// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package outlookcalendar

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/localconfig"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "outlook-calendar"

const (
	UIUnitCalendarPicker             = "calendarPicker"
	UICalendarPickerPortCalendarID   = "calendarId"
	UICalendarPickerPortCalendarName = "calendarName"
)

type Config struct {
	MaxResponseBytes int64  `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
	TenantID         string `json:"tenantId,omitempty" yaml:"tenantId,omitempty"`
	Mailbox          string `json:"mailbox,omitempty" yaml:"mailbox,omitempty"`
}

type Credentials struct {
	AuthMethodID string
	ClientID     string
	ClientSecret sdkgo.SecretString
	AccessToken  sdkgo.SecretString
	RefreshToken sdkgo.SecretString
}

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("outlook-calendar connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("outlook-calendar connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewLocalConnection loads startup configuration and reloads credentials before every provider call.
func NewLocalConnection(store *localconfig.Store, connectionName string, options ...Option) (Connection, error) {
	if store == nil {
		return Connection{}, fmt.Errorf("local connector configuration store is required")
	}
	reference := sdkgo.ConnectionRef{Provider: "microsoft", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("outlook-calendar local connection: %w", err)
	}
	var config Config
	if err := store.DecodeConfiguration(ConnectorID, connectionName, &config); err != nil {
		return Connection{}, err
	}
	credentials := localconfig.NewRefreshingCredentialProvider(store, ConnectorID, connectionName, decodeLocalCredentials, encodeLocalCredentials)
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeLocalCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		AuthMethodID string `json:"auth_method"`
		ClientID     string `json:"client_id"`
		ClientSecret string `json:"client_secret"`
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	if err := localconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		AuthMethodID: fields.AuthMethodID,
		ClientID:     fields.ClientID,
		ClientSecret: sdkgo.NewSecretString(fields.ClientSecret),
		AccessToken:  sdkgo.NewSecretString(fields.AccessToken),
		RefreshToken: sdkgo.NewSecretString(fields.RefreshToken),
	}
	return credentials, credentials.Validate()
}

func encodeLocalCredentials(credentials Credentials) (json.RawMessage, error) {
	fields := struct {
		AuthMethodID string `json:"auth_method"`
		ClientID     string `json:"client_id,omitempty"`
		ClientSecret string `json:"client_secret,omitempty"`
		AccessToken  string `json:"access_token,omitempty"`
		RefreshToken string `json:"refresh_token,omitempty"`
	}{
		AuthMethodID: credentials.AuthMethodID,
		ClientID:     credentials.ClientID,
		ClientSecret: credentials.ClientSecret.Reveal(),
		AccessToken:  credentials.AccessToken.Reveal(),
		RefreshToken: credentials.RefreshToken.Reveal(),
	}
	return json.Marshal(fields)
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("outlook-calendar connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("outlook-calendar connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("outlook-calendar connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("outlook-calendar connector connections cannot be serialized")
}
func (Connection) String() string   { return "outlookcalendar.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "outlookcalendar.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		MaxResponseBytes: 4194304,
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	return config
}

func (config Config) Validate() error {
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	switch credentials.AuthMethodID {
	case "microsoft-oauth":
		if credentials.ClientID == "" {
			return fmt.Errorf("credential client_id is required")
		}
		if credentials.ClientSecret.Reveal() == "" {
			return fmt.Errorf("credential client_secret is required")
		}
		if credentials.AccessToken.Reveal() == "" {
			return fmt.Errorf("credential access_token is required")
		}
		if credentials.RefreshToken.Reveal() == "" {
			return fmt.Errorf("credential refresh_token is required")
		}
	case "app-only":
		if credentials.ClientID == "" {
			return fmt.Errorf("credential client_id is required")
		}
		if credentials.ClientSecret.Reveal() == "" {
			return fmt.Errorf("credential client_secret is required")
		}
	default:
		return fmt.Errorf("credential auth_method is invalid")
	}
	return nil
}

const ListEventsBranchListed sdkgo.BranchID = "listed"
const ListEventsBranchNotFound sdkgo.BranchID = "notFound"
const ListEventsBranchProviderRejected sdkgo.BranchID = "providerRejected"
const ListEventsBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const ListEventsBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var ListEventsDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "listEvents"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ListEventsBranchListed, Description: "One page of events in the window was listed."},
		{ID: ListEventsBranchNotFound, Description: "The calendar does not exist or is not visible to the connection.", Optional: true},
		{ID: ListEventsBranchProviderRejected, Description: "Microsoft Graph conclusively rejected the calendar view.", Optional: true},
		{ID: ListEventsBranchInvalidResponse, Description: "Microsoft Graph returned an invalid or oversized event page.", Optional: true},
		{ID: ListEventsBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type ListEventsResult = sdkgo.QueryResult[ListEventsOutput]

type ListEventsStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                            `connector:"connectorId=outlook-calendar"`
	operationID                    struct{}                                            `connector:"operationId=listEvents"`
	StepType                       string                                              `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                               `connector:"annotations"`
	ConfigurationUI                sdkgo.ConnectorConfigurationUI                      `connector:"configurationUI"`
	Connection                     Connection                                          `connector:"connection"`
	ConnectionName                 string                                              `connector:"connectionName"`
	MapToOperationInput            func(IN) ListEventsInput                            `connector:"mapToOperationInput"`
	Listed                         sdkgo.Target[ListEventsResult]                      `connector:"branch=listed"`
	NotFound                       sdkgo.Target[ListEventsResult]                      `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[ListEventsResult]                      `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[ListEventsResult]                      `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[ListEventsResult]                      `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[ListEventsOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                    `connector:"stepOptionsOverride"`
}

func NewListEventsStep[IN any](config ListEventsStepConfig[IN]) sdkgo.QueryStep[IN, ListEventsInput, ListEventsOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("outlook-calendar connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, ListEventsInput, ListEventsOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.client.ListEvents(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[ListEventsResult] {
			branches := make([]sdkgo.BranchTarget[ListEventsResult], 0, 5)
			if config.Listed.HasStep() {
				branches = append(branches, config.Listed.BranchTarget(ListEventsBranchListed))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(ListEventsBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(ListEventsBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(ListEventsBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(ListEventsBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const GetEventBranchFound sdkgo.BranchID = "found"
const GetEventBranchNotFound sdkgo.BranchID = "notFound"
const GetEventBranchProviderRejected sdkgo.BranchID = "providerRejected"
const GetEventBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const GetEventBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var GetEventDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getEvent"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetEventBranchFound, Description: "The event was read."},
		{ID: GetEventBranchNotFound, Description: "The event does not exist or is not visible to the connection.", Optional: true},
		{ID: GetEventBranchProviderRejected, Description: "Microsoft Graph conclusively rejected the event read.", Optional: true},
		{ID: GetEventBranchInvalidResponse, Description: "Microsoft Graph returned an invalid or oversized event.", Optional: true},
		{ID: GetEventBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type GetEventResult = sdkgo.QueryResult[Event]

type GetEventStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                 `connector:"connectorId=outlook-calendar"`
	operationID                    struct{}                                 `connector:"operationId=getEvent"`
	StepType                       string                                   `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                    `connector:"annotations"`
	ConfigurationUI                sdkgo.ConnectorConfigurationUI           `connector:"configurationUI"`
	Connection                     Connection                               `connector:"connection"`
	ConnectionName                 string                                   `connector:"connectionName"`
	MapToOperationInput            func(IN) GetEventInput                   `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[GetEventResult]             `connector:"branch=found"`
	NotFound                       sdkgo.Target[GetEventResult]             `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[GetEventResult]             `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[GetEventResult]             `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[GetEventResult]             `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[Event]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                         `connector:"stepOptionsOverride"`
}

func NewGetEventStep[IN any](config GetEventStepConfig[IN]) sdkgo.QueryStep[IN, GetEventInput, Event] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("outlook-calendar connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetEventInput, Event]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.client.GetEvent(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[GetEventResult] {
			branches := make([]sdkgo.BranchTarget[GetEventResult], 0, 5)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(GetEventBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(GetEventBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(GetEventBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(GetEventBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(GetEventBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const CreateEventBranchCreated sdkgo.BranchID = "created"
const CreateEventBranchProviderRejected sdkgo.BranchID = "providerRejected"
const CreateEventBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const CreateEventBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var CreateEventDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "createEvent"},
	Branches: []sdkgo.BranchDefinition{
		{ID: CreateEventBranchCreated, Description: "The event that carries the Step's idempotency key exists."},
		{ID: CreateEventBranchProviderRejected, Description: "Microsoft Graph conclusively rejected the event.", Optional: true},
		{ID: CreateEventBranchInvalidResponse, Description: "Microsoft Graph returned an invalid or oversized event response.", Optional: true},
		{ID: CreateEventBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type CreateEventResult = sdkgo.MutationResult[CreateEventOutput]

type CreateEventStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                                `connector:"connectorId=outlook-calendar"`
	operationID                       struct{}                                                `connector:"operationId=createEvent"`
	StepType                          string                                                  `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                   `connector:"annotations"`
	ConfigurationUI                   sdkgo.ConnectorConfigurationUI                          `connector:"configurationUI"`
	Connection                        Connection                                              `connector:"connection"`
	ConnectionName                    string                                                  `connector:"connectionName"`
	MapToOperationInput               func(IN) CreateEventInput                               `connector:"mapToOperationInput"`
	Created                           sdkgo.Target[CreateEventResult]                         `connector:"branch=created"`
	ProviderRejected                  sdkgo.Target[CreateEventResult]                         `connector:"branch=providerRejected,optional"`
	InvalidResponse                   sdkgo.Target[CreateEventResult]                         `connector:"branch=invalidResponse,optional"`
	Defect                            sdkgo.Target[CreateEventResult]                         `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[CreateEventOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewCreateEventStep[IN any](config CreateEventStepConfig[IN]) sdkgo.MutationStep[IN, CreateEventInput, CreateEventOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("outlook-calendar connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, CreateEventInput, CreateEventOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.client.CreateEvent(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[CreateEventResult] {
			branches := make([]sdkgo.BranchTarget[CreateEventResult], 0, 4)
			if config.Created.HasStep() {
				branches = append(branches, config.Created.BranchTarget(CreateEventBranchCreated))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(CreateEventBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(CreateEventBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(CreateEventBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const UpdateEventBranchUpdated sdkgo.BranchID = "updated"
const UpdateEventBranchNotFound sdkgo.BranchID = "notFound"
const UpdateEventBranchProviderRejected sdkgo.BranchID = "providerRejected"
const UpdateEventBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const UpdateEventBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var UpdateEventDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "updateEvent"},
	Branches: []sdkgo.BranchDefinition{
		{ID: UpdateEventBranchUpdated, Description: "The event holds the requested values."},
		{ID: UpdateEventBranchNotFound, Description: "The event does not exist, is cancelled, or is not visible to the connection.", Optional: true},
		{ID: UpdateEventBranchProviderRejected, Description: "Microsoft Graph conclusively rejected the event change.", Optional: true},
		{ID: UpdateEventBranchInvalidResponse, Description: "Microsoft Graph returned an invalid or oversized event response.", Optional: true},
		{ID: UpdateEventBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type UpdateEventResult = sdkgo.MutationResult[UpdateEventOutput]

type UpdateEventStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                                `connector:"connectorId=outlook-calendar"`
	operationID                       struct{}                                                `connector:"operationId=updateEvent"`
	StepType                          string                                                  `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                   `connector:"annotations"`
	ConfigurationUI                   sdkgo.ConnectorConfigurationUI                          `connector:"configurationUI"`
	Connection                        Connection                                              `connector:"connection"`
	ConnectionName                    string                                                  `connector:"connectionName"`
	MapToOperationInput               func(IN) UpdateEventInput                               `connector:"mapToOperationInput"`
	Updated                           sdkgo.Target[UpdateEventResult]                         `connector:"branch=updated"`
	NotFound                          sdkgo.Target[UpdateEventResult]                         `connector:"branch=notFound,optional"`
	ProviderRejected                  sdkgo.Target[UpdateEventResult]                         `connector:"branch=providerRejected,optional"`
	InvalidResponse                   sdkgo.Target[UpdateEventResult]                         `connector:"branch=invalidResponse,optional"`
	Defect                            sdkgo.Target[UpdateEventResult]                         `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[UpdateEventOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewUpdateEventStep[IN any](config UpdateEventStepConfig[IN]) sdkgo.MutationStep[IN, UpdateEventInput, UpdateEventOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("outlook-calendar connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, UpdateEventInput, UpdateEventOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.client.UpdateEvent(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[UpdateEventResult] {
			branches := make([]sdkgo.BranchTarget[UpdateEventResult], 0, 5)
			if config.Updated.HasStep() {
				branches = append(branches, config.Updated.BranchTarget(UpdateEventBranchUpdated))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(UpdateEventBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(UpdateEventBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(UpdateEventBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(UpdateEventBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const QueryFreeBusyBranchQueried sdkgo.BranchID = "queried"
const QueryFreeBusyBranchIncomplete sdkgo.BranchID = "incomplete"
const QueryFreeBusyBranchProviderRejected sdkgo.BranchID = "providerRejected"
const QueryFreeBusyBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const QueryFreeBusyBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var QueryFreeBusyDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "queryFreeBusy"},
	Branches: []sdkgo.BranchDefinition{
		{ID: QueryFreeBusyBranchQueried, Description: "Microsoft Graph reported known availability for every requested schedule."},
		{ID: QueryFreeBusyBranchIncomplete, Description: "Microsoft Graph reported an error, an unknown status, or no data for at least one schedule, so its availability is unknown.", Optional: true},
		{ID: QueryFreeBusyBranchProviderRejected, Description: "Microsoft Graph conclusively rejected the schedule query.", Optional: true},
		{ID: QueryFreeBusyBranchInvalidResponse, Description: "Microsoft Graph returned an invalid or oversized schedule response.", Optional: true},
		{ID: QueryFreeBusyBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type QueryFreeBusyResult = sdkgo.QueryResult[QueryFreeBusyOutput]

type QueryFreeBusyStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                               `connector:"connectorId=outlook-calendar"`
	operationID                    struct{}                                               `connector:"operationId=queryFreeBusy"`
	StepType                       string                                                 `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                  `connector:"annotations"`
	ConfigurationUI                sdkgo.ConnectorConfigurationUI                         `connector:"configurationUI"`
	Connection                     Connection                                             `connector:"connection"`
	ConnectionName                 string                                                 `connector:"connectionName"`
	MapToOperationInput            func(IN) QueryFreeBusyInput                            `connector:"mapToOperationInput"`
	Queried                        sdkgo.Target[QueryFreeBusyResult]                      `connector:"branch=queried"`
	Incomplete                     sdkgo.Target[QueryFreeBusyResult]                      `connector:"branch=incomplete,optional"`
	ProviderRejected               sdkgo.Target[QueryFreeBusyResult]                      `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[QueryFreeBusyResult]                      `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[QueryFreeBusyResult]                      `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[QueryFreeBusyOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                       `connector:"stepOptionsOverride"`
}

func NewQueryFreeBusyStep[IN any](config QueryFreeBusyStepConfig[IN]) sdkgo.QueryStep[IN, QueryFreeBusyInput, QueryFreeBusyOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("outlook-calendar connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, QueryFreeBusyInput, QueryFreeBusyOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.client.QueryFreeBusy(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[QueryFreeBusyResult] {
			branches := make([]sdkgo.BranchTarget[QueryFreeBusyResult], 0, 5)
			if config.Queried.HasStep() {
				branches = append(branches, config.Queried.BranchTarget(QueryFreeBusyBranchQueried))
			}
			if config.Incomplete.HasStep() {
				branches = append(branches, config.Incomplete.BranchTarget(QueryFreeBusyBranchIncomplete))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(QueryFreeBusyBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(QueryFreeBusyBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(QueryFreeBusyBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
