// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package mockfixture

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig/provider"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "mock-fixture"

type Config struct {
}

type Credentials struct {
}

// CredentialSource is the credential provider New requires: this connector never refreshes its credentials.
type CredentialSource = sdkgo.CredentialProvider[Credentials]

type Connection struct {
	client     *Client
	operations Operations
	reference  sdkgo.ConnectionRef
}

// Operations returns the operations that this connector's Step factories invoke, one accessor per operation.
// NewConnection uses the client's operations; NewConnectionWithOperations accepts another implementation.
type Operations interface {
	GetWidget() sdkgo.Query[GetWidgetInput, Widget]
	ListWidgets() sdkgo.Query[ListWidgetsInput, WidgetPage]
	CreateWidget() sdkgo.Mutation[CreateWidgetInput, Widget]
}

type clientOperations struct{ client *Client }

func (operations clientOperations) GetWidget() sdkgo.Query[GetWidgetInput, Widget] {
	return operations.client.GetWidget()
}
func (operations clientOperations) ListWidgets() sdkgo.Query[ListWidgetsInput, WidgetPage] {
	return operations.client.ListWidgets()
}
func (operations clientOperations) CreateWidget() sdkgo.Mutation[CreateWidgetInput, Widget] {
	return operations.client.CreateWidget()
}

// NewConnection wraps a client built with New, such as a test client with a static credential provider.
// Applications open declared connections with NewProjectConnection instead.
func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("mock-fixture connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("mock-fixture connector connection: %w", err)
	}
	return Connection{client: client, operations: clientOperations{client: client}, reference: reference}, nil
}

// NewConnectionWithOperations binds other operations, such as a generated mock package's, to a connection.
// The connection serves operation Steps only: Trigger factories and runners require NewConnection.
func NewConnectionWithOperations(operations Operations, reference sdkgo.ConnectionRef) (Connection, error) {
	if operations == nil {
		return Connection{}, fmt.Errorf("mock-fixture connector operations are required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("mock-fixture connector connection: %w", err)
	}
	return Connection{operations: operations, reference: reference}, nil
}

// NewProjectConnection opens the connection that dex-app.yaml declares as connectionName from the
// loaded project configuration. It reads ordinary settings now and resolves credentials during each call.
func NewProjectConnection(project *projectconfig.LoadedProject, connectionName string, options ...Option) (Connection, error) {
	if project == nil {
		return Connection{}, fmt.Errorf("mock-fixture connection requires the loaded project configuration")
	}
	reference := sdkgo.ConnectionRef{Provider: "example", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("mock-fixture connection: %w", err)
	}
	key := projectconfig.ConnectionKey{ConnectorID: ConnectorID, ConnectionName: connectionName}
	var config Config
	if err := project.Configuration.DecodeConnectionConfiguration(key, &config); err != nil {
		return Connection{}, fmt.Errorf("mock-fixture connection %q settings: %w", connectionName, err)
	}
	credentials, err := provider.NewCredentialProvider(project.Connections, key, decodeCredentials)
	if err != nil {
		return Connection{}, err
	}
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
	}
	if err := projectconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{}
	return credentials, credentials.Validate()
}

func (connection Connection) validate() error {
	if connection.client == nil && connection.operations != nil {
		return fmt.Errorf("mock-fixture connector connection from NewConnectionWithOperations serves only operation Steps")
	}
	if connection.client == nil {
		return fmt.Errorf("mock-fixture connector connection is required")
	}
	return connection.reference.Validate()
}

func (connection Connection) validateOperations() error {
	if connection.operations == nil {
		return fmt.Errorf("mock-fixture connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("mock-fixture connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("mock-fixture connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("mock-fixture connector connections cannot be serialized")
}
func (Connection) String() string   { return "mockfixture.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "mockfixture.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{}
}

func withConfigDefaults(config Config) Config {
	return config
}

func (config Config) Validate() error {
	return nil
}

func (credentials Credentials) Validate() error {
	return nil
}

const GetWidgetBranchFound sdkgo.BranchID = "found"
const GetWidgetBranchNotFound sdkgo.BranchID = "notFound"
const GetWidgetBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var GetWidgetDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getWidget"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetWidgetBranchFound, Description: "The widget was read."},
		{ID: GetWidgetBranchNotFound, Description: "The widget does not exist.", Optional: true},
		{ID: GetWidgetBranchDefect, Description: "The input is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type GetWidgetResult = sdkgo.QueryResult[Widget]

type GetWidgetStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                  `connector:"connectorId=mock-fixture"`
	operationID                    struct{}                                  `connector:"operationId=getWidget"`
	StepType                       string                                    `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                     `connector:"annotations"`
	Connection                     Connection                                `connector:"connection"`
	ConnectionName                 string                                    `connector:"connectionName"`
	MapToOperationInput            func(IN) GetWidgetInput                   `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[GetWidgetResult]             `connector:"branch=found"`
	NotFound                       sdkgo.Target[GetWidgetResult]             `connector:"branch=notFound,optional"`
	Defect                         sdkgo.Target[GetWidgetResult]             `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[Widget]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                          `connector:"stepOptionsOverride"`
}

func NewGetWidgetStep[IN any](config GetWidgetStepConfig[IN]) sdkgo.QueryStep[IN, GetWidgetInput, Widget] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("mock-fixture connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetWidgetInput, Widget]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.operations.GetWidget(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[GetWidgetResult] {
			branches := make([]sdkgo.BranchTarget[GetWidgetResult], 0, 3)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(GetWidgetBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(GetWidgetBranchNotFound))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(GetWidgetBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const ListWidgetsBranchListed sdkgo.BranchID = "listed"
const ListWidgetsBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var ListWidgetsDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "listWidgets"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ListWidgetsBranchListed, Description: "One page was listed."},
		{ID: ListWidgetsBranchDefect, Description: "The input is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type ListWidgetsResult = sdkgo.QueryResult[WidgetPage]

type ListWidgetsStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                      `connector:"connectorId=mock-fixture"`
	operationID                    struct{}                                      `connector:"operationId=listWidgets"`
	StepType                       string                                        `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                         `connector:"annotations"`
	Connection                     Connection                                    `connector:"connection"`
	ConnectionName                 string                                        `connector:"connectionName"`
	MapToOperationInput            func(IN) ListWidgetsInput                     `connector:"mapToOperationInput"`
	Listed                         sdkgo.Target[ListWidgetsResult]               `connector:"branch=listed"`
	Defect                         sdkgo.Target[ListWidgetsResult]               `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[WidgetPage]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                              `connector:"stepOptionsOverride"`
}

func NewListWidgetsStep[IN any](config ListWidgetsStepConfig[IN]) sdkgo.QueryStep[IN, ListWidgetsInput, WidgetPage] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("mock-fixture connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, ListWidgetsInput, WidgetPage]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.operations.ListWidgets(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[ListWidgetsResult] {
			branches := make([]sdkgo.BranchTarget[ListWidgetsResult], 0, 2)
			if config.Listed.HasStep() {
				branches = append(branches, config.Listed.BranchTarget(ListWidgetsBranchListed))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(ListWidgetsBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const CreateWidgetBranchCreated sdkgo.BranchID = "created"
const CreateWidgetBranchUncertain sdkgo.BranchID = sdkgo.UncertainBranchID
const CreateWidgetBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var CreateWidgetDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "createWidget"},
	Branches: []sdkgo.BranchDefinition{
		{ID: CreateWidgetBranchCreated, Description: "The widget was created."},
		{ID: CreateWidgetBranchUncertain, Description: "The create outcome is unknown.", Optional: true},
		{ID: CreateWidgetBranchDefect, Description: "The input is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type CreateWidgetResult = sdkgo.MutationResult[Widget]

type CreateWidgetStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                     `connector:"connectorId=mock-fixture"`
	operationID                       struct{}                                     `connector:"operationId=createWidget"`
	StepType                          string                                       `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                        `connector:"annotations"`
	Connection                        Connection                                   `connector:"connection"`
	ConnectionName                    string                                       `connector:"connectionName"`
	MapToOperationInput               func(IN) CreateWidgetInput                   `connector:"mapToOperationInput"`
	Created                           sdkgo.Target[CreateWidgetResult]             `connector:"branch=created"`
	Uncertain                         sdkgo.Target[CreateWidgetResult]             `connector:"branch=uncertain,optional"`
	Defect                            sdkgo.Target[CreateWidgetResult]             `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[Widget]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                             `connector:"stepOptionsOverride"`
}

func NewCreateWidgetStep[IN any](config CreateWidgetStepConfig[IN]) sdkgo.MutationStep[IN, CreateWidgetInput, Widget] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("mock-fixture connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, CreateWidgetInput, Widget]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.operations.CreateWidget(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[CreateWidgetResult] {
			branches := make([]sdkgo.BranchTarget[CreateWidgetResult], 0, 3)
			if config.Created.HasStep() {
				branches = append(branches, config.Created.BranchTarget(CreateWidgetBranchCreated))
			}
			if config.Uncertain.HasStep() {
				branches = append(branches, config.Uncertain.BranchTarget(CreateWidgetBranchUncertain))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(CreateWidgetBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
