apiVersion: connectors.dex.dev/directory-list/v1alpha1
kind: ConnectorDirectoryList
directories:
  - connectors/anthropic
  - connectors/deepseek
  - connectors/github
  - connectors/google/gemini
  - connectors/google/gmail
  - connectors/google/spreadsheet
  - connectors/linkedin
  - connectors/meta
  - connectors/mistral
  - connectors/openai
  - connectors/slack
  - connectors/stripe
  - connectors/xai
