// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

// Package gmailmock scripts the gmail connector's operations in application tests. New returns a
// Connection whose operations answer from connectormock scripts, with each query's manifest default installed.
package gmailmock

import (
	"testing"
	"time"

	"github.com/superdurable/dex-connectors-library/connectors/google/gmail"
	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/connectormock"
)

// Mock is a scripted gmail connection. Script each operation through its accessor.
type Mock struct {
	connection     gmail.Connection
	getMessage     *connectormock.Query[gmail.GetMessageInput, gmail.Message]
	sendMessage    *connectormock.Mutation[gmail.SendMessageInput, gmail.SendMessageOutput]
	replyToMessage *connectormock.Mutation[gmail.ReplyToMessageInput, gmail.SendMessageOutput]
}

// New returns a mock connection named connectionName. Unscripted calls fail t, except a query's call that its
// manifest default answers.
func New(t testing.TB, connectionName string) *Mock {
	t.Helper()
	mock := &Mock{
		getMessage:     connectormock.NewQuery[gmail.GetMessageInput, gmail.Message](t, gmail.GetMessageDefinition),
		sendMessage:    connectormock.NewMutation[gmail.SendMessageInput, gmail.SendMessageOutput](t, gmail.SendMessageDefinition),
		replyToMessage: connectormock.NewMutation[gmail.ReplyToMessageInput, gmail.SendMessageOutput](t, gmail.ReplyToMessageDefinition),
	}
	mock.getMessage.Default(GetMessageDefault())
	connection, err := gmail.NewConnectionWithOperations(mockOperations{mock: mock}, sdkgo.ConnectionRef{Provider: "google", Name: connectionName})
	if err != nil {
		t.Fatalf("gmail mock connection: %v", err)
	}
	mock.connection = connection
	return mock
}

// Connection returns the typed connection to pass to the connector's Step factories.
func (mock *Mock) Connection() gmail.Connection { return mock.connection }

// GetMessage returns the getMessage script.
func (mock *Mock) GetMessage() *connectormock.Query[gmail.GetMessageInput, gmail.Message] {
	return mock.getMessage
}

// SendMessage returns the sendMessage script.
func (mock *Mock) SendMessage() *connectormock.Mutation[gmail.SendMessageInput, gmail.SendMessageOutput] {
	return mock.sendMessage
}

// ReplyToMessage returns the replyToMessage script.
func (mock *Mock) ReplyToMessage() *connectormock.Mutation[gmail.ReplyToMessageInput, gmail.SendMessageOutput] {
	return mock.replyToMessage
}

type mockOperations struct{ mock *Mock }

func (operations mockOperations) GetMessage() sdkgo.Query[gmail.GetMessageInput, gmail.Message] {
	return operations.mock.getMessage
}
func (operations mockOperations) SendMessage() sdkgo.Mutation[gmail.SendMessageInput, gmail.SendMessageOutput] {
	return operations.mock.sendMessage
}
func (operations mockOperations) ReplyToMessage() sdkgo.Mutation[gmail.ReplyToMessageInput, gmail.SendMessageOutput] {
	return operations.mock.replyToMessage
}

// GetMessageRead selects the read branch: The Gmail message was read.
func GetMessageRead(value gmail.Message, failure *sdkgo.Failure) connectormock.Case[gmail.Message] {
	return connectormock.Branch(gmail.GetMessageBranchRead, value, failure)
}

// GetMessageNotFound selects the notFound branch: The Gmail message does not exist.
func GetMessageNotFound(value gmail.Message, failure *sdkgo.Failure) connectormock.Case[gmail.Message] {
	return connectormock.Branch(gmail.GetMessageBranchNotFound, value, failure)
}

// GetMessageProviderRejected selects the providerRejected branch: Gmail conclusively rejected the message query.
func GetMessageProviderRejected(value gmail.Message, failure *sdkgo.Failure) connectormock.Case[gmail.Message] {
	return connectormock.Branch(gmail.GetMessageBranchProviderRejected, value, failure)
}

// GetMessageInvalidResponse selects the invalidResponse branch: Gmail returned an invalid or oversized message response.
func GetMessageInvalidResponse(value gmail.Message, failure *sdkgo.Failure) connectormock.Case[gmail.Message] {
	return connectormock.Branch(gmail.GetMessageBranchInvalidResponse, value, failure)
}

// GetMessageDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func GetMessageDefect(value gmail.Message, failure *sdkgo.Failure) connectormock.Case[gmail.Message] {
	return connectormock.Branch(gmail.GetMessageBranchDefect, value, failure)
}

// GetMessageRetry asks Dex to retry the getMessage Step, after the delay when it is positive.
func GetMessageRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[gmail.Message] {
	return connectormock.Retry[gmail.Message](failure, after)
}

// GetMessageCustomerQuestion is the manifest mock customerQuestion: A plain-text and HTML customer question in an existing thread, with its threading headers and labels.
func GetMessageCustomerQuestion() connectormock.Case[gmail.Message] {
	value := connectormock.MustDecodeOutput[gmail.Message](`{"messageId":"18c0a1b2c3d4e5f6","threadId":"18c0a1b2c3d4e5f0","rfcMessageId":"\u003cquestion-1@mail.example.com\u003e","inReplyTo":"\u003cwelcome-1@mail.example.com\u003e","references":"\u003cwelcome-1@mail.example.com\u003e","from":"Ada Customer \u003cada@example.com\u003e","replyTo":"ada.support@example.com","to":["support@example.org"],"subject":"Re: Order 1042 has not arrived","textBody":"Hello, my order 1042 has not arrived yet. Can you check?","htmlBody":"\u003cp\u003eHello, my order 1042 has not arrived yet. Can you check?\u003c/p\u003e","snippet":"Hello, my order 1042 has not arrived yet.","receivedAt":"2026-03-04T09:15:00Z","labelIds":["INBOX","UNREAD"]}`)
	return connectormock.Branch(gmail.GetMessageBranchRead, value, nil)
}

// GetMessageDeletedMessage is the manifest mock deletedMessage: The message was deleted or never existed in the mailbox.
func GetMessageDeletedMessage() connectormock.Case[gmail.Message] {
	var value gmail.Message
	return connectormock.Branch(gmail.GetMessageBranchNotFound, value, &sdkgo.Failure{Kind: sdkgo.FailureNotFound, Message: "The Gmail message does not exist."})
}

// GetMessageRevokedGrant is the manifest mock revokedGrant: Gmail rejected the read because the grant lost the required scope.
func GetMessageRevokedGrant() connectormock.Case[gmail.Message] {
	var value gmail.Message
	return connectormock.Branch(gmail.GetMessageBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthorization, Message: "Gmail rejected the message query for the granted scopes."})
}

// GetMessageMalformedPayload is the manifest mock malformedPayload: Gmail returned a message payload that cannot be decoded.
func GetMessageMalformedPayload() connectormock.Case[gmail.Message] {
	var value gmail.Message
	return connectormock.Branch(gmail.GetMessageBranchInvalidResponse, value, &sdkgo.Failure{Kind: sdkgo.FailureProtocol, Message: "Gmail returned an invalid message payload."})
}

// GetMessageEmptyMessageID is the manifest mock emptyMessageID: The input has no message ID, so no request is sent.
func GetMessageEmptyMessageID() connectormock.Case[gmail.Message] {
	var value gmail.Message
	return connectormock.Branch(gmail.GetMessageBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "The message ID is required."})
}

// GetMessageRateLimited is the manifest mock rateLimited: Gmail throttles the read once.
func GetMessageRateLimited() connectormock.Case[gmail.Message] {
	return connectormock.Retry[gmail.Message](sdkgo.Failure{Kind: sdkgo.FailureRateLimit, Message: "Gmail rate limit was reached."}, time.Duration(1000000000))
}

// GetMessageDefault is the manifest default, customerQuestion, which New installs.
func GetMessageDefault() connectormock.Case[gmail.Message] { return GetMessageCustomerQuestion() }

// SendMessageSent selects the sent branch: Gmail accepted the message and returned its identity.
func SendMessageSent(value gmail.SendMessageOutput, failure *sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Branch(gmail.SendMessageBranchSent, value, failure)
}

// SendMessageProviderRejected selects the providerRejected branch: Gmail conclusively rejected the message.
func SendMessageProviderRejected(value gmail.SendMessageOutput, failure *sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Branch(gmail.SendMessageBranchProviderRejected, value, failure)
}

// SendMessageUncertain returns an uncertain sendMessage outcome.
func SendMessageUncertain(value gmail.SendMessageOutput, failure sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Uncertain(value, failure)
}

// SendMessageDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func SendMessageDefect(value gmail.SendMessageOutput, failure *sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Branch(gmail.SendMessageBranchDefect, value, failure)
}

// SendMessageRetry asks Dex to retry the sendMessage Step, after the delay when it is positive.
func SendMessageRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Retry[gmail.SendMessageOutput](failure, after)
}

// SendMessageSentToCustomer is the manifest mock sentToCustomer: Gmail accepted the message and returned its identity.
func SendMessageSentToCustomer() connectormock.Case[gmail.SendMessageOutput] {
	value := connectormock.MustDecodeOutput[gmail.SendMessageOutput](`{"sender":"support@example.org","recipients":["ada@example.com"],"messageId":"18c0a1b2c3d4e600","threadId":"18c0a1b2c3d4e600"}`)
	return connectormock.Branch(gmail.SendMessageBranchSent, value, nil)
}

// SendMessageInvalidRecipient is the manifest mock invalidRecipient: Gmail rejected the message because a recipient address is invalid.
func SendMessageInvalidRecipient() connectormock.Case[gmail.SendMessageOutput] {
	var value gmail.SendMessageOutput
	return connectormock.Branch(gmail.SendMessageBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureProviderRejection, Message: "Gmail rejected the message recipients."})
}

// SendMessageConnectionLost is the manifest mock connectionLost: The connection closed after the message was sent, so delivery is unknown.
func SendMessageConnectionLost() connectormock.Case[gmail.SendMessageOutput] {
	var value gmail.SendMessageOutput
	return connectormock.Uncertain(value, sdkgo.Failure{Kind: sdkgo.FailureTransport, Message: "The connection closed before Gmail answered."})
}

// SendMessageNoRecipients is the manifest mock noRecipients: The message has no recipient, so no request is sent.
func SendMessageNoRecipients() connectormock.Case[gmail.SendMessageOutput] {
	var value gmail.SendMessageOutput
	return connectormock.Branch(gmail.SendMessageBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "At least one recipient is required."})
}

// SendMessageUnavailable is the manifest mock unavailable: Gmail is briefly unavailable before the message is sent.
func SendMessageUnavailable() connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Retry[gmail.SendMessageOutput](sdkgo.Failure{Kind: sdkgo.FailureAvailability, Message: "Gmail is temporarily unavailable."}, time.Duration(0))
}

// ReplyToMessageSent selects the sent branch: Gmail accepted the reply and returned its identity.
func ReplyToMessageSent(value gmail.SendMessageOutput, failure *sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Branch(gmail.ReplyToMessageBranchSent, value, failure)
}

// ReplyToMessageProviderRejected selects the providerRejected branch: Gmail conclusively rejected the reply.
func ReplyToMessageProviderRejected(value gmail.SendMessageOutput, failure *sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Branch(gmail.ReplyToMessageBranchProviderRejected, value, failure)
}

// ReplyToMessageInvalidResponse selects the invalidResponse branch: Gmail returned an invalid or oversized source message response before sending the reply.
func ReplyToMessageInvalidResponse(value gmail.SendMessageOutput, failure *sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Branch(gmail.ReplyToMessageBranchInvalidResponse, value, failure)
}

// ReplyToMessageUncertain returns an uncertain replyToMessage outcome.
func ReplyToMessageUncertain(value gmail.SendMessageOutput, failure sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Uncertain(value, failure)
}

// ReplyToMessageDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func ReplyToMessageDefect(value gmail.SendMessageOutput, failure *sdkgo.Failure) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Branch(gmail.ReplyToMessageBranchDefect, value, failure)
}

// ReplyToMessageRetry asks Dex to retry the replyToMessage Step, after the delay when it is positive.
func ReplyToMessageRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[gmail.SendMessageOutput] {
	return connectormock.Retry[gmail.SendMessageOutput](failure, after)
}

// ReplyToMessageRepliedInThread is the manifest mock repliedInThread: Gmail accepted the reply in the source message's thread.
func ReplyToMessageRepliedInThread() connectormock.Case[gmail.SendMessageOutput] {
	value := connectormock.MustDecodeOutput[gmail.SendMessageOutput](`{"sender":"support@example.org","recipients":["ada.support@example.com"],"messageId":"18c0a1b2c3d4e700","threadId":"18c0a1b2c3d4e5f0"}`)
	return connectormock.Branch(gmail.ReplyToMessageBranchSent, value, nil)
}

// ReplyToMessageSourceMissing is the manifest mock sourceMissing: Gmail rejected the reply because the source message no longer exists.
func ReplyToMessageSourceMissing() connectormock.Case[gmail.SendMessageOutput] {
	var value gmail.SendMessageOutput
	return connectormock.Branch(gmail.ReplyToMessageBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureNotFound, Message: "The source Gmail message does not exist."})
}

// ReplyToMessageMalformedSource is the manifest mock malformedSource: Gmail returned a source message that cannot be decoded, so no reply is sent.
func ReplyToMessageMalformedSource() connectormock.Case[gmail.SendMessageOutput] {
	var value gmail.SendMessageOutput
	return connectormock.Branch(gmail.ReplyToMessageBranchInvalidResponse, value, &sdkgo.Failure{Kind: sdkgo.FailureProtocol, Message: "Gmail returned an invalid source message."})
}

// ReplyToMessageConnectionLost is the manifest mock connectionLost: The connection closed after the reply was sent, so delivery is unknown.
func ReplyToMessageConnectionLost() connectormock.Case[gmail.SendMessageOutput] {
	var value gmail.SendMessageOutput
	return connectormock.Uncertain(value, sdkgo.Failure{Kind: sdkgo.FailureTransport, Message: "The connection closed before Gmail answered."})
}

// ReplyToMessageEmptyBody is the manifest mock emptyBody: The reply has no body, so no request is sent.
func ReplyToMessageEmptyBody() connectormock.Case[gmail.SendMessageOutput] {
	var value gmail.SendMessageOutput
	return connectormock.Branch(gmail.ReplyToMessageBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "The reply body is required."})
}
