// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package s3

import (
	"encoding/json"
	"fmt"
	"net/url"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/localconfig"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "amazon-s3"

type AddressingStyle string

const (
	AddressingStyleAuto          AddressingStyle = "auto"
	AddressingStyleVirtualHosted AddressingStyle = "virtualHosted"
	AddressingStylePath          AddressingStyle = "path"
)

type Config struct {
	Region           string          `json:"region,omitempty" yaml:"region,omitempty"`
	Endpoint         string          `json:"endpoint,omitempty" yaml:"endpoint,omitempty"`
	AddressingStyle  AddressingStyle `json:"addressingStyle,omitempty" yaml:"addressingStyle,omitempty"`
	DefaultBucket    string          `json:"defaultBucket,omitempty" yaml:"defaultBucket,omitempty"`
	ListPageSize     int64           `json:"listPageSize,omitempty" yaml:"listPageSize,omitempty"`
	MaxResponseBytes int64           `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
	MaxTextBytes     int64           `json:"maxTextBytes,omitempty" yaml:"maxTextBytes,omitempty"`
	MaxUploadBytes   int64           `json:"maxUploadBytes,omitempty" yaml:"maxUploadBytes,omitempty"`
}

type Credentials struct {
	AccessKeyID     sdkgo.SecretString
	SecretAccessKey sdkgo.SecretString
	SessionToken    sdkgo.SecretString
}

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("amazon-s3 connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("amazon-s3 connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewLocalConnection loads startup configuration and reloads credentials before every provider call.
func NewLocalConnection(store *localconfig.Store, connectionName string, options ...Option) (Connection, error) {
	if store == nil {
		return Connection{}, fmt.Errorf("local connector configuration store is required")
	}
	reference := sdkgo.ConnectionRef{Provider: "amazon-s3", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("amazon-s3 local connection: %w", err)
	}
	var config Config
	if err := store.DecodeConfiguration(ConnectorID, connectionName, &config); err != nil {
		return Connection{}, err
	}
	credentials := localconfig.NewCredentialProvider(store, ConnectorID, connectionName, decodeLocalCredentials)
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeLocalCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		AccessKeyID     string `json:"access_key_id"`
		SecretAccessKey string `json:"secret_access_key"`
		SessionToken    string `json:"session_token"`
	}
	if err := localconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		AccessKeyID:     sdkgo.NewSecretString(fields.AccessKeyID),
		SecretAccessKey: sdkgo.NewSecretString(fields.SecretAccessKey),
		SessionToken:    sdkgo.NewSecretString(fields.SessionToken),
	}
	return credentials, credentials.Validate()
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("amazon-s3 connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("amazon-s3 connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("amazon-s3 connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("amazon-s3 connector connections cannot be serialized")
}
func (Connection) String() string   { return "s3.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "s3.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		Region:           "us-east-1",
		AddressingStyle:  AddressingStyle("auto"),
		ListPageSize:     100,
		MaxResponseBytes: 4194304,
		MaxTextBytes:     1048576,
		MaxUploadBytes:   1048576,
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.Region == "" {
		config.Region = defaults.Region
	}
	if config.AddressingStyle == "" {
		config.AddressingStyle = defaults.AddressingStyle
	}
	if config.ListPageSize == 0 {
		config.ListPageSize = defaults.ListPageSize
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	if config.MaxTextBytes == 0 {
		config.MaxTextBytes = defaults.MaxTextBytes
	}
	if config.MaxUploadBytes == 0 {
		config.MaxUploadBytes = defaults.MaxUploadBytes
	}
	return config
}

func (config Config) Validate() error {
	if config.Endpoint != "" {
		parsed, err := url.Parse(config.Endpoint)
		if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
			return fmt.Errorf("configuration endpoint must be an absolute URL")
		}
	}
	switch config.AddressingStyle {
	case "", "auto", "virtualHosted", "path":
	default:
		return fmt.Errorf("configuration addressingStyle is invalid")
	}
	if config.ListPageSize < 0 {
		return fmt.Errorf("configuration listPageSize cannot be negative")
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	if config.MaxTextBytes < 0 {
		return fmt.Errorf("configuration maxTextBytes cannot be negative")
	}
	if config.MaxUploadBytes < 0 {
		return fmt.Errorf("configuration maxUploadBytes cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	if credentials.AccessKeyID.Reveal() == "" {
		return fmt.Errorf("credential access_key_id is required")
	}
	if credentials.SecretAccessKey.Reveal() == "" {
		return fmt.Errorf("credential secret_access_key is required")
	}
	return nil
}

const ListObjectsBranchFound sdkgo.BranchID = "found"
const ListObjectsBranchNotFound sdkgo.BranchID = "notFound"
const ListObjectsBranchProviderRejected sdkgo.BranchID = "providerRejected"
const ListObjectsBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const ListObjectsBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var ListObjectsDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "listObjects"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ListObjectsBranchFound, Description: "The page holds objects or common prefixes, or more pages remain."},
		{ID: ListObjectsBranchNotFound, Description: "No object matched the prefix and no further page remains.", Optional: true},
		{ID: ListObjectsBranchProviderRejected, Description: "The store conclusively rejected the list, such as a missing bucket, a wrong Region, invalid credentials, or missing s3:ListBucket permission.", Optional: true},
		{ID: ListObjectsBranchInvalidResponse, Description: "The store returned an invalid or oversized list page.", Optional: true},
		{ID: ListObjectsBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type ListObjectsResult = sdkgo.QueryResult[ListObjectsOutput]

type ListObjectsStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                             `connector:"connectorId=amazon-s3"`
	operationID                    struct{}                                             `connector:"operationId=listObjects"`
	StepType                       string                                               `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                `connector:"annotations"`
	Connection                     Connection                                           `connector:"connection"`
	ConnectionName                 string                                               `connector:"connectionName"`
	MapToOperationInput            func(IN) ListObjectsInput                            `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[ListObjectsResult]                      `connector:"branch=found"`
	NotFound                       sdkgo.Target[ListObjectsResult]                      `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[ListObjectsResult]                      `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[ListObjectsResult]                      `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[ListObjectsResult]                      `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[ListObjectsOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                     `connector:"stepOptionsOverride"`
}

func NewListObjectsStep[IN any](config ListObjectsStepConfig[IN]) sdkgo.QueryStep[IN, ListObjectsInput, ListObjectsOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("amazon-s3 connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, ListObjectsInput, ListObjectsOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.ListObjects(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[ListObjectsResult] {
			branches := make([]sdkgo.BranchTarget[ListObjectsResult], 0, 5)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(ListObjectsBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(ListObjectsBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(ListObjectsBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(ListObjectsBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(ListObjectsBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const HeadObjectBranchFound sdkgo.BranchID = "found"
const HeadObjectBranchNotFound sdkgo.BranchID = "notFound"
const HeadObjectBranchProviderRejected sdkgo.BranchID = "providerRejected"
const HeadObjectBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const HeadObjectBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var HeadObjectDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "headObject"},
	Branches: []sdkgo.BranchDefinition{
		{ID: HeadObjectBranchFound, Description: "The store returned the object's metadata."},
		{ID: HeadObjectBranchNotFound, Description: "The object, or its bucket, does not exist; a HEAD response cannot say which.", Optional: true},
		{ID: HeadObjectBranchProviderRejected, Description: "The store conclusively rejected the read, such as a wrong Region, invalid credentials, or missing s3:GetObject permission.", Optional: true},
		{ID: HeadObjectBranchInvalidResponse, Description: "The store returned metadata without a valid size or modification time.", Optional: true},
		{ID: HeadObjectBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type HeadObjectResult = sdkgo.QueryResult[ObjectMetadata]

type HeadObjectStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                          `connector:"connectorId=amazon-s3"`
	operationID                    struct{}                                          `connector:"operationId=headObject"`
	StepType                       string                                            `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                             `connector:"annotations"`
	Connection                     Connection                                        `connector:"connection"`
	ConnectionName                 string                                            `connector:"connectionName"`
	MapToOperationInput            func(IN) HeadObjectInput                          `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[HeadObjectResult]                    `connector:"branch=found"`
	NotFound                       sdkgo.Target[HeadObjectResult]                    `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[HeadObjectResult]                    `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[HeadObjectResult]                    `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[HeadObjectResult]                    `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[ObjectMetadata]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                  `connector:"stepOptionsOverride"`
}

func NewHeadObjectStep[IN any](config HeadObjectStepConfig[IN]) sdkgo.QueryStep[IN, HeadObjectInput, ObjectMetadata] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("amazon-s3 connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, HeadObjectInput, ObjectMetadata]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.HeadObject(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[HeadObjectResult] {
			branches := make([]sdkgo.BranchTarget[HeadObjectResult], 0, 5)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(HeadObjectBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(HeadObjectBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(HeadObjectBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(HeadObjectBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(HeadObjectBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const GetObjectTextBranchRead sdkgo.BranchID = "read"
const GetObjectTextBranchNotFound sdkgo.BranchID = "notFound"
const GetObjectTextBranchUnsupportedContent sdkgo.BranchID = "unsupportedContent"
const GetObjectTextBranchTooLarge sdkgo.BranchID = "tooLarge"
const GetObjectTextBranchProviderRejected sdkgo.BranchID = "providerRejected"
const GetObjectTextBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const GetObjectTextBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var GetObjectTextDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getObjectText"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetObjectTextBranchRead, Description: "The object's complete text was read within maxTextBytes."},
		{ID: GetObjectTextBranchNotFound, Description: "The object does not exist.", Optional: true},
		{ID: GetObjectTextBranchUnsupportedContent, Description: "The object's content type is not text, its content is encoded such as gzip, or its bytes are not valid UTF-8 text.", Optional: true},
		{ID: GetObjectTextBranchTooLarge, Description: "The object is larger than maxTextBytes.", Optional: true},
		{ID: GetObjectTextBranchProviderRejected, Description: "The store conclusively rejected the read, such as a missing bucket, a wrong Region, invalid credentials, or missing s3:GetObject permission.", Optional: true},
		{ID: GetObjectTextBranchInvalidResponse, Description: "The store returned a response without a valid size or with content that contains the connection's credentials.", Optional: true},
		{ID: GetObjectTextBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type GetObjectTextResult = sdkgo.QueryResult[ObjectText]

type GetObjectTextStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                      `connector:"connectorId=amazon-s3"`
	operationID                    struct{}                                      `connector:"operationId=getObjectText"`
	StepType                       string                                        `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                         `connector:"annotations"`
	Connection                     Connection                                    `connector:"connection"`
	ConnectionName                 string                                        `connector:"connectionName"`
	MapToOperationInput            func(IN) GetObjectTextInput                   `connector:"mapToOperationInput"`
	Read                           sdkgo.Target[GetObjectTextResult]             `connector:"branch=read"`
	NotFound                       sdkgo.Target[GetObjectTextResult]             `connector:"branch=notFound,optional"`
	UnsupportedContent             sdkgo.Target[GetObjectTextResult]             `connector:"branch=unsupportedContent,optional"`
	TooLarge                       sdkgo.Target[GetObjectTextResult]             `connector:"branch=tooLarge,optional"`
	ProviderRejected               sdkgo.Target[GetObjectTextResult]             `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[GetObjectTextResult]             `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[GetObjectTextResult]             `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[ObjectText]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                              `connector:"stepOptionsOverride"`
}

func NewGetObjectTextStep[IN any](config GetObjectTextStepConfig[IN]) sdkgo.QueryStep[IN, GetObjectTextInput, ObjectText] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("amazon-s3 connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetObjectTextInput, ObjectText]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.GetObjectText(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[GetObjectTextResult] {
			branches := make([]sdkgo.BranchTarget[GetObjectTextResult], 0, 7)
			if config.Read.HasStep() {
				branches = append(branches, config.Read.BranchTarget(GetObjectTextBranchRead))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(GetObjectTextBranchNotFound))
			}
			if config.UnsupportedContent.HasStep() {
				branches = append(branches, config.UnsupportedContent.BranchTarget(GetObjectTextBranchUnsupportedContent))
			}
			if config.TooLarge.HasStep() {
				branches = append(branches, config.TooLarge.BranchTarget(GetObjectTextBranchTooLarge))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(GetObjectTextBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(GetObjectTextBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(GetObjectTextBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const PutObjectBranchStored sdkgo.BranchID = "stored"
const PutObjectBranchAlreadyExists sdkgo.BranchID = "alreadyExists"
const PutObjectBranchProviderRejected sdkgo.BranchID = "providerRejected"
const PutObjectBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var PutObjectDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "putObject"},
	Branches: []sdkgo.BranchDefinition{
		{ID: PutObjectBranchStored, Description: "The store holds the object this Step execution wrote."},
		{ID: PutObjectBranchAlreadyExists, Description: "Create-only mode found an object at the key that this Step execution did not write; nothing was written.", Optional: true},
		{ID: PutObjectBranchProviderRejected, Description: "The store conclusively rejected the write, such as a missing bucket, a wrong Region, invalid credentials, missing s3:PutObject permission, or a store that does not support create-only writes.", Optional: true},
		{ID: PutObjectBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type PutObjectResult = sdkgo.MutationResult[StoredObject]

type PutObjectStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                           `connector:"connectorId=amazon-s3"`
	operationID                       struct{}                                           `connector:"operationId=putObject"`
	StepType                          string                                             `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                              `connector:"annotations"`
	Connection                        Connection                                         `connector:"connection"`
	ConnectionName                    string                                             `connector:"connectionName"`
	MapToOperationInput               func(IN) PutObjectInput                            `connector:"mapToOperationInput"`
	Stored                            sdkgo.Target[PutObjectResult]                      `connector:"branch=stored"`
	AlreadyExists                     sdkgo.Target[PutObjectResult]                      `connector:"branch=alreadyExists,optional"`
	ProviderRejected                  sdkgo.Target[PutObjectResult]                      `connector:"branch=providerRejected,optional"`
	Defect                            sdkgo.Target[PutObjectResult]                      `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[StoredObject]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                   `connector:"stepOptionsOverride"`
}

func NewPutObjectStep[IN any](config PutObjectStepConfig[IN]) sdkgo.MutationStep[IN, PutObjectInput, StoredObject] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("amazon-s3 connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, PutObjectInput, StoredObject]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.PutObject(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[PutObjectResult] {
			branches := make([]sdkgo.BranchTarget[PutObjectResult], 0, 4)
			if config.Stored.HasStep() {
				branches = append(branches, config.Stored.BranchTarget(PutObjectBranchStored))
			}
			if config.AlreadyExists.HasStep() {
				branches = append(branches, config.AlreadyExists.BranchTarget(PutObjectBranchAlreadyExists))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(PutObjectBranchProviderRejected))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(PutObjectBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
