// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package mockfixturemock

import (
	"testing"

	"example.com/mockfixture"
	"github.com/superdurable/dex-connectors-library/sdkgo/connectormock"
)

func TestManifestMockOutputsDecodeStrictly(t *testing.T) {
	fixtures := []struct {
		name   string
		decode func() error
	}{
		{name: "getWidget/gear/1", decode: func() error {
			_, err := connectormock.DecodeOutput[mockfixture.Widget](`{"id":"w-1","name":"Gear","createdAt":"2026-01-02T03:04:05Z","tags":["metal","007"]}`)
			return err
		}},
		{name: "listWidgets/threePages/1", decode: func() error {
			_, err := connectormock.DecodeOutput[mockfixture.WidgetPage](`{"widgets":[{"id":"w-3","name":"Spring"},{"id":"w-1","name":"Gear"}],"nextPage":2}`)
			return err
		}},
		{name: "listWidgets/threePages/2", decode: func() error {
			_, err := connectormock.DecodeOutput[mockfixture.WidgetPage](`{"widgets":[{"id":"w-1","name":"Gear"},{"id":"w-9","name":"Archived","tags":["archived"]}],"nextPage":3}`)
			return err
		}},
		{name: "listWidgets/threePages/3", decode: func() error {
			_, err := connectormock.DecodeOutput[mockfixture.WidgetPage](`{"widgets":[],"nextPage":0}`)
			return err
		}},
		{name: "createWidget/createdGear/1", decode: func() error {
			_, err := connectormock.DecodeOutput[mockfixture.Widget](`{"id":"w-1","name":"Gear"}`)
			return err
		}},
	}
	for _, fixture := range fixtures {
		if err := fixture.decode(); err != nil {
			t.Errorf("manifest mock %s: %v", fixture.name, err)
		}
	}
}

func TestNewBindsEveryOperation(t *testing.T) {
	mock := New(t, "mock")
	if mock.GetWidget().Definition().Operation.OperationID != "getWidget" {
		t.Errorf("getWidget mock has another definition")
	}
	if mock.ListWidgets().Definition().Operation.OperationID != "listWidgets" {
		t.Errorf("listWidgets mock has another definition")
	}
	if mock.CreateWidget().Definition().Operation.OperationID != "createWidget" {
		t.Errorf("createWidget mock has another definition")
	}
}
