// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package slack

import (
	"encoding/json"
	"fmt"
	"net/url"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/localconfig"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "slack"

type Config struct {
	Endpoint             string `json:"endpoint,omitempty" yaml:"endpoint,omitempty"`
	MaxResponseBytes     int64  `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
	MaxMessageCharacters int64  `json:"maxMessageCharacters,omitempty" yaml:"maxMessageCharacters,omitempty"`
}

type Credentials struct {
	BotToken  sdkgo.SecretString
	UserToken sdkgo.SecretString
	AppToken  sdkgo.SecretString
}

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("slack connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("slack connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewLocalConnection loads startup configuration and reloads credentials before every provider call.
func NewLocalConnection(store *localconfig.Store, connectionName string, options ...Option) (Connection, error) {
	if store == nil {
		return Connection{}, fmt.Errorf("local connector configuration store is required")
	}
	reference := sdkgo.ConnectionRef{Provider: "slack", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("slack local connection: %w", err)
	}
	var config Config
	if err := store.DecodeConfiguration(ConnectorID, connectionName, &config); err != nil {
		return Connection{}, err
	}
	credentials := localconfig.NewCredentialProvider(store, ConnectorID, connectionName, decodeLocalCredentials)
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeLocalCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		BotToken  string `json:"bot_token"`
		UserToken string `json:"user_token"`
		AppToken  string `json:"app_token"`
	}
	if err := localconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		BotToken:  sdkgo.NewSecretString(fields.BotToken),
		UserToken: sdkgo.NewSecretString(fields.UserToken),
		AppToken:  sdkgo.NewSecretString(fields.AppToken),
	}
	return credentials, credentials.Validate()
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("slack connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("slack connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("slack connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("slack connector connections cannot be serialized")
}
func (Connection) String() string   { return "slack.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "slack.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		Endpoint:             "https://slack.com/api",
		MaxResponseBytes:     4194304,
		MaxMessageCharacters: 40000,
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.Endpoint == "" {
		config.Endpoint = defaults.Endpoint
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	if config.MaxMessageCharacters == 0 {
		config.MaxMessageCharacters = defaults.MaxMessageCharacters
	}
	return config
}

func (config Config) Validate() error {
	if config.Endpoint != "" {
		parsed, err := url.Parse(config.Endpoint)
		if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
			return fmt.Errorf("configuration endpoint must be an absolute URL")
		}
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	if config.MaxMessageCharacters < 0 {
		return fmt.Errorf("configuration maxMessageCharacters cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	if credentials.BotToken.Reveal() == "" {
		return fmt.Errorf("credential bot_token is required")
	}
	if credentials.UserToken.Reveal() == "" {
		return fmt.Errorf("credential user_token is required")
	}
	if credentials.AppToken.Reveal() == "" {
		return fmt.Errorf("credential app_token is required")
	}
	return nil
}

var ChannelThreadCreatedTriggerDefinition = sdkgo.TriggerDefinition{
	Trigger:     sdkgo.TriggerRef{ConnectorID: ConnectorID, TriggerName: "channelThreadCreated"},
	Description: "Receive a matching top-level channel message.",
}

type ChannelThreadCreatedTriggerBindingConfig struct {
	sdkgo.TriggerBindingFactoryConfigMarker `connector:"factory=triggerBinding"`
	connectorID                             struct{} `connector:"connectorId=slack"`
	triggerName                             struct{} `connector:"triggerName=channelThreadCreated"`
	ConnectionName                          string   `connector:"connectionName"`
	BindingName                             string   `connector:"bindingName"`
}

func DefineChannelThreadCreatedTriggerBinding(config ChannelThreadCreatedTriggerBindingConfig) sdkgo.TriggerBindingDefinition {
	return sdkgo.MustTriggerBindingDefinition(sdkgo.TriggerBindingDefinition{
		Definition: ChannelThreadCreatedTriggerDefinition, ConnectionName: config.ConnectionName, BindingName: config.BindingName,
	})
}

type ChannelThreadCreatedTriggerConfig struct {
	sdkgo.TriggerFactoryConfigMarker `connector:"factory=trigger"`
	connectorID                      struct{}                                 `connector:"connectorId=slack"`
	triggerName                      struct{}                                 `connector:"triggerName=channelThreadCreated"`
	Connection                       Connection                               `connector:"connection"`
	ConnectionName                   string                                   `connector:"connectionName"`
	BindingName                      string                                   `connector:"bindingName"`
	Configuration                    ChannelThreadCreatedTriggerConfiguration `connector:"triggerConfiguration"`
	Target                           sdkgo.TriggerTarget[MessageEvent]        `connector:"triggerTarget"`
}

func NewChannelThreadCreatedTrigger(config ChannelThreadCreatedTriggerConfig) sdkgo.TriggerRunner {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("slack connector trigger connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	binding := sdkgo.TriggerBindingRef{Connection: config.Connection.reference, Trigger: ChannelThreadCreatedTriggerDefinition.Trigger, Name: config.BindingName}
	return sdkgo.MustNewTrigger(sdkgo.TriggerConfig[MessageEvent]{
		Definition: ChannelThreadCreatedTriggerDefinition, Binding: binding,
		Source: config.Connection.client.channelThreadCreatedTriggerSource(config.Connection.reference, config.Configuration), Target: config.Target,
	})
}

func NewLocalChannelThreadCreatedTrigger(store *localconfig.Store, connectionName string, bindingName string, target sdkgo.TriggerTarget[MessageEvent], options ...Option) (sdkgo.TriggerRunner, error) {
	connection, err := NewLocalConnection(store, connectionName, options...)
	if err != nil {
		return nil, err
	}
	var configuration ChannelThreadCreatedTriggerConfiguration
	if err := store.DecodeTriggerConfiguration(ConnectorID, connectionName, "channelThreadCreated", bindingName, &configuration); err != nil {
		return nil, err
	}
	durableTarget, err := localconfig.NewDurableTriggerTarget(store, ConnectorID, connectionName, "channelThreadCreated", bindingName, target)
	if err != nil {
		return nil, err
	}
	return NewChannelThreadCreatedTrigger(ChannelThreadCreatedTriggerConfig{
		Connection: connection, ConnectionName: connectionName, BindingName: bindingName, Configuration: configuration, Target: durableTarget,
	}), nil
}

var ThreadReplyCreatedTriggerDefinition = sdkgo.TriggerDefinition{
	Trigger:     sdkgo.TriggerRef{ConnectorID: ConnectorID, TriggerName: "threadReplyCreated"},
	Description: "Receive a matching thread reply.",
}

type ThreadReplyCreatedTriggerBindingConfig struct {
	sdkgo.TriggerBindingFactoryConfigMarker `connector:"factory=triggerBinding"`
	connectorID                             struct{} `connector:"connectorId=slack"`
	triggerName                             struct{} `connector:"triggerName=threadReplyCreated"`
	ConnectionName                          string   `connector:"connectionName"`
	BindingName                             string   `connector:"bindingName"`
}

func DefineThreadReplyCreatedTriggerBinding(config ThreadReplyCreatedTriggerBindingConfig) sdkgo.TriggerBindingDefinition {
	return sdkgo.MustTriggerBindingDefinition(sdkgo.TriggerBindingDefinition{
		Definition: ThreadReplyCreatedTriggerDefinition, ConnectionName: config.ConnectionName, BindingName: config.BindingName,
	})
}

type ThreadReplyCreatedTriggerConfig struct {
	sdkgo.TriggerFactoryConfigMarker `connector:"factory=trigger"`
	connectorID                      struct{}                               `connector:"connectorId=slack"`
	triggerName                      struct{}                               `connector:"triggerName=threadReplyCreated"`
	Connection                       Connection                             `connector:"connection"`
	ConnectionName                   string                                 `connector:"connectionName"`
	BindingName                      string                                 `connector:"bindingName"`
	Configuration                    ThreadReplyCreatedTriggerConfiguration `connector:"triggerConfiguration"`
	Target                           sdkgo.TriggerTarget[MessageEvent]      `connector:"triggerTarget"`
}

func NewThreadReplyCreatedTrigger(config ThreadReplyCreatedTriggerConfig) sdkgo.TriggerRunner {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("slack connector trigger connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	binding := sdkgo.TriggerBindingRef{Connection: config.Connection.reference, Trigger: ThreadReplyCreatedTriggerDefinition.Trigger, Name: config.BindingName}
	return sdkgo.MustNewTrigger(sdkgo.TriggerConfig[MessageEvent]{
		Definition: ThreadReplyCreatedTriggerDefinition, Binding: binding,
		Source: config.Connection.client.threadReplyCreatedTriggerSource(config.Connection.reference, config.Configuration), Target: config.Target,
	})
}

func NewLocalThreadReplyCreatedTrigger(store *localconfig.Store, connectionName string, bindingName string, target sdkgo.TriggerTarget[MessageEvent], options ...Option) (sdkgo.TriggerRunner, error) {
	connection, err := NewLocalConnection(store, connectionName, options...)
	if err != nil {
		return nil, err
	}
	var configuration ThreadReplyCreatedTriggerConfiguration
	if err := store.DecodeTriggerConfiguration(ConnectorID, connectionName, "threadReplyCreated", bindingName, &configuration); err != nil {
		return nil, err
	}
	durableTarget, err := localconfig.NewDurableTriggerTarget(store, ConnectorID, connectionName, "threadReplyCreated", bindingName, target)
	if err != nil {
		return nil, err
	}
	return NewThreadReplyCreatedTrigger(ThreadReplyCreatedTriggerConfig{
		Connection: connection, ConnectionName: connectionName, BindingName: bindingName, Configuration: configuration, Target: durableTarget,
	}), nil
}

const ListThreadMessagesBranchRead sdkgo.BranchID = "read"
const ListThreadMessagesBranchRejected sdkgo.BranchID = "rejected"
const ListThreadMessagesBranchDefect sdkgo.BranchID = "defect"

var ListThreadMessagesDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "listThreadMessages"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ListThreadMessagesBranchRead, Description: "The thread page was read."},
		{ID: ListThreadMessagesBranchRejected, Description: "Slack rejected the query."},
		{ID: ListThreadMessagesBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch: ListThreadMessagesBranchDefect,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementOptional,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type ListThreadMessagesResult = sdkgo.QueryResult[ListThreadMessagesOutput]

type ListThreadMessagesStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                                    `connector:"connectorId=slack"`
	operationID                    struct{}                                                    `connector:"operationId=listThreadMessages"`
	StepType                       string                                                      `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                       `connector:"annotations"`
	Connection                     Connection                                                  `connector:"connection"`
	ConnectionName                 string                                                      `connector:"connectionName"`
	BuildOperationInput            func(IN) (ListThreadMessagesInput, error)                   `connector:"buildOperationInput"`
	Read                           sdkgo.Target[ListThreadMessagesResult]                      `connector:"branch=read"`
	Rejected                       sdkgo.Target[ListThreadMessagesResult]                      `connector:"branch=rejected"`
	Defect                         sdkgo.Target[ListThreadMessagesResult]                      `connector:"branch=defect"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[ListThreadMessagesOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                            `connector:"stepOptionsOverride"`
}

func NewListThreadMessagesStep[IN any](config ListThreadMessagesStepConfig[IN]) sdkgo.QueryStep[IN, ListThreadMessagesInput, ListThreadMessagesOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("slack connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, ListThreadMessagesInput, ListThreadMessagesOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.ListThreadMessages(), Connection: config.Connection.reference,
		BuildOperationInput: config.BuildOperationInput,
		Branches: []sdkgo.BranchTarget[ListThreadMessagesResult]{
			config.Read.BranchTarget(ListThreadMessagesBranchRead),
			config.Rejected.BranchTarget(ListThreadMessagesBranchRejected),
			config.Defect.BranchTarget(ListThreadMessagesBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const GetThreadReplyBranchFound sdkgo.BranchID = "found"
const GetThreadReplyBranchNotFound sdkgo.BranchID = "notFound"
const GetThreadReplyBranchRejected sdkgo.BranchID = "rejected"
const GetThreadReplyBranchDefect sdkgo.BranchID = "defect"

var GetThreadReplyDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getThreadReply"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetThreadReplyBranchFound, Description: "The reply was found."},
		{ID: GetThreadReplyBranchNotFound, Description: "The reply does not exist."},
		{ID: GetThreadReplyBranchRejected, Description: "Slack rejected the query."},
		{ID: GetThreadReplyBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch: GetThreadReplyBranchDefect,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementOptional,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type GetThreadReplyResult = sdkgo.QueryResult[GetThreadReplyOutput]

type GetThreadReplyStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                                `connector:"connectorId=slack"`
	operationID                    struct{}                                                `connector:"operationId=getThreadReply"`
	StepType                       string                                                  `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                   `connector:"annotations"`
	Connection                     Connection                                              `connector:"connection"`
	ConnectionName                 string                                                  `connector:"connectionName"`
	BuildOperationInput            func(IN) (GetThreadReplyInput, error)                   `connector:"buildOperationInput"`
	Found                          sdkgo.Target[GetThreadReplyResult]                      `connector:"branch=found"`
	NotFound                       sdkgo.Target[GetThreadReplyResult]                      `connector:"branch=notFound"`
	Rejected                       sdkgo.Target[GetThreadReplyResult]                      `connector:"branch=rejected"`
	Defect                         sdkgo.Target[GetThreadReplyResult]                      `connector:"branch=defect"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[GetThreadReplyOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewGetThreadReplyStep[IN any](config GetThreadReplyStepConfig[IN]) sdkgo.QueryStep[IN, GetThreadReplyInput, GetThreadReplyOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("slack connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetThreadReplyInput, GetThreadReplyOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.GetThreadReply(), Connection: config.Connection.reference,
		BuildOperationInput: config.BuildOperationInput,
		Branches: []sdkgo.BranchTarget[GetThreadReplyResult]{
			config.Found.BranchTarget(GetThreadReplyBranchFound),
			config.NotFound.BranchTarget(GetThreadReplyBranchNotFound),
			config.Rejected.BranchTarget(GetThreadReplyBranchRejected),
			config.Defect.BranchTarget(GetThreadReplyBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const PostChannelMessageBranchSent sdkgo.BranchID = "sent"
const PostChannelMessageBranchRejected sdkgo.BranchID = "rejected"
const PostChannelMessageBranchUncertain sdkgo.BranchID = "uncertain"
const PostChannelMessageBranchDefect sdkgo.BranchID = "defect"

var PostChannelMessageDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "postChannelMessage"},
	Branches: []sdkgo.BranchDefinition{
		{ID: PostChannelMessageBranchSent, Description: "Slack accepted the message."},
		{ID: PostChannelMessageBranchRejected, Description: "Slack conclusively rejected the message."},
		{ID: PostChannelMessageBranchUncertain, Description: "The dispatched message outcome cannot be confirmed."},
		{ID: PostChannelMessageBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch:    PostChannelMessageBranchDefect,
	UncertainBranch: PostChannelMessageBranchUncertain,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementRequired,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type PostChannelMessageResult = sdkgo.MutationResult[PostMessageOutput]

type PostChannelMessageStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                                `connector:"connectorId=slack"`
	operationID                       struct{}                                                `connector:"operationId=postChannelMessage"`
	StepType                          string                                                  `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                   `connector:"annotations"`
	Connection                        Connection                                              `connector:"connection"`
	ConnectionName                    string                                                  `connector:"connectionName"`
	BuildOperationInput               func(IN) (PostChannelMessageInput, error)               `connector:"buildOperationInput"`
	Sent                              sdkgo.Target[PostChannelMessageResult]                  `connector:"branch=sent"`
	Rejected                          sdkgo.Target[PostChannelMessageResult]                  `connector:"branch=rejected"`
	Uncertain                         sdkgo.Target[PostChannelMessageResult]                  `connector:"branch=uncertain"`
	Defect                            sdkgo.Target[PostChannelMessageResult]                  `connector:"branch=defect"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[PostMessageOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewPostChannelMessageStep[IN any](config PostChannelMessageStepConfig[IN]) sdkgo.MutationStep[IN, PostChannelMessageInput, PostMessageOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("slack connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, PostChannelMessageInput, PostMessageOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.PostChannelMessage(), Connection: config.Connection.reference,
		BuildOperationInput: config.BuildOperationInput,
		Branches: []sdkgo.BranchTarget[PostChannelMessageResult]{
			config.Sent.BranchTarget(PostChannelMessageBranchSent),
			config.Rejected.BranchTarget(PostChannelMessageBranchRejected),
			config.Uncertain.BranchTarget(PostChannelMessageBranchUncertain),
			config.Defect.BranchTarget(PostChannelMessageBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const PostThreadReplyBranchSent sdkgo.BranchID = "sent"
const PostThreadReplyBranchRejected sdkgo.BranchID = "rejected"
const PostThreadReplyBranchUncertain sdkgo.BranchID = "uncertain"
const PostThreadReplyBranchDefect sdkgo.BranchID = "defect"

var PostThreadReplyDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "postThreadReply"},
	Branches: []sdkgo.BranchDefinition{
		{ID: PostThreadReplyBranchSent, Description: "Slack accepted the message."},
		{ID: PostThreadReplyBranchRejected, Description: "Slack conclusively rejected the message."},
		{ID: PostThreadReplyBranchUncertain, Description: "The dispatched message outcome cannot be confirmed."},
		{ID: PostThreadReplyBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch:    PostThreadReplyBranchDefect,
	UncertainBranch: PostThreadReplyBranchUncertain,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementRequired,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type PostThreadReplyResult = sdkgo.MutationResult[PostMessageOutput]

type PostThreadReplyStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                                `connector:"connectorId=slack"`
	operationID                       struct{}                                                `connector:"operationId=postThreadReply"`
	StepType                          string                                                  `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                   `connector:"annotations"`
	Connection                        Connection                                              `connector:"connection"`
	ConnectionName                    string                                                  `connector:"connectionName"`
	BuildOperationInput               func(IN) (PostThreadReplyInput, error)                  `connector:"buildOperationInput"`
	Sent                              sdkgo.Target[PostThreadReplyResult]                     `connector:"branch=sent"`
	Rejected                          sdkgo.Target[PostThreadReplyResult]                     `connector:"branch=rejected"`
	Uncertain                         sdkgo.Target[PostThreadReplyResult]                     `connector:"branch=uncertain"`
	Defect                            sdkgo.Target[PostThreadReplyResult]                     `connector:"branch=defect"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[PostMessageOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewPostThreadReplyStep[IN any](config PostThreadReplyStepConfig[IN]) sdkgo.MutationStep[IN, PostThreadReplyInput, PostMessageOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("slack connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, PostThreadReplyInput, PostMessageOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.PostThreadReply(), Connection: config.Connection.reference,
		BuildOperationInput: config.BuildOperationInput,
		Branches: []sdkgo.BranchTarget[PostThreadReplyResult]{
			config.Sent.BranchTarget(PostThreadReplyBranchSent),
			config.Rejected.BranchTarget(PostThreadReplyBranchRejected),
			config.Uncertain.BranchTarget(PostThreadReplyBranchUncertain),
			config.Defect.BranchTarget(PostThreadReplyBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
