// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package email

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig/provider"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "email"

type IMAPSecurity string

const (
	IMAPSecurityImplicitTLS IMAPSecurity = "implicitTLS"
	IMAPSecurityStartTLS    IMAPSecurity = "startTLS"
)

type SMTPSecurity string

const (
	SMTPSecurityImplicitTLS SMTPSecurity = "implicitTLS"
	SMTPSecurityStartTLS    SMTPSecurity = "startTLS"
)

type Config struct {
	IMAPHost     string       `json:"imapHost,omitempty" yaml:"imapHost,omitempty"`
	IMAPPort     int64        `json:"imapPort,omitempty" yaml:"imapPort,omitempty"`
	IMAPSecurity IMAPSecurity `json:"imapSecurity,omitempty" yaml:"imapSecurity,omitempty"`
	SMTPHost     string       `json:"smtpHost,omitempty" yaml:"smtpHost,omitempty"`
	SMTPPort     int64        `json:"smtpPort,omitempty" yaml:"smtpPort,omitempty"`
	SMTPSecurity SMTPSecurity `json:"smtpSecurity,omitempty" yaml:"smtpSecurity,omitempty"`
	FromAddress  string       `json:"fromAddress,omitempty" yaml:"fromAddress,omitempty"`
	FromName     string       `json:"fromName,omitempty" yaml:"fromName,omitempty"`
}

type Credentials struct {
	Username     string
	Password     sdkgo.SecretString
	SMTPUsername string
	SMTPPassword sdkgo.SecretString
}

// CredentialSource is the credential provider New requires: this connector never refreshes its credentials.
type CredentialSource = sdkgo.CredentialProvider[Credentials]

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

// NewConnection wraps a client built with New, such as a test client with a static credential provider.
// Applications open declared connections with NewProjectConnection instead.
func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("email connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("email connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewProjectConnection opens the connection that dex-app.yaml declares as connectionName from the
// loaded project configuration. It reads ordinary settings now and resolves credentials during each call.
func NewProjectConnection(project *projectconfig.LoadedProject, connectionName string, options ...Option) (Connection, error) {
	if project == nil {
		return Connection{}, fmt.Errorf("email connection requires the loaded project configuration")
	}
	reference := sdkgo.ConnectionRef{Provider: "email", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("email connection: %w", err)
	}
	key := projectconfig.ConnectionKey{ConnectorID: ConnectorID, ConnectionName: connectionName}
	var config Config
	if err := project.Configuration.DecodeConnectionConfiguration(key, &config); err != nil {
		return Connection{}, fmt.Errorf("email connection %q settings: %w", connectionName, err)
	}
	credentials, err := provider.NewCredentialProvider(project.Connections, key, decodeCredentials)
	if err != nil {
		return Connection{}, err
	}
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		Username     string `json:"username"`
		Password     string `json:"password"`
		SMTPUsername string `json:"smtp_username"`
		SMTPPassword string `json:"smtp_password"`
	}
	if err := projectconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		Username:     fields.Username,
		Password:     sdkgo.NewSecretString(fields.Password),
		SMTPUsername: fields.SMTPUsername,
		SMTPPassword: sdkgo.NewSecretString(fields.SMTPPassword),
	}
	return credentials, credentials.Validate()
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("email connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("email connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("email connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("email connector connections cannot be serialized")
}
func (Connection) String() string   { return "email.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "email.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		IMAPPort:     993,
		IMAPSecurity: IMAPSecurity("implicitTLS"),
		SMTPPort:     465,
		SMTPSecurity: SMTPSecurity("implicitTLS"),
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.IMAPPort == 0 {
		config.IMAPPort = defaults.IMAPPort
	}
	if config.IMAPSecurity == "" {
		config.IMAPSecurity = defaults.IMAPSecurity
	}
	if config.SMTPPort == 0 {
		config.SMTPPort = defaults.SMTPPort
	}
	if config.SMTPSecurity == "" {
		config.SMTPSecurity = defaults.SMTPSecurity
	}
	return config
}

func (config Config) Validate() error {
	if config.IMAPHost == "" {
		return fmt.Errorf("configuration imapHost is required")
	}
	if config.IMAPPort < 0 {
		return fmt.Errorf("configuration imapPort cannot be negative")
	}
	switch config.IMAPSecurity {
	case "", "implicitTLS", "startTLS":
	default:
		return fmt.Errorf("configuration imapSecurity is invalid")
	}
	if config.SMTPHost == "" {
		return fmt.Errorf("configuration smtpHost is required")
	}
	if config.SMTPPort < 0 {
		return fmt.Errorf("configuration smtpPort cannot be negative")
	}
	switch config.SMTPSecurity {
	case "", "implicitTLS", "startTLS":
	default:
		return fmt.Errorf("configuration smtpSecurity is invalid")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	if credentials.Username == "" {
		return fmt.Errorf("credential username is required")
	}
	if credentials.Password.Reveal() == "" {
		return fmt.Errorf("credential password is required")
	}
	return nil
}

const SearchMessagesBranchSearched sdkgo.BranchID = "searched"
const SearchMessagesBranchProviderRejected sdkgo.BranchID = "providerRejected"
const SearchMessagesBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const SearchMessagesBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var SearchMessagesDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "searchMessages"},
	Branches: []sdkgo.BranchDefinition{
		{ID: SearchMessagesBranchSearched, Description: "The search ran; the Result holds up to limit matching summaries, newest first, and may be empty."},
		{ID: SearchMessagesBranchProviderRejected, Description: "The IMAP server conclusively refused the login, TLS, mailbox, or search, such as a wrong app password, a certificate that fails verification, or a mailbox that does not exist.", Optional: true},
		{ID: SearchMessagesBranchInvalidResponse, Description: "The IMAP server returned a response the connector cannot parse.", Optional: true},
		{ID: SearchMessagesBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type SearchMessagesResult = sdkgo.QueryResult[SearchMessagesOutput]

type SearchMessagesStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                                `connector:"connectorId=email"`
	operationID                    struct{}                                                `connector:"operationId=searchMessages"`
	StepType                       string                                                  `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                   `connector:"annotations"`
	Connection                     Connection                                              `connector:"connection"`
	ConnectionName                 string                                                  `connector:"connectionName"`
	MapToOperationInput            func(IN) SearchMessagesInput                            `connector:"mapToOperationInput"`
	Searched                       sdkgo.Target[SearchMessagesResult]                      `connector:"branch=searched"`
	ProviderRejected               sdkgo.Target[SearchMessagesResult]                      `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[SearchMessagesResult]                      `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[SearchMessagesResult]                      `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[SearchMessagesOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewSearchMessagesStep[IN any](config SearchMessagesStepConfig[IN]) sdkgo.QueryStep[IN, SearchMessagesInput, SearchMessagesOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("email connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, SearchMessagesInput, SearchMessagesOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.SearchMessages(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[SearchMessagesResult] {
			branches := make([]sdkgo.BranchTarget[SearchMessagesResult], 0, 4)
			if config.Searched.HasStep() {
				branches = append(branches, config.Searched.BranchTarget(SearchMessagesBranchSearched))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(SearchMessagesBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(SearchMessagesBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(SearchMessagesBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const GetMessageBranchFound sdkgo.BranchID = "found"
const GetMessageBranchNotFound sdkgo.BranchID = "notFound"
const GetMessageBranchProviderRejected sdkgo.BranchID = "providerRejected"
const GetMessageBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const GetMessageBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var GetMessageDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getMessage"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetMessageBranchFound, Description: "The message was read."},
		{ID: GetMessageBranchNotFound, Description: "The mailbox does not exist, its UIDVALIDITY changed, or no message has the UID.", Optional: true},
		{ID: GetMessageBranchProviderRejected, Description: "The IMAP server conclusively refused the login, TLS, or read.", Optional: true},
		{ID: GetMessageBranchInvalidResponse, Description: "The IMAP server returned a response or message the connector cannot parse.", Optional: true},
		{ID: GetMessageBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type GetMessageResult = sdkgo.QueryResult[Message]

type GetMessageStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                   `connector:"connectorId=email"`
	operationID                    struct{}                                   `connector:"operationId=getMessage"`
	StepType                       string                                     `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                      `connector:"annotations"`
	Connection                     Connection                                 `connector:"connection"`
	ConnectionName                 string                                     `connector:"connectionName"`
	MapToOperationInput            func(IN) GetMessageInput                   `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[GetMessageResult]             `connector:"branch=found"`
	NotFound                       sdkgo.Target[GetMessageResult]             `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[GetMessageResult]             `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[GetMessageResult]             `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[GetMessageResult]             `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[Message]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                           `connector:"stepOptionsOverride"`
}

func NewGetMessageStep[IN any](config GetMessageStepConfig[IN]) sdkgo.QueryStep[IN, GetMessageInput, Message] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("email connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetMessageInput, Message]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.GetMessage(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[GetMessageResult] {
			branches := make([]sdkgo.BranchTarget[GetMessageResult], 0, 5)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(GetMessageBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(GetMessageBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(GetMessageBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(GetMessageBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(GetMessageBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const SendMessageBranchSent sdkgo.BranchID = "sent"
const SendMessageBranchProviderRejected sdkgo.BranchID = "providerRejected"
const SendMessageBranchUncertain sdkgo.BranchID = sdkgo.UncertainBranchID
const SendMessageBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var SendMessageDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "sendMessage"},
	Branches: []sdkgo.BranchDefinition{
		{ID: SendMessageBranchSent, Description: "The SMTP server accepted the message for delivery."},
		{ID: SendMessageBranchProviderRejected, Description: "The SMTP server conclusively refused the login, TLS, sender, a recipient, or the message, so nothing was sent.", Optional: true},
		{ID: SendMessageBranchUncertain, Description: "The message was submitted but the server's answer was lost, so it may have been sent; the connector never submits it again.", Optional: true},
		{ID: SendMessageBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(150000000000), HeartbeatTimeout: time.Duration(150000000000),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(2000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 5, TotalDuration: time.Duration(600000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
}

type SendMessageResult = sdkgo.MutationResult[SentMessage]

type SendMessageStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                          `connector:"connectorId=email"`
	operationID                       struct{}                                          `connector:"operationId=sendMessage"`
	StepType                          string                                            `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                             `connector:"annotations"`
	Connection                        Connection                                        `connector:"connection"`
	ConnectionName                    string                                            `connector:"connectionName"`
	MapToOperationInput               func(IN) SendMessageInput                         `connector:"mapToOperationInput"`
	Sent                              sdkgo.Target[SendMessageResult]                   `connector:"branch=sent"`
	ProviderRejected                  sdkgo.Target[SendMessageResult]                   `connector:"branch=providerRejected,optional"`
	Uncertain                         sdkgo.Target[SendMessageResult]                   `connector:"branch=uncertain,optional"`
	Defect                            sdkgo.Target[SendMessageResult]                   `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[SentMessage]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                  `connector:"stepOptionsOverride"`
}

func NewSendMessageStep[IN any](config SendMessageStepConfig[IN]) sdkgo.MutationStep[IN, SendMessageInput, SentMessage] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("email connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, SendMessageInput, SentMessage]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.SendMessage(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[SendMessageResult] {
			branches := make([]sdkgo.BranchTarget[SendMessageResult], 0, 4)
			if config.Sent.HasStep() {
				branches = append(branches, config.Sent.BranchTarget(SendMessageBranchSent))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(SendMessageBranchProviderRejected))
			}
			if config.Uncertain.HasStep() {
				branches = append(branches, config.Uncertain.BranchTarget(SendMessageBranchUncertain))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(SendMessageBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const ReplyToMessageBranchSent sdkgo.BranchID = "sent"
const ReplyToMessageBranchNotFound sdkgo.BranchID = "notFound"
const ReplyToMessageBranchProviderRejected sdkgo.BranchID = "providerRejected"
const ReplyToMessageBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const ReplyToMessageBranchUncertain sdkgo.BranchID = sdkgo.UncertainBranchID
const ReplyToMessageBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var ReplyToMessageDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "replyToMessage"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ReplyToMessageBranchSent, Description: "The SMTP server accepted the reply for delivery."},
		{ID: ReplyToMessageBranchNotFound, Description: "The source mailbox does not exist, its UIDVALIDITY changed, or no message has the UID, so nothing was sent.", Optional: true},
		{ID: ReplyToMessageBranchProviderRejected, Description: "The IMAP or SMTP server conclusively refused the login, TLS, read, sender, a recipient, or the reply, so nothing was sent.", Optional: true},
		{ID: ReplyToMessageBranchInvalidResponse, Description: "The source message has no usable reply address or could not be parsed, so nothing was sent.", Optional: true},
		{ID: ReplyToMessageBranchUncertain, Description: "The reply was submitted but the server's answer was lost, so it may have been sent; the connector never submits it again.", Optional: true},
		{ID: ReplyToMessageBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(150000000000), HeartbeatTimeout: time.Duration(150000000000),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(2000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 5, TotalDuration: time.Duration(600000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
}

type ReplyToMessageResult = sdkgo.MutationResult[SentMessage]

type ReplyToMessageStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                          `connector:"connectorId=email"`
	operationID                       struct{}                                          `connector:"operationId=replyToMessage"`
	StepType                          string                                            `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                             `connector:"annotations"`
	Connection                        Connection                                        `connector:"connection"`
	ConnectionName                    string                                            `connector:"connectionName"`
	MapToOperationInput               func(IN) ReplyToMessageInput                      `connector:"mapToOperationInput"`
	Sent                              sdkgo.Target[ReplyToMessageResult]                `connector:"branch=sent"`
	NotFound                          sdkgo.Target[ReplyToMessageResult]                `connector:"branch=notFound,optional"`
	ProviderRejected                  sdkgo.Target[ReplyToMessageResult]                `connector:"branch=providerRejected,optional"`
	InvalidResponse                   sdkgo.Target[ReplyToMessageResult]                `connector:"branch=invalidResponse,optional"`
	Uncertain                         sdkgo.Target[ReplyToMessageResult]                `connector:"branch=uncertain,optional"`
	Defect                            sdkgo.Target[ReplyToMessageResult]                `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[SentMessage]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                  `connector:"stepOptionsOverride"`
}

func NewReplyToMessageStep[IN any](config ReplyToMessageStepConfig[IN]) sdkgo.MutationStep[IN, ReplyToMessageInput, SentMessage] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("email connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, ReplyToMessageInput, SentMessage]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.ReplyToMessage(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[ReplyToMessageResult] {
			branches := make([]sdkgo.BranchTarget[ReplyToMessageResult], 0, 6)
			if config.Sent.HasStep() {
				branches = append(branches, config.Sent.BranchTarget(ReplyToMessageBranchSent))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(ReplyToMessageBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(ReplyToMessageBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(ReplyToMessageBranchInvalidResponse))
			}
			if config.Uncertain.HasStep() {
				branches = append(branches, config.Uncertain.BranchTarget(ReplyToMessageBranchUncertain))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(ReplyToMessageBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const MoveMessageBranchMoved sdkgo.BranchID = "moved"
const MoveMessageBranchNotFound sdkgo.BranchID = "notFound"
const MoveMessageBranchProviderRejected sdkgo.BranchID = "providerRejected"
const MoveMessageBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var MoveMessageDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "moveMessage"},
	Branches: []sdkgo.BranchDefinition{
		{ID: MoveMessageBranchMoved, Description: "The message is in the destination mailbox, moved now or by an earlier attempt."},
		{ID: MoveMessageBranchNotFound, Description: "The source mailbox does not exist, its UIDVALIDITY changed, or no message has the UID and none with the expected Message-ID is in the destination.", Optional: true},
		{ID: MoveMessageBranchProviderRejected, Description: "The IMAP server conclusively refused the login, TLS, or move, such as a destination mailbox that does not exist or a server without MOVE or UIDPLUS.", Optional: true},
		{ID: MoveMessageBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type MoveMessageResult = sdkgo.MutationResult[MovedMessage]

type MoveMessageStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                           `connector:"connectorId=email"`
	operationID                       struct{}                                           `connector:"operationId=moveMessage"`
	StepType                          string                                             `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                              `connector:"annotations"`
	Connection                        Connection                                         `connector:"connection"`
	ConnectionName                    string                                             `connector:"connectionName"`
	MapToOperationInput               func(IN) MoveMessageInput                          `connector:"mapToOperationInput"`
	Moved                             sdkgo.Target[MoveMessageResult]                    `connector:"branch=moved"`
	NotFound                          sdkgo.Target[MoveMessageResult]                    `connector:"branch=notFound,optional"`
	ProviderRejected                  sdkgo.Target[MoveMessageResult]                    `connector:"branch=providerRejected,optional"`
	Defect                            sdkgo.Target[MoveMessageResult]                    `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[MovedMessage]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                   `connector:"stepOptionsOverride"`
}

func NewMoveMessageStep[IN any](config MoveMessageStepConfig[IN]) sdkgo.MutationStep[IN, MoveMessageInput, MovedMessage] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("email connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, MoveMessageInput, MovedMessage]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.MoveMessage(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[MoveMessageResult] {
			branches := make([]sdkgo.BranchTarget[MoveMessageResult], 0, 4)
			if config.Moved.HasStep() {
				branches = append(branches, config.Moved.BranchTarget(MoveMessageBranchMoved))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(MoveMessageBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(MoveMessageBranchProviderRejected))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(MoveMessageBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const SetFlagsBranchUpdated sdkgo.BranchID = "updated"
const SetFlagsBranchNotFound sdkgo.BranchID = "notFound"
const SetFlagsBranchProviderRejected sdkgo.BranchID = "providerRejected"
const SetFlagsBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var SetFlagsDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "setFlags"},
	Branches: []sdkgo.BranchDefinition{
		{ID: SetFlagsBranchUpdated, Description: "The message holds the requested flags, set now or by an earlier attempt."},
		{ID: SetFlagsBranchNotFound, Description: "The mailbox does not exist, its UIDVALIDITY changed, or no message has the UID.", Optional: true},
		{ID: SetFlagsBranchProviderRejected, Description: "The IMAP server conclusively refused the login, TLS, or flag change, such as a read-only mailbox.", Optional: true},
		{ID: SetFlagsBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type SetFlagsResult = sdkgo.MutationResult[MessageFlags]

type SetFlagsStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                           `connector:"connectorId=email"`
	operationID                       struct{}                                           `connector:"operationId=setFlags"`
	StepType                          string                                             `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                              `connector:"annotations"`
	Connection                        Connection                                         `connector:"connection"`
	ConnectionName                    string                                             `connector:"connectionName"`
	MapToOperationInput               func(IN) SetFlagsInput                             `connector:"mapToOperationInput"`
	Updated                           sdkgo.Target[SetFlagsResult]                       `connector:"branch=updated"`
	NotFound                          sdkgo.Target[SetFlagsResult]                       `connector:"branch=notFound,optional"`
	ProviderRejected                  sdkgo.Target[SetFlagsResult]                       `connector:"branch=providerRejected,optional"`
	Defect                            sdkgo.Target[SetFlagsResult]                       `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[MessageFlags]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                   `connector:"stepOptionsOverride"`
}

func NewSetFlagsStep[IN any](config SetFlagsStepConfig[IN]) sdkgo.MutationStep[IN, SetFlagsInput, MessageFlags] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("email connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, SetFlagsInput, MessageFlags]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.SetFlags(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[SetFlagsResult] {
			branches := make([]sdkgo.BranchTarget[SetFlagsResult], 0, 4)
			if config.Updated.HasStep() {
				branches = append(branches, config.Updated.BranchTarget(SetFlagsBranchUpdated))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(SetFlagsBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(SetFlagsBranchProviderRejected))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(SetFlagsBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
