// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

// Package githubmock scripts the github connector's operations in application tests. New returns a
// Connection whose operations answer from connectormock scripts, with each query's manifest default installed.
package githubmock

import (
	"testing"
	"time"

	"github.com/superdurable/dex-connectors-library/connectors/github"
	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/connectormock"
)

// Mock is a scripted github connection. Script each operation through its accessor.
type Mock struct {
	connection              github.Connection
	getAuthenticatedProfile *connectormock.Query[github.GetAuthenticatedProfileInput, github.AuthenticatedProfile]
	listPublicRepositories  *connectormock.Query[github.ListPublicRepositoriesInput, github.PublicRepositories]
	listMergedPullRequests  *connectormock.Query[github.ListMergedPullRequestsInput, github.MergedPullRequestPage]
	listPullRequestFiles    *connectormock.Query[github.ListPullRequestFilesInput, github.PullRequestFilePage]
	listReleases            *connectormock.Query[github.ListReleasesInput, github.ReleasePage]
	listCommits             *connectormock.Query[github.ListCommitsInput, github.CommitPage]
}

// New returns a mock connection named connectionName. Unscripted calls fail t, except a query's call that its
// manifest default answers.
func New(t testing.TB, connectionName string) *Mock {
	t.Helper()
	mock := &Mock{
		getAuthenticatedProfile: connectormock.NewQuery[github.GetAuthenticatedProfileInput, github.AuthenticatedProfile](t, github.GetAuthenticatedProfileDefinition),
		listPublicRepositories:  connectormock.NewQuery[github.ListPublicRepositoriesInput, github.PublicRepositories](t, github.ListPublicRepositoriesDefinition),
		listMergedPullRequests:  connectormock.NewQuery[github.ListMergedPullRequestsInput, github.MergedPullRequestPage](t, github.ListMergedPullRequestsDefinition),
		listPullRequestFiles:    connectormock.NewQuery[github.ListPullRequestFilesInput, github.PullRequestFilePage](t, github.ListPullRequestFilesDefinition),
		listReleases:            connectormock.NewQuery[github.ListReleasesInput, github.ReleasePage](t, github.ListReleasesDefinition),
		listCommits:             connectormock.NewQuery[github.ListCommitsInput, github.CommitPage](t, github.ListCommitsDefinition),
	}
	mock.getAuthenticatedProfile.Default(GetAuthenticatedProfileDefault())
	mock.listPublicRepositories.Default(ListPublicRepositoriesDefault())
	mock.listMergedPullRequests.Default(ListMergedPullRequestsDefault())
	mock.listPullRequestFiles.Default(ListPullRequestFilesDefault())
	mock.listReleases.Default(ListReleasesDefault())
	mock.listCommits.Default(ListCommitsDefault())
	connection, err := github.NewConnectionWithOperations(mockOperations{mock: mock}, sdkgo.ConnectionRef{Provider: "github", Name: connectionName})
	if err != nil {
		t.Fatalf("github mock connection: %v", err)
	}
	mock.connection = connection
	return mock
}

// Connection returns the typed connection to pass to the connector's Step factories.
func (mock *Mock) Connection() github.Connection { return mock.connection }

// GetAuthenticatedProfile returns the getAuthenticatedProfile script.
func (mock *Mock) GetAuthenticatedProfile() *connectormock.Query[github.GetAuthenticatedProfileInput, github.AuthenticatedProfile] {
	return mock.getAuthenticatedProfile
}

// ListPublicRepositories returns the listPublicRepositories script.
func (mock *Mock) ListPublicRepositories() *connectormock.Query[github.ListPublicRepositoriesInput, github.PublicRepositories] {
	return mock.listPublicRepositories
}

// ListMergedPullRequests returns the listMergedPullRequests script.
func (mock *Mock) ListMergedPullRequests() *connectormock.Query[github.ListMergedPullRequestsInput, github.MergedPullRequestPage] {
	return mock.listMergedPullRequests
}

// ListPullRequestFiles returns the listPullRequestFiles script.
func (mock *Mock) ListPullRequestFiles() *connectormock.Query[github.ListPullRequestFilesInput, github.PullRequestFilePage] {
	return mock.listPullRequestFiles
}

// ListReleases returns the listReleases script.
func (mock *Mock) ListReleases() *connectormock.Query[github.ListReleasesInput, github.ReleasePage] {
	return mock.listReleases
}

// ListCommits returns the listCommits script.
func (mock *Mock) ListCommits() *connectormock.Query[github.ListCommitsInput, github.CommitPage] {
	return mock.listCommits
}

type mockOperations struct{ mock *Mock }

func (operations mockOperations) GetAuthenticatedProfile() sdkgo.Query[github.GetAuthenticatedProfileInput, github.AuthenticatedProfile] {
	return operations.mock.getAuthenticatedProfile
}
func (operations mockOperations) ListPublicRepositories() sdkgo.Query[github.ListPublicRepositoriesInput, github.PublicRepositories] {
	return operations.mock.listPublicRepositories
}
func (operations mockOperations) ListMergedPullRequests() sdkgo.Query[github.ListMergedPullRequestsInput, github.MergedPullRequestPage] {
	return operations.mock.listMergedPullRequests
}
func (operations mockOperations) ListPullRequestFiles() sdkgo.Query[github.ListPullRequestFilesInput, github.PullRequestFilePage] {
	return operations.mock.listPullRequestFiles
}
func (operations mockOperations) ListReleases() sdkgo.Query[github.ListReleasesInput, github.ReleasePage] {
	return operations.mock.listReleases
}
func (operations mockOperations) ListCommits() sdkgo.Query[github.ListCommitsInput, github.CommitPage] {
	return operations.mock.listCommits
}

// GetAuthenticatedProfileProfileLoaded selects the profileLoaded branch: The authenticated profile and primary verified email were loaded.
func GetAuthenticatedProfileProfileLoaded(value github.AuthenticatedProfile, failure *sdkgo.Failure) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Branch(github.GetAuthenticatedProfileBranchProfileLoaded, value, failure)
}

// GetAuthenticatedProfileVerifiedEmailRequired selects the verifiedEmailRequired branch: A primary verified email was not available.
func GetAuthenticatedProfileVerifiedEmailRequired(value github.AuthenticatedProfile, failure *sdkgo.Failure) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Branch(github.GetAuthenticatedProfileBranchVerifiedEmailRequired, value, failure)
}

// GetAuthenticatedProfileInsufficientScope selects the insufficientScope branch: The OAuth grant does not match the required scopes.
func GetAuthenticatedProfileInsufficientScope(value github.AuthenticatedProfile, failure *sdkgo.Failure) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Branch(github.GetAuthenticatedProfileBranchInsufficientScope, value, failure)
}

// GetAuthenticatedProfileAuthorizationRevoked selects the authorizationRevoked branch: The OAuth grant is invalid or revoked.
func GetAuthenticatedProfileAuthorizationRevoked(value github.AuthenticatedProfile, failure *sdkgo.Failure) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Branch(github.GetAuthenticatedProfileBranchAuthorizationRevoked, value, failure)
}

// GetAuthenticatedProfileNotFound selects the notFound branch: The authenticated account was not found.
func GetAuthenticatedProfileNotFound(value github.AuthenticatedProfile, failure *sdkgo.Failure) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Branch(github.GetAuthenticatedProfileBranchNotFound, value, failure)
}

// GetAuthenticatedProfileProviderRejected selects the providerRejected branch: GitHub conclusively rejected the profile query.
func GetAuthenticatedProfileProviderRejected(value github.AuthenticatedProfile, failure *sdkgo.Failure) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Branch(github.GetAuthenticatedProfileBranchProviderRejected, value, failure)
}

// GetAuthenticatedProfileInvalidResponse selects the invalidResponse branch: GitHub returned an invalid or oversized profile response.
func GetAuthenticatedProfileInvalidResponse(value github.AuthenticatedProfile, failure *sdkgo.Failure) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Branch(github.GetAuthenticatedProfileBranchInvalidResponse, value, failure)
}

// GetAuthenticatedProfileDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func GetAuthenticatedProfileDefect(value github.AuthenticatedProfile, failure *sdkgo.Failure) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Branch(github.GetAuthenticatedProfileBranchDefect, value, failure)
}

// GetAuthenticatedProfileRetry asks Dex to retry the getAuthenticatedProfile Step, after the delay when it is positive.
func GetAuthenticatedProfileRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Retry[github.AuthenticatedProfile](failure, after)
}

// GetAuthenticatedProfileOctocatProfile is the manifest mock octocatProfile: The authenticated account with a primary verified email and every optional profile field.
func GetAuthenticatedProfileOctocatProfile() connectormock.Case[github.AuthenticatedProfile] {
	value := connectormock.MustDecodeOutput[github.AuthenticatedProfile](`{"subject":"583231","login":"octocat","name":"The Octocat","verifiedEmail":"octocat@example.com","avatarUrl":"https://avatars.example.com/u/583231","profileUrl":"https://github.com/octocat","company":"@github","blogUrl":"https://github.blog","location":"San Francisco","bio":"Mascot","twitterUsername":"github","publicRepos":8,"followers":9000,"following":9,"createdAt":"2011-01-25T18:44:36Z","updatedAt":"2026-02-01T10:00:00Z"}`)
	return connectormock.Branch(github.GetAuthenticatedProfileBranchProfileLoaded, value, nil)
}

// GetAuthenticatedProfileRateLimited is the manifest mock rateLimited: GitHub's secondary rate limit throttles the read once.
func GetAuthenticatedProfileRateLimited() connectormock.Case[github.AuthenticatedProfile] {
	return connectormock.Retry[github.AuthenticatedProfile](sdkgo.Failure{Kind: sdkgo.FailureRateLimit, Message: "GitHub rate limit was reached."}, time.Duration(1000000000))
}

// GetAuthenticatedProfileVerifiedEmailRequiredFailure is the manifest mock verifiedEmailRequiredFailure: A primary verified email was not available.
func GetAuthenticatedProfileVerifiedEmailRequiredFailure() connectormock.Case[github.AuthenticatedProfile] {
	var value github.AuthenticatedProfile
	return connectormock.Branch(github.GetAuthenticatedProfileBranchVerifiedEmailRequired, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthentication, Message: "A primary verified email was not available."})
}

// GetAuthenticatedProfileInsufficientScopeFailure is the manifest mock insufficientScopeFailure: The OAuth grant does not match the required scopes.
func GetAuthenticatedProfileInsufficientScopeFailure() connectormock.Case[github.AuthenticatedProfile] {
	var value github.AuthenticatedProfile
	return connectormock.Branch(github.GetAuthenticatedProfileBranchInsufficientScope, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthorization, Message: "The OAuth grant does not match the required scopes."})
}

// GetAuthenticatedProfileAuthorizationRevokedFailure is the manifest mock authorizationRevokedFailure: The OAuth grant is invalid or revoked.
func GetAuthenticatedProfileAuthorizationRevokedFailure() connectormock.Case[github.AuthenticatedProfile] {
	var value github.AuthenticatedProfile
	return connectormock.Branch(github.GetAuthenticatedProfileBranchAuthorizationRevoked, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthentication, Message: "The OAuth grant is invalid or revoked."})
}

// GetAuthenticatedProfileNotFoundFailure is the manifest mock notFoundFailure: The authenticated account was not found.
func GetAuthenticatedProfileNotFoundFailure() connectormock.Case[github.AuthenticatedProfile] {
	var value github.AuthenticatedProfile
	return connectormock.Branch(github.GetAuthenticatedProfileBranchNotFound, value, &sdkgo.Failure{Kind: sdkgo.FailureNotFound, Message: "The authenticated account was not found."})
}

// GetAuthenticatedProfileProviderRejectedFailure is the manifest mock providerRejectedFailure: GitHub conclusively rejected the profile query.
func GetAuthenticatedProfileProviderRejectedFailure() connectormock.Case[github.AuthenticatedProfile] {
	var value github.AuthenticatedProfile
	return connectormock.Branch(github.GetAuthenticatedProfileBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureProviderRejection, Message: "GitHub conclusively rejected the profile query."})
}

// GetAuthenticatedProfileInvalidResponseFailure is the manifest mock invalidResponseFailure: GitHub returned an invalid or oversized profile response.
func GetAuthenticatedProfileInvalidResponseFailure() connectormock.Case[github.AuthenticatedProfile] {
	var value github.AuthenticatedProfile
	return connectormock.Branch(github.GetAuthenticatedProfileBranchInvalidResponse, value, &sdkgo.Failure{Kind: sdkgo.FailureProtocol, Message: "GitHub returned an invalid or oversized profile response."})
}

// GetAuthenticatedProfileDefectFailure is the manifest mock defectFailure: Local input, connection configuration, or connector definition is invalid.
func GetAuthenticatedProfileDefectFailure() connectormock.Case[github.AuthenticatedProfile] {
	var value github.AuthenticatedProfile
	return connectormock.Branch(github.GetAuthenticatedProfileBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "Local input, connection configuration, or connector definition is invalid."})
}

// GetAuthenticatedProfileDefault is the manifest default, octocatProfile, which New installs.
func GetAuthenticatedProfileDefault() connectormock.Case[github.AuthenticatedProfile] {
	return GetAuthenticatedProfileOctocatProfile()
}

// ListPublicRepositoriesRepositoriesLoaded selects the repositoriesLoaded branch: Public repositories were loaded and bounded.
func ListPublicRepositoriesRepositoriesLoaded(value github.PublicRepositories, failure *sdkgo.Failure) connectormock.Case[github.PublicRepositories] {
	return connectormock.Branch(github.ListPublicRepositoriesBranchRepositoriesLoaded, value, failure)
}

// ListPublicRepositoriesInsufficientScope selects the insufficientScope branch: The OAuth grant does not match the required scopes.
func ListPublicRepositoriesInsufficientScope(value github.PublicRepositories, failure *sdkgo.Failure) connectormock.Case[github.PublicRepositories] {
	return connectormock.Branch(github.ListPublicRepositoriesBranchInsufficientScope, value, failure)
}

// ListPublicRepositoriesAuthorizationRevoked selects the authorizationRevoked branch: The OAuth grant is invalid or revoked.
func ListPublicRepositoriesAuthorizationRevoked(value github.PublicRepositories, failure *sdkgo.Failure) connectormock.Case[github.PublicRepositories] {
	return connectormock.Branch(github.ListPublicRepositoriesBranchAuthorizationRevoked, value, failure)
}

// ListPublicRepositoriesNotFound selects the notFound branch: The requested GitHub account was not found.
func ListPublicRepositoriesNotFound(value github.PublicRepositories, failure *sdkgo.Failure) connectormock.Case[github.PublicRepositories] {
	return connectormock.Branch(github.ListPublicRepositoriesBranchNotFound, value, failure)
}

// ListPublicRepositoriesProviderRejected selects the providerRejected branch: GitHub conclusively rejected the repository query.
func ListPublicRepositoriesProviderRejected(value github.PublicRepositories, failure *sdkgo.Failure) connectormock.Case[github.PublicRepositories] {
	return connectormock.Branch(github.ListPublicRepositoriesBranchProviderRejected, value, failure)
}

// ListPublicRepositoriesInvalidResponse selects the invalidResponse branch: GitHub returned an invalid or oversized repository response.
func ListPublicRepositoriesInvalidResponse(value github.PublicRepositories, failure *sdkgo.Failure) connectormock.Case[github.PublicRepositories] {
	return connectormock.Branch(github.ListPublicRepositoriesBranchInvalidResponse, value, failure)
}

// ListPublicRepositoriesDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func ListPublicRepositoriesDefect(value github.PublicRepositories, failure *sdkgo.Failure) connectormock.Case[github.PublicRepositories] {
	return connectormock.Branch(github.ListPublicRepositoriesBranchDefect, value, failure)
}

// ListPublicRepositoriesRetry asks Dex to retry the listPublicRepositories Step, after the delay when it is positive.
func ListPublicRepositoriesRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[github.PublicRepositories] {
	return connectormock.Retry[github.PublicRepositories](failure, after)
}

// ListPublicRepositoriesMixedRepositories is the manifest mock mixedRepositories: A truncated recent-first set with a fork, an archived repository, and a disabled one that applications usually filter out.
func ListPublicRepositoriesMixedRepositories() connectormock.Case[github.PublicRepositories] {
	value := connectormock.MustDecodeOutput[github.PublicRepositories](`{"repositories":[{"id":1296269,"name":"hello-world","fullName":"octocat/hello-world","description":"My first repository.","profileUrl":"https://github.com/octocat/hello-world","language":"Go","topics":["example","dex"],"fork":false,"archived":false,"disabled":false,"stargazersCount":80,"forksCount":9,"openIssuesCount":2,"pushedAt":"2026-03-01T12:00:00Z"},{"id":1300192,"name":"spoon-knife","fullName":"octocat/spoon-knife","fork":true,"archived":false,"disabled":false,"stargazersCount":12,"forksCount":0,"openIssuesCount":0,"pushedAt":"2026-02-20T08:30:00Z"},{"id":1400300,"name":"old-site","fullName":"octocat/old-site","fork":false,"archived":true,"disabled":false,"stargazersCount":3,"forksCount":1,"openIssuesCount":0,"pushedAt":"2019-05-04T00:00:00Z"},{"id":1500400,"name":"suspended","fullName":"octocat/suspended","fork":false,"archived":false,"disabled":true,"stargazersCount":0,"forksCount":0,"openIssuesCount":0}],"truncated":true}`)
	return connectormock.Branch(github.ListPublicRepositoriesBranchRepositoriesLoaded, value, nil)
}

// ListPublicRepositoriesNoRepositories is the manifest mock noRepositories: The login owns no public repositories.
func ListPublicRepositoriesNoRepositories() connectormock.Case[github.PublicRepositories] {
	value := connectormock.MustDecodeOutput[github.PublicRepositories](`{"repositories":[],"truncated":false}`)
	return connectormock.Branch(github.ListPublicRepositoriesBranchRepositoriesLoaded, value, nil)
}

// ListPublicRepositoriesRateLimited is the manifest mock rateLimited: GitHub's secondary rate limit throttles the listing once.
func ListPublicRepositoriesRateLimited() connectormock.Case[github.PublicRepositories] {
	return connectormock.Retry[github.PublicRepositories](sdkgo.Failure{Kind: sdkgo.FailureRateLimit, Message: "GitHub rate limit was reached."}, time.Duration(1000000000))
}

// ListPublicRepositoriesInsufficientScopeFailure is the manifest mock insufficientScopeFailure: The OAuth grant does not match the required scopes.
func ListPublicRepositoriesInsufficientScopeFailure() connectormock.Case[github.PublicRepositories] {
	var value github.PublicRepositories
	return connectormock.Branch(github.ListPublicRepositoriesBranchInsufficientScope, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthorization, Message: "The OAuth grant does not match the required scopes."})
}

// ListPublicRepositoriesAuthorizationRevokedFailure is the manifest mock authorizationRevokedFailure: The OAuth grant is invalid or revoked.
func ListPublicRepositoriesAuthorizationRevokedFailure() connectormock.Case[github.PublicRepositories] {
	var value github.PublicRepositories
	return connectormock.Branch(github.ListPublicRepositoriesBranchAuthorizationRevoked, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthentication, Message: "The OAuth grant is invalid or revoked."})
}

// ListPublicRepositoriesNotFoundFailure is the manifest mock notFoundFailure: The requested GitHub account was not found.
func ListPublicRepositoriesNotFoundFailure() connectormock.Case[github.PublicRepositories] {
	var value github.PublicRepositories
	return connectormock.Branch(github.ListPublicRepositoriesBranchNotFound, value, &sdkgo.Failure{Kind: sdkgo.FailureNotFound, Message: "The requested GitHub account was not found."})
}

// ListPublicRepositoriesProviderRejectedFailure is the manifest mock providerRejectedFailure: GitHub conclusively rejected the repository query.
func ListPublicRepositoriesProviderRejectedFailure() connectormock.Case[github.PublicRepositories] {
	var value github.PublicRepositories
	return connectormock.Branch(github.ListPublicRepositoriesBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureProviderRejection, Message: "GitHub conclusively rejected the repository query."})
}

// ListPublicRepositoriesInvalidResponseFailure is the manifest mock invalidResponseFailure: GitHub returned an invalid or oversized repository response.
func ListPublicRepositoriesInvalidResponseFailure() connectormock.Case[github.PublicRepositories] {
	var value github.PublicRepositories
	return connectormock.Branch(github.ListPublicRepositoriesBranchInvalidResponse, value, &sdkgo.Failure{Kind: sdkgo.FailureProtocol, Message: "GitHub returned an invalid or oversized repository response."})
}

// ListPublicRepositoriesDefectFailure is the manifest mock defectFailure: Local input, connection configuration, or connector definition is invalid.
func ListPublicRepositoriesDefectFailure() connectormock.Case[github.PublicRepositories] {
	var value github.PublicRepositories
	return connectormock.Branch(github.ListPublicRepositoriesBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "Local input, connection configuration, or connector definition is invalid."})
}

// ListPublicRepositoriesDefault is the manifest default, mixedRepositories, which New installs.
func ListPublicRepositoriesDefault() connectormock.Case[github.PublicRepositories] {
	return ListPublicRepositoriesMixedRepositories()
}

// ListMergedPullRequestsListed selects the listed branch: One bounded page of merged pull requests was loaded.
func ListMergedPullRequestsListed(value github.MergedPullRequestPage, failure *sdkgo.Failure) connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Branch(github.ListMergedPullRequestsBranchListed, value, failure)
}

// ListMergedPullRequestsInsufficientScope selects the insufficientScope branch: The OAuth grant does not match the required scopes.
func ListMergedPullRequestsInsufficientScope(value github.MergedPullRequestPage, failure *sdkgo.Failure) connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Branch(github.ListMergedPullRequestsBranchInsufficientScope, value, failure)
}

// ListMergedPullRequestsAuthorizationRevoked selects the authorizationRevoked branch: The OAuth grant is invalid or revoked.
func ListMergedPullRequestsAuthorizationRevoked(value github.MergedPullRequestPage, failure *sdkgo.Failure) connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Branch(github.ListMergedPullRequestsBranchAuthorizationRevoked, value, failure)
}

// ListMergedPullRequestsNotFound selects the notFound branch: The requested GitHub resource was not found.
func ListMergedPullRequestsNotFound(value github.MergedPullRequestPage, failure *sdkgo.Failure) connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Branch(github.ListMergedPullRequestsBranchNotFound, value, failure)
}

// ListMergedPullRequestsProviderRejected selects the providerRejected branch: GitHub conclusively rejected the search, including a repository it cannot search.
func ListMergedPullRequestsProviderRejected(value github.MergedPullRequestPage, failure *sdkgo.Failure) connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Branch(github.ListMergedPullRequestsBranchProviderRejected, value, failure)
}

// ListMergedPullRequestsInvalidResponse selects the invalidResponse branch: GitHub returned an invalid or oversized search response.
func ListMergedPullRequestsInvalidResponse(value github.MergedPullRequestPage, failure *sdkgo.Failure) connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Branch(github.ListMergedPullRequestsBranchInvalidResponse, value, failure)
}

// ListMergedPullRequestsDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func ListMergedPullRequestsDefect(value github.MergedPullRequestPage, failure *sdkgo.Failure) connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Branch(github.ListMergedPullRequestsBranchDefect, value, failure)
}

// ListMergedPullRequestsRetry asks Dex to retry the listMergedPullRequests Step, after the delay when it is positive.
func ListMergedPullRequestsRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Retry[github.MergedPullRequestPage](failure, after)
}

// ListMergedPullRequestsThreeUnorderedPages is the manifest mock threeUnorderedPages: Three pages in GitHub search order, not merge order, with a pull request repeated across a page boundary and merges exactly at both window edges.
func ListMergedPullRequestsThreeUnorderedPages() connectormock.Case[github.MergedPullRequestPage] {
	pages := []github.MergedPullRequestPage{
		connectormock.MustDecodeOutput[github.MergedPullRequestPage](`{"pullRequests":[{"number":42,"title":"Add release notes","bodyTruncated":false,"url":"https://github.com/octocat/hello-world/pull/42","authorLogin":"octocat","mergedAt":"2026-03-03T10:00:00Z","labels":["docs"]},{"number":40,"title":"Fix flaky test","body":"The retry waited too long.","bodyTruncated":false,"authorLogin":"hubot","mergedAt":"2026-03-01T00:00:00Z"}],"totalCount":5,"incompleteResults":false,"nextPage":2}`),
		connectormock.MustDecodeOutput[github.MergedPullRequestPage](`{"pullRequests":[{"number":40,"title":"Fix flaky test","body":"The retry waited too long.","bodyTruncated":false,"authorLogin":"hubot","mergedAt":"2026-03-01T00:00:00Z"},{"number":45,"title":"Bump dependencies","bodyTruncated":false,"authorLogin":"dependabot","mergedAt":"2026-03-07T23:59:59Z","labels":["dependencies"]}],"totalCount":5,"incompleteResults":false,"nextPage":3}`),
		connectormock.MustDecodeOutput[github.MergedPullRequestPage](`{"pullRequests":[{"number":38,"title":"Rewrite the README","body":"A long body","bodyTruncated":true,"authorLogin":"octocat","mergedAt":"2026-03-05T16:20:00Z"}],"totalCount":5,"incompleteResults":false,"nextPage":0}`),
	}
	pageNumber := connectormock.CursorPageNumber[github.ListMergedPullRequestsInput]("page", "nextPage", pages)
	return connectormock.Paged(github.ListMergedPullRequestsBranchListed, pageNumber, pages...)
}

// ListMergedPullRequestsNoMerges is the manifest mock noMerges: No pull request merged in the window.
func ListMergedPullRequestsNoMerges() connectormock.Case[github.MergedPullRequestPage] {
	value := connectormock.MustDecodeOutput[github.MergedPullRequestPage](`{"pullRequests":[],"totalCount":0,"incompleteResults":false,"nextPage":0}`)
	return connectormock.Branch(github.ListMergedPullRequestsBranchListed, value, nil)
}

// ListMergedPullRequestsIncompleteSearch is the manifest mock incompleteSearch: GitHub search timed out and returned a partial page.
func ListMergedPullRequestsIncompleteSearch() connectormock.Case[github.MergedPullRequestPage] {
	value := connectormock.MustDecodeOutput[github.MergedPullRequestPage](`{"pullRequests":[{"number":42,"title":"Add release notes","bodyTruncated":false,"mergedAt":"2026-03-03T10:00:00Z"}],"totalCount":7,"incompleteResults":true,"nextPage":0}`)
	return connectormock.Branch(github.ListMergedPullRequestsBranchListed, value, nil)
}

// ListMergedPullRequestsRateLimited is the manifest mock rateLimited: GitHub's search rate limit throttles the listing and asks for a wait.
func ListMergedPullRequestsRateLimited() connectormock.Case[github.MergedPullRequestPage] {
	return connectormock.Retry[github.MergedPullRequestPage](sdkgo.Failure{Kind: sdkgo.FailureRateLimit, Message: "GitHub search rate limit was reached."}, time.Duration(30000000000))
}

// ListMergedPullRequestsInsufficientScopeFailure is the manifest mock insufficientScopeFailure: The OAuth grant does not match the required scopes.
func ListMergedPullRequestsInsufficientScopeFailure() connectormock.Case[github.MergedPullRequestPage] {
	var value github.MergedPullRequestPage
	return connectormock.Branch(github.ListMergedPullRequestsBranchInsufficientScope, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthorization, Message: "The OAuth grant does not match the required scopes."})
}

// ListMergedPullRequestsAuthorizationRevokedFailure is the manifest mock authorizationRevokedFailure: The OAuth grant is invalid or revoked.
func ListMergedPullRequestsAuthorizationRevokedFailure() connectormock.Case[github.MergedPullRequestPage] {
	var value github.MergedPullRequestPage
	return connectormock.Branch(github.ListMergedPullRequestsBranchAuthorizationRevoked, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthentication, Message: "The OAuth grant is invalid or revoked."})
}

// ListMergedPullRequestsNotFoundFailure is the manifest mock notFoundFailure: The requested GitHub resource was not found.
func ListMergedPullRequestsNotFoundFailure() connectormock.Case[github.MergedPullRequestPage] {
	var value github.MergedPullRequestPage
	return connectormock.Branch(github.ListMergedPullRequestsBranchNotFound, value, &sdkgo.Failure{Kind: sdkgo.FailureNotFound, Message: "The requested GitHub resource was not found."})
}

// ListMergedPullRequestsProviderRejectedFailure is the manifest mock providerRejectedFailure: GitHub conclusively rejected the search, including a repository it cannot search.
func ListMergedPullRequestsProviderRejectedFailure() connectormock.Case[github.MergedPullRequestPage] {
	var value github.MergedPullRequestPage
	return connectormock.Branch(github.ListMergedPullRequestsBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureProviderRejection, Message: "GitHub conclusively rejected the search, including a repository it cannot search."})
}

// ListMergedPullRequestsInvalidResponseFailure is the manifest mock invalidResponseFailure: GitHub returned an invalid or oversized search response.
func ListMergedPullRequestsInvalidResponseFailure() connectormock.Case[github.MergedPullRequestPage] {
	var value github.MergedPullRequestPage
	return connectormock.Branch(github.ListMergedPullRequestsBranchInvalidResponse, value, &sdkgo.Failure{Kind: sdkgo.FailureProtocol, Message: "GitHub returned an invalid or oversized search response."})
}

// ListMergedPullRequestsDefectFailure is the manifest mock defectFailure: Local input, connection configuration, or connector definition is invalid.
func ListMergedPullRequestsDefectFailure() connectormock.Case[github.MergedPullRequestPage] {
	var value github.MergedPullRequestPage
	return connectormock.Branch(github.ListMergedPullRequestsBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "Local input, connection configuration, or connector definition is invalid."})
}

// ListMergedPullRequestsDefault is the manifest default, threeUnorderedPages, which New installs.
func ListMergedPullRequestsDefault() connectormock.Case[github.MergedPullRequestPage] {
	return ListMergedPullRequestsThreeUnorderedPages()
}

// ListPullRequestFilesListed selects the listed branch: One bounded page of changed files was loaded.
func ListPullRequestFilesListed(value github.PullRequestFilePage, failure *sdkgo.Failure) connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Branch(github.ListPullRequestFilesBranchListed, value, failure)
}

// ListPullRequestFilesInsufficientScope selects the insufficientScope branch: The OAuth grant does not match the required scopes.
func ListPullRequestFilesInsufficientScope(value github.PullRequestFilePage, failure *sdkgo.Failure) connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Branch(github.ListPullRequestFilesBranchInsufficientScope, value, failure)
}

// ListPullRequestFilesAuthorizationRevoked selects the authorizationRevoked branch: The OAuth grant is invalid or revoked.
func ListPullRequestFilesAuthorizationRevoked(value github.PullRequestFilePage, failure *sdkgo.Failure) connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Branch(github.ListPullRequestFilesBranchAuthorizationRevoked, value, failure)
}

// ListPullRequestFilesNotFound selects the notFound branch: The repository or pull request was not found.
func ListPullRequestFilesNotFound(value github.PullRequestFilePage, failure *sdkgo.Failure) connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Branch(github.ListPullRequestFilesBranchNotFound, value, failure)
}

// ListPullRequestFilesProviderRejected selects the providerRejected branch: GitHub conclusively rejected the changed-file query.
func ListPullRequestFilesProviderRejected(value github.PullRequestFilePage, failure *sdkgo.Failure) connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Branch(github.ListPullRequestFilesBranchProviderRejected, value, failure)
}

// ListPullRequestFilesInvalidResponse selects the invalidResponse branch: GitHub returned an invalid or oversized changed-file response.
func ListPullRequestFilesInvalidResponse(value github.PullRequestFilePage, failure *sdkgo.Failure) connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Branch(github.ListPullRequestFilesBranchInvalidResponse, value, failure)
}

// ListPullRequestFilesDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func ListPullRequestFilesDefect(value github.PullRequestFilePage, failure *sdkgo.Failure) connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Branch(github.ListPullRequestFilesBranchDefect, value, failure)
}

// ListPullRequestFilesRetry asks Dex to retry the listPullRequestFiles Step, after the delay when it is positive.
func ListPullRequestFilesRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Retry[github.PullRequestFilePage](failure, after)
}

// ListPullRequestFilesThreePagesOfChanges is the manifest mock threePagesOfChanges: Three pages of added, modified, renamed, and removed files, with a truncated patch and a binary file without a patch.
func ListPullRequestFilesThreePagesOfChanges() connectormock.Case[github.PullRequestFilePage] {
	pages := []github.PullRequestFilePage{
		connectormock.MustDecodeOutput[github.PullRequestFilePage](`{"files":[{"filename":"README.md","status":"modified","additions":3,"deletions":1,"changes":4,"patch":"@@ -1 +1,3 @@","patchTruncated":false},{"filename":"docs/guide.md","previousFilename":"docs/old-guide.md","status":"renamed","additions":0,"deletions":0,"changes":0,"patchTruncated":false}],"nextPage":2}`),
		connectormock.MustDecodeOutput[github.PullRequestFilePage](`{"files":[{"filename":"logo.png","status":"added","additions":0,"deletions":0,"changes":0,"patchTruncated":false},{"filename":"main.go","status":"modified","additions":400,"deletions":120,"changes":520,"patch":"@@ -1,120 +1,400 @@","patchTruncated":true}],"nextPage":3}`),
		connectormock.MustDecodeOutput[github.PullRequestFilePage](`{"files":[{"filename":"legacy.go","status":"removed","additions":0,"deletions":80,"changes":80,"patchTruncated":false}],"nextPage":0}`),
	}
	pageNumber := connectormock.CursorPageNumber[github.ListPullRequestFilesInput]("page", "nextPage", pages)
	return connectormock.Paged(github.ListPullRequestFilesBranchListed, pageNumber, pages...)
}

// ListPullRequestFilesRateLimited is the manifest mock rateLimited: GitHub's rate limit throttles the listing once.
func ListPullRequestFilesRateLimited() connectormock.Case[github.PullRequestFilePage] {
	return connectormock.Retry[github.PullRequestFilePage](sdkgo.Failure{Kind: sdkgo.FailureRateLimit, Message: "GitHub rate limit was reached."}, time.Duration(1000000000))
}

// ListPullRequestFilesInsufficientScopeFailure is the manifest mock insufficientScopeFailure: The OAuth grant does not match the required scopes.
func ListPullRequestFilesInsufficientScopeFailure() connectormock.Case[github.PullRequestFilePage] {
	var value github.PullRequestFilePage
	return connectormock.Branch(github.ListPullRequestFilesBranchInsufficientScope, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthorization, Message: "The OAuth grant does not match the required scopes."})
}

// ListPullRequestFilesAuthorizationRevokedFailure is the manifest mock authorizationRevokedFailure: The OAuth grant is invalid or revoked.
func ListPullRequestFilesAuthorizationRevokedFailure() connectormock.Case[github.PullRequestFilePage] {
	var value github.PullRequestFilePage
	return connectormock.Branch(github.ListPullRequestFilesBranchAuthorizationRevoked, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthentication, Message: "The OAuth grant is invalid or revoked."})
}

// ListPullRequestFilesNotFoundFailure is the manifest mock notFoundFailure: The repository or pull request was not found.
func ListPullRequestFilesNotFoundFailure() connectormock.Case[github.PullRequestFilePage] {
	var value github.PullRequestFilePage
	return connectormock.Branch(github.ListPullRequestFilesBranchNotFound, value, &sdkgo.Failure{Kind: sdkgo.FailureNotFound, Message: "The repository or pull request was not found."})
}

// ListPullRequestFilesProviderRejectedFailure is the manifest mock providerRejectedFailure: GitHub conclusively rejected the changed-file query.
func ListPullRequestFilesProviderRejectedFailure() connectormock.Case[github.PullRequestFilePage] {
	var value github.PullRequestFilePage
	return connectormock.Branch(github.ListPullRequestFilesBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureProviderRejection, Message: "GitHub conclusively rejected the changed-file query."})
}

// ListPullRequestFilesInvalidResponseFailure is the manifest mock invalidResponseFailure: GitHub returned an invalid or oversized changed-file response.
func ListPullRequestFilesInvalidResponseFailure() connectormock.Case[github.PullRequestFilePage] {
	var value github.PullRequestFilePage
	return connectormock.Branch(github.ListPullRequestFilesBranchInvalidResponse, value, &sdkgo.Failure{Kind: sdkgo.FailureProtocol, Message: "GitHub returned an invalid or oversized changed-file response."})
}

// ListPullRequestFilesDefectFailure is the manifest mock defectFailure: Local input, connection configuration, or connector definition is invalid.
func ListPullRequestFilesDefectFailure() connectormock.Case[github.PullRequestFilePage] {
	var value github.PullRequestFilePage
	return connectormock.Branch(github.ListPullRequestFilesBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "Local input, connection configuration, or connector definition is invalid."})
}

// ListPullRequestFilesDefault is the manifest default, threePagesOfChanges, which New installs.
func ListPullRequestFilesDefault() connectormock.Case[github.PullRequestFilePage] {
	return ListPullRequestFilesThreePagesOfChanges()
}

// ListReleasesListed selects the listed branch: One bounded page of releases was loaded, possibly empty.
func ListReleasesListed(value github.ReleasePage, failure *sdkgo.Failure) connectormock.Case[github.ReleasePage] {
	return connectormock.Branch(github.ListReleasesBranchListed, value, failure)
}

// ListReleasesInsufficientScope selects the insufficientScope branch: The OAuth grant does not match the required scopes.
func ListReleasesInsufficientScope(value github.ReleasePage, failure *sdkgo.Failure) connectormock.Case[github.ReleasePage] {
	return connectormock.Branch(github.ListReleasesBranchInsufficientScope, value, failure)
}

// ListReleasesAuthorizationRevoked selects the authorizationRevoked branch: The OAuth grant is invalid or revoked.
func ListReleasesAuthorizationRevoked(value github.ReleasePage, failure *sdkgo.Failure) connectormock.Case[github.ReleasePage] {
	return connectormock.Branch(github.ListReleasesBranchAuthorizationRevoked, value, failure)
}

// ListReleasesNotFound selects the notFound branch: The repository was not found or is inaccessible.
func ListReleasesNotFound(value github.ReleasePage, failure *sdkgo.Failure) connectormock.Case[github.ReleasePage] {
	return connectormock.Branch(github.ListReleasesBranchNotFound, value, failure)
}

// ListReleasesProviderRejected selects the providerRejected branch: GitHub conclusively rejected the releases query.
func ListReleasesProviderRejected(value github.ReleasePage, failure *sdkgo.Failure) connectormock.Case[github.ReleasePage] {
	return connectormock.Branch(github.ListReleasesBranchProviderRejected, value, failure)
}

// ListReleasesInvalidResponse selects the invalidResponse branch: GitHub returned an invalid or oversized releases response.
func ListReleasesInvalidResponse(value github.ReleasePage, failure *sdkgo.Failure) connectormock.Case[github.ReleasePage] {
	return connectormock.Branch(github.ListReleasesBranchInvalidResponse, value, failure)
}

// ListReleasesDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func ListReleasesDefect(value github.ReleasePage, failure *sdkgo.Failure) connectormock.Case[github.ReleasePage] {
	return connectormock.Branch(github.ListReleasesBranchDefect, value, failure)
}

// ListReleasesRetry asks Dex to retry the listReleases Step, after the delay when it is positive.
func ListReleasesRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[github.ReleasePage] {
	return connectormock.Retry[github.ReleasePage](failure, after)
}

// ListReleasesThreeUnorderedPages is the manifest mock threeUnorderedPages: Three pages in GitHub order, not publication order, with a draft, a prerelease, a release repeated across a page boundary, and one published outside a typical window.
func ListReleasesThreeUnorderedPages() connectormock.Case[github.ReleasePage] {
	pages := []github.ReleasePage{
		connectormock.MustDecodeOutput[github.ReleasePage](`{"releases":[{"id":300,"tagName":"v1.3.0","name":"v1.3.0","url":"https://github.com/octocat/hello-world/releases/tag/v1.3.0","body":"Faster startup.","bodyTruncated":false,"isDraft":false,"isPrerelease":false,"createdAt":"2026-03-05T09:00:00Z","publishedAt":"2026-03-05T09:30:00Z"},{"id":310,"tagName":"v1.4.0-rc.1","bodyTruncated":false,"isDraft":false,"isPrerelease":true,"createdAt":"2026-03-06T09:00:00Z","publishedAt":"2026-03-06T09:05:00Z"}],"nextPage":2}`),
		connectormock.MustDecodeOutput[github.ReleasePage](`{"releases":[{"id":310,"tagName":"v1.4.0-rc.1","bodyTruncated":false,"isDraft":false,"isPrerelease":true,"createdAt":"2026-03-06T09:00:00Z","publishedAt":"2026-03-06T09:05:00Z"},{"id":320,"tagName":"v1.4.0","bodyTruncated":false,"isDraft":true,"isPrerelease":false,"createdAt":"2026-03-07T09:00:00Z"}],"nextPage":3}`),
		connectormock.MustDecodeOutput[github.ReleasePage](`{"releases":[{"id":200,"tagName":"v1.2.0","name":"v1.2.0","body":"A long list of changes","bodyTruncated":true,"isDraft":false,"isPrerelease":false,"createdAt":"2025-11-01T09:00:00Z","publishedAt":"2025-11-02T09:00:00Z"},{"id":290,"tagName":"v1.2.9","bodyTruncated":false,"isDraft":false,"isPrerelease":false,"createdAt":"2026-03-01T00:00:00Z","publishedAt":"2026-03-01T00:00:00Z"}],"nextPage":0}`),
	}
	pageNumber := connectormock.CursorPageNumber[github.ListReleasesInput]("page", "nextPage", pages)
	return connectormock.Paged(github.ListReleasesBranchListed, pageNumber, pages...)
}

// ListReleasesNoReleases is the manifest mock noReleases: The repository has no releases.
func ListReleasesNoReleases() connectormock.Case[github.ReleasePage] {
	value := connectormock.MustDecodeOutput[github.ReleasePage](`{"releases":[],"nextPage":0}`)
	return connectormock.Branch(github.ListReleasesBranchListed, value, nil)
}

// ListReleasesRateLimited is the manifest mock rateLimited: GitHub's rate limit throttles the listing once.
func ListReleasesRateLimited() connectormock.Case[github.ReleasePage] {
	return connectormock.Retry[github.ReleasePage](sdkgo.Failure{Kind: sdkgo.FailureRateLimit, Message: "GitHub rate limit was reached."}, time.Duration(1000000000))
}

// ListReleasesInsufficientScopeFailure is the manifest mock insufficientScopeFailure: The OAuth grant does not match the required scopes.
func ListReleasesInsufficientScopeFailure() connectormock.Case[github.ReleasePage] {
	var value github.ReleasePage
	return connectormock.Branch(github.ListReleasesBranchInsufficientScope, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthorization, Message: "The OAuth grant does not match the required scopes."})
}

// ListReleasesAuthorizationRevokedFailure is the manifest mock authorizationRevokedFailure: The OAuth grant is invalid or revoked.
func ListReleasesAuthorizationRevokedFailure() connectormock.Case[github.ReleasePage] {
	var value github.ReleasePage
	return connectormock.Branch(github.ListReleasesBranchAuthorizationRevoked, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthentication, Message: "The OAuth grant is invalid or revoked."})
}

// ListReleasesNotFoundFailure is the manifest mock notFoundFailure: The repository was not found or is inaccessible.
func ListReleasesNotFoundFailure() connectormock.Case[github.ReleasePage] {
	var value github.ReleasePage
	return connectormock.Branch(github.ListReleasesBranchNotFound, value, &sdkgo.Failure{Kind: sdkgo.FailureNotFound, Message: "The repository was not found or is inaccessible."})
}

// ListReleasesProviderRejectedFailure is the manifest mock providerRejectedFailure: GitHub conclusively rejected the releases query.
func ListReleasesProviderRejectedFailure() connectormock.Case[github.ReleasePage] {
	var value github.ReleasePage
	return connectormock.Branch(github.ListReleasesBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureProviderRejection, Message: "GitHub conclusively rejected the releases query."})
}

// ListReleasesInvalidResponseFailure is the manifest mock invalidResponseFailure: GitHub returned an invalid or oversized releases response.
func ListReleasesInvalidResponseFailure() connectormock.Case[github.ReleasePage] {
	var value github.ReleasePage
	return connectormock.Branch(github.ListReleasesBranchInvalidResponse, value, &sdkgo.Failure{Kind: sdkgo.FailureProtocol, Message: "GitHub returned an invalid or oversized releases response."})
}

// ListReleasesDefectFailure is the manifest mock defectFailure: Local input, connection configuration, or connector definition is invalid.
func ListReleasesDefectFailure() connectormock.Case[github.ReleasePage] {
	var value github.ReleasePage
	return connectormock.Branch(github.ListReleasesBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "Local input, connection configuration, or connector definition is invalid."})
}

// ListReleasesDefault is the manifest default, threeUnorderedPages, which New installs.
func ListReleasesDefault() connectormock.Case[github.ReleasePage] {
	return ListReleasesThreeUnorderedPages()
}

// ListCommitsListed selects the listed branch: One bounded page of commits was loaded; an empty repository has no commits.
func ListCommitsListed(value github.CommitPage, failure *sdkgo.Failure) connectormock.Case[github.CommitPage] {
	return connectormock.Branch(github.ListCommitsBranchListed, value, failure)
}

// ListCommitsInsufficientScope selects the insufficientScope branch: The OAuth grant does not match the required scopes.
func ListCommitsInsufficientScope(value github.CommitPage, failure *sdkgo.Failure) connectormock.Case[github.CommitPage] {
	return connectormock.Branch(github.ListCommitsBranchInsufficientScope, value, failure)
}

// ListCommitsAuthorizationRevoked selects the authorizationRevoked branch: The OAuth grant is invalid or revoked.
func ListCommitsAuthorizationRevoked(value github.CommitPage, failure *sdkgo.Failure) connectormock.Case[github.CommitPage] {
	return connectormock.Branch(github.ListCommitsBranchAuthorizationRevoked, value, failure)
}

// ListCommitsNotFound selects the notFound branch: The repository or starting ref was not found.
func ListCommitsNotFound(value github.CommitPage, failure *sdkgo.Failure) connectormock.Case[github.CommitPage] {
	return connectormock.Branch(github.ListCommitsBranchNotFound, value, failure)
}

// ListCommitsProviderRejected selects the providerRejected branch: GitHub conclusively rejected the commit query.
func ListCommitsProviderRejected(value github.CommitPage, failure *sdkgo.Failure) connectormock.Case[github.CommitPage] {
	return connectormock.Branch(github.ListCommitsBranchProviderRejected, value, failure)
}

// ListCommitsInvalidResponse selects the invalidResponse branch: GitHub returned an invalid or oversized commit response.
func ListCommitsInvalidResponse(value github.CommitPage, failure *sdkgo.Failure) connectormock.Case[github.CommitPage] {
	return connectormock.Branch(github.ListCommitsBranchInvalidResponse, value, failure)
}

// ListCommitsDefect selects the defect branch: Local input, connection configuration, or connector definition is invalid.
func ListCommitsDefect(value github.CommitPage, failure *sdkgo.Failure) connectormock.Case[github.CommitPage] {
	return connectormock.Branch(github.ListCommitsBranchDefect, value, failure)
}

// ListCommitsRetry asks Dex to retry the listCommits Step, after the delay when it is positive.
func ListCommitsRetry(failure sdkgo.Failure, after time.Duration) connectormock.Case[github.CommitPage] {
	return connectormock.Retry[github.CommitPage](failure, after)
}

// ListCommitsThreePagesNewestFirst is the manifest mock threePagesNewestFirst: Three pages newest first, with a commit repeated across a page boundary as new commits shift pages, a truncated message, and a commit without a GitHub author.
func ListCommitsThreePagesNewestFirst() connectormock.Case[github.CommitPage] {
	pages := []github.CommitPage{
		connectormock.MustDecodeOutput[github.CommitPage](`{"commits":[{"sha":"6dcb09b5b57875f334f61aebed695e2e4193db5e","message":"Add release notes","messageTruncated":false,"authorLogin":"octocat","authorName":"The Octocat","authoredAt":"2026-03-06T10:00:00Z","committedAt":"2026-03-06T10:01:00Z","url":"https://github.com/octocat/hello-world/commit/6dcb09b5b57875f334f61aebed695e2e4193db5e"},{"sha":"7638417db6d59f3c431d3e1f261cc637155684cd","message":"Fix flaky test","messageTruncated":false,"authorLogin":"hubot","authorName":"Hubot","authoredAt":"2026-03-05T08:00:00Z","committedAt":"2026-03-05T08:00:00Z"}],"nextPage":2}`),
		connectormock.MustDecodeOutput[github.CommitPage](`{"commits":[{"sha":"7638417db6d59f3c431d3e1f261cc637155684cd","message":"Fix flaky test","messageTruncated":false,"authorLogin":"hubot","authorName":"Hubot","authoredAt":"2026-03-05T08:00:00Z","committedAt":"2026-03-05T08:00:00Z"},{"sha":"3a0f86fb8db8eea7ccbb9a95f325ddbedfb25e15","message":"A very long commit message","messageTruncated":true,"authorName":"Build Bot","authoredAt":"2026-03-04T23:59:59Z","committedAt":"2026-03-04T23:59:59Z"}],"nextPage":3}`),
		connectormock.MustDecodeOutput[github.CommitPage](`{"commits":[{"sha":"762941318ee16e59dabbacb1b4049eec22f0d303","message":"Initial commit","messageTruncated":false,"authorLogin":"octocat","authorName":"The Octocat","authoredAt":"2026-03-01T00:00:00Z","committedAt":"2026-03-01T00:00:00Z"}],"nextPage":0}`),
	}
	pageNumber := connectormock.CursorPageNumber[github.ListCommitsInput]("page", "nextPage", pages)
	return connectormock.Paged(github.ListCommitsBranchListed, pageNumber, pages...)
}

// ListCommitsEmptyRepository is the manifest mock emptyRepository: The repository has no commits in the window.
func ListCommitsEmptyRepository() connectormock.Case[github.CommitPage] {
	value := connectormock.MustDecodeOutput[github.CommitPage](`{"commits":[],"nextPage":0}`)
	return connectormock.Branch(github.ListCommitsBranchListed, value, nil)
}

// ListCommitsRateLimited is the manifest mock rateLimited: GitHub's rate limit throttles the listing once.
func ListCommitsRateLimited() connectormock.Case[github.CommitPage] {
	return connectormock.Retry[github.CommitPage](sdkgo.Failure{Kind: sdkgo.FailureRateLimit, Message: "GitHub rate limit was reached."}, time.Duration(1000000000))
}

// ListCommitsInsufficientScopeFailure is the manifest mock insufficientScopeFailure: The OAuth grant does not match the required scopes.
func ListCommitsInsufficientScopeFailure() connectormock.Case[github.CommitPage] {
	var value github.CommitPage
	return connectormock.Branch(github.ListCommitsBranchInsufficientScope, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthorization, Message: "The OAuth grant does not match the required scopes."})
}

// ListCommitsAuthorizationRevokedFailure is the manifest mock authorizationRevokedFailure: The OAuth grant is invalid or revoked.
func ListCommitsAuthorizationRevokedFailure() connectormock.Case[github.CommitPage] {
	var value github.CommitPage
	return connectormock.Branch(github.ListCommitsBranchAuthorizationRevoked, value, &sdkgo.Failure{Kind: sdkgo.FailureAuthentication, Message: "The OAuth grant is invalid or revoked."})
}

// ListCommitsNotFoundFailure is the manifest mock notFoundFailure: The repository or starting ref was not found.
func ListCommitsNotFoundFailure() connectormock.Case[github.CommitPage] {
	var value github.CommitPage
	return connectormock.Branch(github.ListCommitsBranchNotFound, value, &sdkgo.Failure{Kind: sdkgo.FailureNotFound, Message: "The repository or starting ref was not found."})
}

// ListCommitsProviderRejectedFailure is the manifest mock providerRejectedFailure: GitHub conclusively rejected the commit query.
func ListCommitsProviderRejectedFailure() connectormock.Case[github.CommitPage] {
	var value github.CommitPage
	return connectormock.Branch(github.ListCommitsBranchProviderRejected, value, &sdkgo.Failure{Kind: sdkgo.FailureProviderRejection, Message: "GitHub conclusively rejected the commit query."})
}

// ListCommitsInvalidResponseFailure is the manifest mock invalidResponseFailure: GitHub returned an invalid or oversized commit response.
func ListCommitsInvalidResponseFailure() connectormock.Case[github.CommitPage] {
	var value github.CommitPage
	return connectormock.Branch(github.ListCommitsBranchInvalidResponse, value, &sdkgo.Failure{Kind: sdkgo.FailureProtocol, Message: "GitHub returned an invalid or oversized commit response."})
}

// ListCommitsDefectFailure is the manifest mock defectFailure: Local input, connection configuration, or connector definition is invalid.
func ListCommitsDefectFailure() connectormock.Case[github.CommitPage] {
	var value github.CommitPage
	return connectormock.Branch(github.ListCommitsBranchDefect, value, &sdkgo.Failure{Kind: sdkgo.FailureValidation, Message: "Local input, connection configuration, or connector definition is invalid."})
}

// ListCommitsDefault is the manifest default, threePagesNewestFirst, which New installs.
func ListCommitsDefault() connectormock.Case[github.CommitPage] {
	return ListCommitsThreePagesNewestFirst()
}
