// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package quickbooks

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig/provider"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "quickbooks"

type Environment string

const (
	EnvironmentProduction Environment = "production"
	EnvironmentSandbox    Environment = "sandbox"
)

type Config struct {
	Environment      Environment `json:"environment,omitempty" yaml:"environment,omitempty"`
	RealmID          string      `json:"realmId,omitempty" yaml:"realmId,omitempty"`
	MaxResponseBytes int64       `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
}

type Credentials struct {
	ClientID     string
	ClientSecret sdkgo.SecretString
	AccessToken  sdkgo.SecretString
	RefreshToken sdkgo.SecretString
	IDToken      sdkgo.SecretString
}

// CredentialSource is the credential provider New requires: this connector refreshes its credentials.
type CredentialSource = sdkgo.RefreshingCredentialProvider[Credentials]

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

// NewConnection wraps a client built with New, such as a test client with a static credential provider.
// Applications open declared connections with NewProjectConnection instead.
func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("quickbooks connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("quickbooks connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewProjectConnection opens the connection that dex-app.yaml declares as connectionName from the
// loaded project configuration. It reads ordinary settings now and resolves credentials during each call.
func NewProjectConnection(project *projectconfig.LoadedProject, connectionName string, options ...Option) (Connection, error) {
	if project == nil {
		return Connection{}, fmt.Errorf("quickbooks connection requires the loaded project configuration")
	}
	reference := sdkgo.ConnectionRef{Provider: "quickbooks", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("quickbooks connection: %w", err)
	}
	key := projectconfig.ConnectionKey{ConnectorID: ConnectorID, ConnectionName: connectionName}
	var config Config
	if err := project.Configuration.DecodeConnectionConfiguration(key, &config); err != nil {
		return Connection{}, fmt.Errorf("quickbooks connection %q settings: %w", connectionName, err)
	}
	credentials, err := provider.NewRefreshingCredentialProvider(project.Connections, key, decodeCredentials, encodeCredentials)
	if err != nil {
		return Connection{}, err
	}
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		ClientID     string `json:"client_id"`
		ClientSecret string `json:"client_secret"`
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
		IDToken      string `json:"id_token"`
	}
	if err := projectconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		ClientID:     fields.ClientID,
		ClientSecret: sdkgo.NewSecretString(fields.ClientSecret),
		AccessToken:  sdkgo.NewSecretString(fields.AccessToken),
		RefreshToken: sdkgo.NewSecretString(fields.RefreshToken),
		IDToken:      sdkgo.NewSecretString(fields.IDToken),
	}
	return credentials, credentials.Validate()
}

func encodeCredentials(credentials Credentials) (json.RawMessage, error) {
	fields := struct {
		ClientID     string `json:"client_id,omitempty"`
		ClientSecret string `json:"client_secret,omitempty"`
		AccessToken  string `json:"access_token,omitempty"`
		RefreshToken string `json:"refresh_token,omitempty"`
		IDToken      string `json:"id_token,omitempty"`
	}{
		ClientID:     credentials.ClientID,
		ClientSecret: credentials.ClientSecret.Reveal(),
		AccessToken:  credentials.AccessToken.Reveal(),
		RefreshToken: credentials.RefreshToken.Reveal(),
		IDToken:      credentials.IDToken.Reveal(),
	}
	return json.Marshal(fields)
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("quickbooks connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("quickbooks connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("quickbooks connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("quickbooks connector connections cannot be serialized")
}
func (Connection) String() string   { return "quickbooks.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "quickbooks.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		Environment:      Environment("production"),
		MaxResponseBytes: 4194304,
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.Environment == "" {
		config.Environment = defaults.Environment
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	return config
}

func (config Config) Validate() error {
	switch config.Environment {
	case "", "production", "sandbox":
	default:
		return fmt.Errorf("configuration environment is invalid")
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	if credentials.ClientID == "" {
		return fmt.Errorf("credential client_id is required")
	}
	if credentials.ClientSecret.Reveal() == "" {
		return fmt.Errorf("credential client_secret is required")
	}
	if credentials.AccessToken.Reveal() == "" {
		return fmt.Errorf("credential access_token is required")
	}
	if credentials.RefreshToken.Reveal() == "" {
		return fmt.Errorf("credential refresh_token is required")
	}
	return nil
}

const FindCustomerBranchFound sdkgo.BranchID = "found"
const FindCustomerBranchNotFound sdkgo.BranchID = "notFound"
const FindCustomerBranchAmbiguous sdkgo.BranchID = "ambiguous"
const FindCustomerBranchProviderRejected sdkgo.BranchID = "providerRejected"
const FindCustomerBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const FindCustomerBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var FindCustomerDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "findCustomer"},
	Branches: []sdkgo.BranchDefinition{
		{ID: FindCustomerBranchFound, Description: "Exactly one customer matches."},
		{ID: FindCustomerBranchNotFound, Description: "No customer matches; inactive customers count only when the input includes them.", Optional: true},
		{ID: FindCustomerBranchAmbiguous, Description: "Several customers share the email address; the output lists them so the application can choose.", Optional: true},
		{ID: FindCustomerBranchProviderRejected, Description: "QuickBooks conclusively rejected the query, such as a revoked connection or a company the app can no longer reach.", Optional: true},
		{ID: FindCustomerBranchInvalidResponse, Description: "QuickBooks returned an invalid or oversized customer list.", Optional: true},
		{ID: FindCustomerBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type FindCustomerResult = sdkgo.QueryResult[FindCustomerOutput]

type FindCustomerStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                              `connector:"connectorId=quickbooks"`
	operationID                    struct{}                                              `connector:"operationId=findCustomer"`
	StepType                       string                                                `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                 `connector:"annotations"`
	Connection                     Connection                                            `connector:"connection"`
	ConnectionName                 string                                                `connector:"connectionName"`
	MapToOperationInput            func(IN) FindCustomerInput                            `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[FindCustomerResult]                      `connector:"branch=found"`
	NotFound                       sdkgo.Target[FindCustomerResult]                      `connector:"branch=notFound,optional"`
	Ambiguous                      sdkgo.Target[FindCustomerResult]                      `connector:"branch=ambiguous,optional"`
	ProviderRejected               sdkgo.Target[FindCustomerResult]                      `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[FindCustomerResult]                      `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[FindCustomerResult]                      `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[FindCustomerOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                      `connector:"stepOptionsOverride"`
}

func NewFindCustomerStep[IN any](config FindCustomerStepConfig[IN]) sdkgo.QueryStep[IN, FindCustomerInput, FindCustomerOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("quickbooks connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, FindCustomerInput, FindCustomerOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.FindCustomer(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[FindCustomerResult] {
			branches := make([]sdkgo.BranchTarget[FindCustomerResult], 0, 6)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(FindCustomerBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(FindCustomerBranchNotFound))
			}
			if config.Ambiguous.HasStep() {
				branches = append(branches, config.Ambiguous.BranchTarget(FindCustomerBranchAmbiguous))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(FindCustomerBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(FindCustomerBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(FindCustomerBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const CreateCustomerBranchCreated sdkgo.BranchID = "created"
const CreateCustomerBranchNameConflict sdkgo.BranchID = "nameConflict"
const CreateCustomerBranchProviderRejected sdkgo.BranchID = "providerRejected"
const CreateCustomerBranchUncertain sdkgo.BranchID = sdkgo.UncertainBranchID
const CreateCustomerBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var CreateCustomerDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "createCustomer"},
	Branches: []sdkgo.BranchDefinition{
		{ID: CreateCustomerBranchCreated, Description: "QuickBooks created the customer, or returned the customer this Step already created."},
		{ID: CreateCustomerBranchNameConflict, Description: "Another customer, vendor, or employee already uses the display name (QuickBooks error 6240); nothing was created, so resolve it with findCustomer by display name.", Optional: true},
		{ID: CreateCustomerBranchProviderRejected, Description: "QuickBooks conclusively rejected the customer, such as an invalid field or a revoked connection; nothing was created.", Optional: true},
		{ID: CreateCustomerBranchUncertain, Description: "QuickBooks accepted the request but returned an unusable customer; look it up with findCustomer before creating again.", Optional: true},
		{ID: CreateCustomerBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type CreateCustomerResult = sdkgo.MutationResult[CreateCustomerOutput]

type CreateCustomerStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                                   `connector:"connectorId=quickbooks"`
	operationID                       struct{}                                                   `connector:"operationId=createCustomer"`
	StepType                          string                                                     `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                      `connector:"annotations"`
	Connection                        Connection                                                 `connector:"connection"`
	ConnectionName                    string                                                     `connector:"connectionName"`
	MapToOperationInput               func(IN) CreateCustomerInput                               `connector:"mapToOperationInput"`
	Created                           sdkgo.Target[CreateCustomerResult]                         `connector:"branch=created"`
	NameConflict                      sdkgo.Target[CreateCustomerResult]                         `connector:"branch=nameConflict,optional"`
	ProviderRejected                  sdkgo.Target[CreateCustomerResult]                         `connector:"branch=providerRejected,optional"`
	Uncertain                         sdkgo.Target[CreateCustomerResult]                         `connector:"branch=uncertain,optional"`
	Defect                            sdkgo.Target[CreateCustomerResult]                         `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[CreateCustomerOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                           `connector:"stepOptionsOverride"`
}

func NewCreateCustomerStep[IN any](config CreateCustomerStepConfig[IN]) sdkgo.MutationStep[IN, CreateCustomerInput, CreateCustomerOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("quickbooks connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, CreateCustomerInput, CreateCustomerOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.CreateCustomer(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[CreateCustomerResult] {
			branches := make([]sdkgo.BranchTarget[CreateCustomerResult], 0, 5)
			if config.Created.HasStep() {
				branches = append(branches, config.Created.BranchTarget(CreateCustomerBranchCreated))
			}
			if config.NameConflict.HasStep() {
				branches = append(branches, config.NameConflict.BranchTarget(CreateCustomerBranchNameConflict))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(CreateCustomerBranchProviderRejected))
			}
			if config.Uncertain.HasStep() {
				branches = append(branches, config.Uncertain.BranchTarget(CreateCustomerBranchUncertain))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(CreateCustomerBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const CreateInvoiceBranchCreated sdkgo.BranchID = "created"
const CreateInvoiceBranchProviderRejected sdkgo.BranchID = "providerRejected"
const CreateInvoiceBranchUncertain sdkgo.BranchID = sdkgo.UncertainBranchID
const CreateInvoiceBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var CreateInvoiceDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "createInvoice"},
	Branches: []sdkgo.BranchDefinition{
		{ID: CreateInvoiceBranchCreated, Description: "QuickBooks created the invoice, or returned the invoice this Step already created, with its number, total, and balance."},
		{ID: CreateInvoiceBranchProviderRejected, Description: "QuickBooks conclusively rejected the invoice, such as an unknown or inactive customer or item, a duplicate document number, a closed period, or a revoked connection; nothing was created.", Optional: true},
		{ID: CreateInvoiceBranchUncertain, Description: "QuickBooks accepted the request but returned an unusable invoice; look it up by document number before creating again.", Optional: true},
		{ID: CreateInvoiceBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type CreateInvoiceResult = sdkgo.MutationResult[CreateInvoiceOutput]

type CreateInvoiceStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                                  `connector:"connectorId=quickbooks"`
	operationID                       struct{}                                                  `connector:"operationId=createInvoice"`
	StepType                          string                                                    `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                     `connector:"annotations"`
	Connection                        Connection                                                `connector:"connection"`
	ConnectionName                    string                                                    `connector:"connectionName"`
	MapToOperationInput               func(IN) CreateInvoiceInput                               `connector:"mapToOperationInput"`
	Created                           sdkgo.Target[CreateInvoiceResult]                         `connector:"branch=created"`
	ProviderRejected                  sdkgo.Target[CreateInvoiceResult]                         `connector:"branch=providerRejected,optional"`
	Uncertain                         sdkgo.Target[CreateInvoiceResult]                         `connector:"branch=uncertain,optional"`
	Defect                            sdkgo.Target[CreateInvoiceResult]                         `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[CreateInvoiceOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                          `connector:"stepOptionsOverride"`
}

func NewCreateInvoiceStep[IN any](config CreateInvoiceStepConfig[IN]) sdkgo.MutationStep[IN, CreateInvoiceInput, CreateInvoiceOutput] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("quickbooks connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, CreateInvoiceInput, CreateInvoiceOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.CreateInvoice(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[CreateInvoiceResult] {
			branches := make([]sdkgo.BranchTarget[CreateInvoiceResult], 0, 4)
			if config.Created.HasStep() {
				branches = append(branches, config.Created.BranchTarget(CreateInvoiceBranchCreated))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(CreateInvoiceBranchProviderRejected))
			}
			if config.Uncertain.HasStep() {
				branches = append(branches, config.Uncertain.BranchTarget(CreateInvoiceBranchUncertain))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(CreateInvoiceBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const GetInvoiceBranchFound sdkgo.BranchID = "found"
const GetInvoiceBranchNotFound sdkgo.BranchID = "notFound"
const GetInvoiceBranchProviderRejected sdkgo.BranchID = "providerRejected"
const GetInvoiceBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const GetInvoiceBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var GetInvoiceDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getInvoice"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetInvoiceBranchFound, Description: "The invoice was read."},
		{ID: GetInvoiceBranchNotFound, Description: "The invoice does not exist in the company or was deleted.", Optional: true},
		{ID: GetInvoiceBranchProviderRejected, Description: "QuickBooks conclusively rejected the read, such as a revoked connection.", Optional: true},
		{ID: GetInvoiceBranchInvalidResponse, Description: "QuickBooks returned an invalid or oversized invoice.", Optional: true},
		{ID: GetInvoiceBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type GetInvoiceResult = sdkgo.QueryResult[Invoice]

type GetInvoiceStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                   `connector:"connectorId=quickbooks"`
	operationID                    struct{}                                   `connector:"operationId=getInvoice"`
	StepType                       string                                     `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                      `connector:"annotations"`
	Connection                     Connection                                 `connector:"connection"`
	ConnectionName                 string                                     `connector:"connectionName"`
	MapToOperationInput            func(IN) GetInvoiceInput                   `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[GetInvoiceResult]             `connector:"branch=found"`
	NotFound                       sdkgo.Target[GetInvoiceResult]             `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[GetInvoiceResult]             `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[GetInvoiceResult]             `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[GetInvoiceResult]             `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[Invoice]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                           `connector:"stepOptionsOverride"`
}

func NewGetInvoiceStep[IN any](config GetInvoiceStepConfig[IN]) sdkgo.QueryStep[IN, GetInvoiceInput, Invoice] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("quickbooks connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetInvoiceInput, Invoice]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.GetInvoice(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[GetInvoiceResult] {
			branches := make([]sdkgo.BranchTarget[GetInvoiceResult], 0, 5)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(GetInvoiceBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(GetInvoiceBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(GetInvoiceBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(GetInvoiceBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(GetInvoiceBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const ListInvoicesBranchListed sdkgo.BranchID = "listed"
const ListInvoicesBranchProviderRejected sdkgo.BranchID = "providerRejected"
const ListInvoicesBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const ListInvoicesBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var ListInvoicesDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "listInvoices"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ListInvoicesBranchListed, Description: "One page of matching invoices was read; it can be empty."},
		{ID: ListInvoicesBranchProviderRejected, Description: "QuickBooks conclusively rejected the query, such as a revoked connection.", Optional: true},
		{ID: ListInvoicesBranchInvalidResponse, Description: "QuickBooks returned an invalid or oversized page of invoices.", Optional: true},
		{ID: ListInvoicesBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type ListInvoicesResult = sdkgo.QueryResult[InvoicePage]

type ListInvoicesStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                       `connector:"connectorId=quickbooks"`
	operationID                    struct{}                                       `connector:"operationId=listInvoices"`
	StepType                       string                                         `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                          `connector:"annotations"`
	Connection                     Connection                                     `connector:"connection"`
	ConnectionName                 string                                         `connector:"connectionName"`
	MapToOperationInput            func(IN) ListInvoicesInput                     `connector:"mapToOperationInput"`
	Listed                         sdkgo.Target[ListInvoicesResult]               `connector:"branch=listed"`
	ProviderRejected               sdkgo.Target[ListInvoicesResult]               `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[ListInvoicesResult]               `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[ListInvoicesResult]               `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[InvoicePage]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                               `connector:"stepOptionsOverride"`
}

func NewListInvoicesStep[IN any](config ListInvoicesStepConfig[IN]) sdkgo.QueryStep[IN, ListInvoicesInput, InvoicePage] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("quickbooks connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, ListInvoicesInput, InvoicePage]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.ListInvoices(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[ListInvoicesResult] {
			branches := make([]sdkgo.BranchTarget[ListInvoicesResult], 0, 4)
			if config.Listed.HasStep() {
				branches = append(branches, config.Listed.BranchTarget(ListInvoicesBranchListed))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(ListInvoicesBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(ListInvoicesBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(ListInvoicesBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const SendInvoiceBranchSent sdkgo.BranchID = "sent"
const SendInvoiceBranchProviderRejected sdkgo.BranchID = "providerRejected"
const SendInvoiceBranchUncertain sdkgo.BranchID = sdkgo.UncertainBranchID
const SendInvoiceBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var SendInvoiceDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "sendInvoice"},
	Branches: []sdkgo.BranchDefinition{
		{ID: SendInvoiceBranchSent, Description: "QuickBooks emailed the invoice, or returned the delivery this Step already made, with EmailStatus EmailSent."},
		{ID: SendInvoiceBranchProviderRejected, Description: "QuickBooks conclusively rejected the delivery, such as an invoice without an address, a deleted invoice, or a revoked connection; nothing was sent.", Optional: true},
		{ID: SendInvoiceBranchUncertain, Description: "QuickBooks accepted the request but returned an unusable invoice; read it back with getInvoice and check its EmailStatus before sending again.", Optional: true},
		{ID: SendInvoiceBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type SendInvoiceResult = sdkgo.MutationResult[Invoice]

type SendInvoiceStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                      `connector:"connectorId=quickbooks"`
	operationID                       struct{}                                      `connector:"operationId=sendInvoice"`
	StepType                          string                                        `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                         `connector:"annotations"`
	Connection                        Connection                                    `connector:"connection"`
	ConnectionName                    string                                        `connector:"connectionName"`
	MapToOperationInput               func(IN) SendInvoiceInput                     `connector:"mapToOperationInput"`
	Sent                              sdkgo.Target[SendInvoiceResult]               `connector:"branch=sent"`
	ProviderRejected                  sdkgo.Target[SendInvoiceResult]               `connector:"branch=providerRejected,optional"`
	Uncertain                         sdkgo.Target[SendInvoiceResult]               `connector:"branch=uncertain,optional"`
	Defect                            sdkgo.Target[SendInvoiceResult]               `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[Invoice]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                              `connector:"stepOptionsOverride"`
}

func NewSendInvoiceStep[IN any](config SendInvoiceStepConfig[IN]) sdkgo.MutationStep[IN, SendInvoiceInput, Invoice] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("quickbooks connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, SendInvoiceInput, Invoice]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.SendInvoice(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[SendInvoiceResult] {
			branches := make([]sdkgo.BranchTarget[SendInvoiceResult], 0, 4)
			if config.Sent.HasStep() {
				branches = append(branches, config.Sent.BranchTarget(SendInvoiceBranchSent))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(SendInvoiceBranchProviderRejected))
			}
			if config.Uncertain.HasStep() {
				branches = append(branches, config.Uncertain.BranchTarget(SendInvoiceBranchUncertain))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(SendInvoiceBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const RecordPaymentBranchRecorded sdkgo.BranchID = "recorded"
const RecordPaymentBranchProviderRejected sdkgo.BranchID = "providerRejected"
const RecordPaymentBranchUncertain sdkgo.BranchID = sdkgo.UncertainBranchID
const RecordPaymentBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var RecordPaymentDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "recordPayment"},
	Branches: []sdkgo.BranchDefinition{
		{ID: RecordPaymentBranchRecorded, Description: "QuickBooks recorded the payment, or returned the payment this Step already recorded, with the invoices it applies to."},
		{ID: RecordPaymentBranchProviderRejected, Description: "QuickBooks conclusively rejected the payment, such as an invoice of another customer, an amount above the balance, an invalid deposit account, a closed period, or a revoked connection; nothing was recorded.", Optional: true},
		{ID: RecordPaymentBranchUncertain, Description: "QuickBooks accepted the request but returned an unusable payment; read the invoice back before paying again.", Optional: true},
		{ID: RecordPaymentBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type RecordPaymentResult = sdkgo.MutationResult[Payment]

type RecordPaymentStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                      `connector:"connectorId=quickbooks"`
	operationID                       struct{}                                      `connector:"operationId=recordPayment"`
	StepType                          string                                        `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                         `connector:"annotations"`
	Connection                        Connection                                    `connector:"connection"`
	ConnectionName                    string                                        `connector:"connectionName"`
	MapToOperationInput               func(IN) RecordPaymentInput                   `connector:"mapToOperationInput"`
	Recorded                          sdkgo.Target[RecordPaymentResult]             `connector:"branch=recorded"`
	ProviderRejected                  sdkgo.Target[RecordPaymentResult]             `connector:"branch=providerRejected,optional"`
	Uncertain                         sdkgo.Target[RecordPaymentResult]             `connector:"branch=uncertain,optional"`
	Defect                            sdkgo.Target[RecordPaymentResult]             `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[Payment]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                              `connector:"stepOptionsOverride"`
}

func NewRecordPaymentStep[IN any](config RecordPaymentStepConfig[IN]) sdkgo.MutationStep[IN, RecordPaymentInput, Payment] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("quickbooks connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, RecordPaymentInput, Payment]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.RecordPayment(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[RecordPaymentResult] {
			branches := make([]sdkgo.BranchTarget[RecordPaymentResult], 0, 4)
			if config.Recorded.HasStep() {
				branches = append(branches, config.Recorded.BranchTarget(RecordPaymentBranchRecorded))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(RecordPaymentBranchProviderRejected))
			}
			if config.Uncertain.HasStep() {
				branches = append(branches, config.Uncertain.BranchTarget(RecordPaymentBranchUncertain))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(RecordPaymentBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
