// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package openai

import (
	"fmt"
	"net/url"
	"time"

	connector "github.com/superdurable/dex-connectors-library/sdk/go"
	"github.com/superdurable/dex/sdk-go/dex"
)

const (
	ConnectorID      = "openai"
	ConnectorVersion = "v0.1.0-alpha.1"
)

type Config struct {
	Endpoint         string `json:"endpoint,omitempty" yaml:"endpoint,omitempty"`
	MaxResponseBytes int64  `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
	MaxSSEEventBytes int64  `json:"maxSseEventBytes,omitempty" yaml:"maxSseEventBytes,omitempty"`
}

type Credentials struct {
	APIKey connector.SecretString
}

func DefaultConfig() Config {
	return Config{
		Endpoint:         "https://api.openai.com/v1",
		MaxResponseBytes: 8388608,
		MaxSSEEventBytes: 1048576,
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.Endpoint == "" {
		config.Endpoint = defaults.Endpoint
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	if config.MaxSSEEventBytes == 0 {
		config.MaxSSEEventBytes = defaults.MaxSSEEventBytes
	}
	return config
}

func (config Config) Validate() error {
	if config.Endpoint != "" {
		parsed, err := url.Parse(config.Endpoint)
		if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
			return fmt.Errorf("configuration endpoint must be an absolute URL")
		}
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	if config.MaxSSEEventBytes < 0 {
		return fmt.Errorf("configuration maxSseEventBytes cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	if credentials.APIKey.Reveal() == "" {
		return fmt.Errorf("credential api_key is required")
	}
	return nil
}

const CreateResponseBranchCompleted connector.BranchID = "completed"
const CreateResponseBranchFailed connector.BranchID = "failed"
const CreateResponseBranchUncertain connector.BranchID = "uncertain"
const CreateResponseBranchDefect connector.BranchID = "defect"

var CreateResponseDefinition = connector.MutationDefinition{
	Operation: connector.OperationRef{ConnectorID: ConnectorID, OperationID: "createResponse"},
	Branches: []connector.BranchDefinition{
		{ID: CreateResponseBranchCompleted, Description: "OpenAI completed the response."},
		{ID: CreateResponseBranchFailed, Description: "OpenAI returned a terminal failed or incomplete response."},
		{ID: CreateResponseBranchUncertain, Description: "The dispatched response outcome cannot be confirmed."},
		{ID: CreateResponseBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch:    CreateResponseBranchDefect,
	UncertainBranch: CreateResponseBranchUncertain,
	StepDefaults: connector.StepDefaults{
		ExecuteMethodTimeout: time.Duration(150000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(2000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: connector.RequirementRequired,
	Progress:        connector.ProgressCapabilities{Structured: true, Text: true},
}

const RetrieveResponseBranchFound connector.BranchID = "found"
const RetrieveResponseBranchFailed connector.BranchID = "failed"
const RetrieveResponseBranchDefect connector.BranchID = "defect"

var RetrieveResponseDefinition = connector.QueryDefinition{
	Operation: connector.OperationRef{ConnectorID: ConnectorID, OperationID: "retrieveResponse"},
	Branches: []connector.BranchDefinition{
		{ID: RetrieveResponseBranchFound, Description: "The response exists and was returned."},
		{ID: RetrieveResponseBranchFailed, Description: "OpenAI returned a terminal query failure."},
		{ID: RetrieveResponseBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch: RetrieveResponseBranchDefect,
	StepDefaults: connector.StepDefaults{
		ExecuteMethodTimeout: time.Duration(150000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(2000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: connector.RequirementOptional,
	Progress:        connector.ProgressCapabilities{Structured: false, Text: false},
}
