// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package httpconnector

import (
	"fmt"
	"net/url"
	"time"

	connector "github.com/superdurable/dex-connectors-library/sdk/go"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "http"

type Config struct {
	BaseURL           string            `json:"baseUrl,omitempty" yaml:"baseUrl,omitempty"`
	AllowedHosts      []string          `json:"allowedHosts,omitempty" yaml:"allowedHosts,omitempty"`
	Timeout           time.Duration     `json:"timeout,omitempty" yaml:"timeout,omitempty"`
	MaxResponseBytes  int64             `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
	CredentialHeaders map[string]string `json:"credentialHeaders,omitempty" yaml:"credentialHeaders,omitempty"`
	IdempotencyHeader string            `json:"idempotencyHeader,omitempty" yaml:"idempotencyHeader,omitempty"`
}

type Credentials struct {
	APIKey        connector.SecretString
	WebhookSecret connector.SecretString
}

type Connection struct {
	client    *Client
	reference connector.ConnectionRef
}

func NewConnection(client *Client, reference connector.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("http connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("http connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("http connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("http connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("http connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("http connector connections cannot be serialized")
}
func (Connection) String() string   { return "httpconnector.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "httpconnector.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		Timeout:           time.Duration(15000000000),
		MaxResponseBytes:  2097152,
		IdempotencyHeader: "Idempotency-Key",
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.Timeout == 0 {
		config.Timeout = defaults.Timeout
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	if config.IdempotencyHeader == "" {
		config.IdempotencyHeader = defaults.IdempotencyHeader
	}
	return config
}

func (config Config) Validate() error {
	if config.BaseURL == "" {
		return fmt.Errorf("configuration baseUrl is required")
	}
	if config.BaseURL != "" {
		parsed, err := url.Parse(config.BaseURL)
		if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
			return fmt.Errorf("configuration baseUrl must be an absolute URL")
		}
	}
	if config.Timeout < 0 {
		return fmt.Errorf("configuration timeout cannot be negative")
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	return nil
}

const QueryBranchSucceeded connector.BranchID = "succeeded"
const QueryBranchFailed connector.BranchID = "failed"
const QueryBranchDefect connector.BranchID = "defect"

var QueryDefinition = connector.QueryDefinition{
	Operation: connector.OperationRef{ConnectorID: ConnectorID, OperationID: "query"},
	Branches: []connector.BranchDefinition{
		{ID: QueryBranchSucceeded, Description: "The provider returned a successful response."},
		{ID: QueryBranchFailed, Description: "The provider rejected the query or returned a terminal response."},
		{ID: QueryBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch: QueryBranchDefect,
	StepDefaults: connector.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: connector.RequirementOptional,
	Progress:        connector.ProgressCapabilities{Structured: false, Text: false},
}

type QueryStepOutput[IN any] = connector.QueryStepOutput[IN, Response]

type QueryStepConfig[IN any] struct {
	connector.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                        struct{}                                        `connector:"connectorId=http"`
	operationID                        struct{}                                        `connector:"operationId=query"`
	StepType                           string                                          `connector:"stepType"`
	Presentation                       connector.StepPresentation                      `connector:"presentation"`
	Connection                         Connection                                      `connector:"connection"`
	BuildInput                         func(IN) (Request, error)                       `connector:"buildInput"`
	Succeeded                          connector.Target[QueryStepOutput[IN]]           `connector:"branch=succeeded"`
	Failed                             connector.Target[QueryStepOutput[IN]]           `connector:"branch=failed"`
	Defect                             connector.Target[QueryStepOutput[IN]]           `connector:"branch=defect"`
	ResultAttribute                    *dex.Attribute[connector.QueryResult[Response]] `connector:"resultAttribute"`
	StepOptionsOverride                *dex.StepOptions                                `connector:"stepOptionsOverride"`
}

func NewQueryStep[IN any](config QueryStepConfig[IN]) connector.QueryStep[IN, Request, Response] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	return connector.MustNewQueryStep(connector.QueryStepConfig[IN, Request, Response]{
		StepType: config.StepType, Presentation: config.Presentation,
		Operation: config.Connection.client.Query(), Connection: config.Connection.reference,
		BuildInput: config.BuildInput,
		Branches: []connector.BranchTarget[QueryStepOutput[IN]]{
			config.Succeeded.BranchTarget(QueryBranchSucceeded),
			config.Failed.BranchTarget(QueryBranchFailed),
			config.Defect.BranchTarget(QueryBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const MutationBranchSucceeded connector.BranchID = "succeeded"
const MutationBranchRejected connector.BranchID = "rejected"
const MutationBranchUncertain connector.BranchID = "uncertain"
const MutationBranchDefect connector.BranchID = "defect"

var MutationDefinition = connector.MutationDefinition{
	Operation: connector.OperationRef{ConnectorID: ConnectorID, OperationID: "mutation"},
	Branches: []connector.BranchDefinition{
		{ID: MutationBranchSucceeded, Description: "The provider confirmed the mutation."},
		{ID: MutationBranchRejected, Description: "The provider definitely rejected the mutation."},
		{ID: MutationBranchUncertain, Description: "The provider outcome cannot be confirmed."},
		{ID: MutationBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch:    MutationBranchDefect,
	UncertainBranch: MutationBranchUncertain,
	StepDefaults: connector.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: connector.RequirementRequired,
	Progress:        connector.ProgressCapabilities{Structured: false, Text: false},
}

type MutationStepOutput[IN any] = connector.MutationStepOutput[IN, Response]

type MutationStepConfig[IN any] struct {
	connector.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                           struct{}                                           `connector:"connectorId=http"`
	operationID                           struct{}                                           `connector:"operationId=mutation"`
	StepType                              string                                             `connector:"stepType"`
	Presentation                          connector.StepPresentation                         `connector:"presentation"`
	Connection                            Connection                                         `connector:"connection"`
	BuildInput                            func(IN) (Request, error)                          `connector:"buildInput"`
	Succeeded                             connector.Target[MutationStepOutput[IN]]           `connector:"branch=succeeded"`
	Rejected                              connector.Target[MutationStepOutput[IN]]           `connector:"branch=rejected"`
	Uncertain                             connector.Target[MutationStepOutput[IN]]           `connector:"branch=uncertain"`
	Defect                                connector.Target[MutationStepOutput[IN]]           `connector:"branch=defect"`
	ResultAttribute                       *dex.Attribute[connector.MutationResult[Response]] `connector:"resultAttribute"`
	StepOptionsOverride                   *dex.StepOptions                                   `connector:"stepOptionsOverride"`
}

func NewMutationStep[IN any](config MutationStepConfig[IN]) connector.MutationStep[IN, Request, Response] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	return connector.MustNewMutationStep(connector.MutationStepConfig[IN, Request, Response]{
		StepType: config.StepType, Presentation: config.Presentation,
		Operation: config.Connection.client.Mutation(), Connection: config.Connection.reference,
		BuildInput: config.BuildInput,
		Branches: []connector.BranchTarget[MutationStepOutput[IN]]{
			config.Succeeded.BranchTarget(MutationBranchSucceeded),
			config.Rejected.BranchTarget(MutationBranchRejected),
			config.Uncertain.BranchTarget(MutationBranchUncertain),
			config.Defect.BranchTarget(MutationBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const VerifyWebhookBranchVerified connector.BranchID = "verified"
const VerifyWebhookBranchRejected connector.BranchID = "rejected"
const VerifyWebhookBranchDefect connector.BranchID = "defect"

var VerifyWebhookDefinition = connector.QueryDefinition{
	Operation: connector.OperationRef{ConnectorID: ConnectorID, OperationID: "verifyWebhook"},
	Branches: []connector.BranchDefinition{
		{ID: VerifyWebhookBranchVerified, Description: "The webhook signature and replay checks passed."},
		{ID: VerifyWebhookBranchRejected, Description: "The webhook could not be verified."},
		{ID: VerifyWebhookBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch: VerifyWebhookBranchDefect,
	StepDefaults: connector.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: connector.RequirementNone,
	Progress:        connector.ProgressCapabilities{Structured: false, Text: false},
}

type VerifyWebhookStepOutput[IN any] = connector.QueryStepOutput[IN, WebhookResult]

type VerifyWebhookStepConfig[IN any] struct {
	connector.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                        struct{}                                      `connector:"connectorId=http"`
	operationID                        struct{}                                      `connector:"operationId=verifyWebhook"`
	StepType                           string                                        `connector:"stepType"`
	Presentation                       connector.StepPresentation                    `connector:"presentation"`
	Connection                         Connection                                    `connector:"connection"`
	BuildInput                         func(IN) (WebhookRequest, error)              `connector:"buildInput"`
	Verified                           connector.Target[VerifyWebhookStepOutput[IN]] `connector:"branch=verified"`
	Rejected                           connector.Target[VerifyWebhookStepOutput[IN]] `connector:"branch=rejected"`
	Defect                             connector.Target[VerifyWebhookStepOutput[IN]] `connector:"branch=defect"`
	StepOptionsOverride                *dex.StepOptions                              `connector:"stepOptionsOverride"`
}

func NewVerifyWebhookStep[IN any](config VerifyWebhookStepConfig[IN]) connector.QueryStep[IN, WebhookRequest, WebhookResult] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	return connector.MustNewQueryStep(connector.QueryStepConfig[IN, WebhookRequest, WebhookResult]{
		StepType: config.StepType, Presentation: config.Presentation,
		Operation: config.Connection.client.VerifyWebhook(), Connection: config.Connection.reference,
		BuildInput: config.BuildInput,
		Branches: []connector.BranchTarget[VerifyWebhookStepOutput[IN]]{
			config.Verified.BranchTarget(VerifyWebhookBranchVerified),
			config.Rejected.BranchTarget(VerifyWebhookBranchRejected),
			config.Defect.BranchTarget(VerifyWebhookBranchDefect),
		},
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
