// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package httpconnector

import (
	"encoding/json"
	"fmt"
	"net/url"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/localconfig"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "http"

type Config struct {
	BaseURL           string            `json:"baseUrl,omitempty" yaml:"baseUrl,omitempty"`
	AllowedHosts      []string          `json:"allowedHosts,omitempty" yaml:"allowedHosts,omitempty"`
	Timeout           time.Duration     `json:"timeout,omitempty" yaml:"timeout,omitempty"`
	MaxResponseBytes  int64             `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
	CredentialHeaders map[string]string `json:"credentialHeaders,omitempty" yaml:"credentialHeaders,omitempty"`
	IdempotencyHeader string            `json:"idempotencyHeader,omitempty" yaml:"idempotencyHeader,omitempty"`
}

type Credentials struct {
	APIKey        sdkgo.SecretString
	WebhookSecret sdkgo.SecretString
}

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("http connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("http connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewLocalConnection loads startup configuration and reloads credentials before every provider call.
func NewLocalConnection(store *localconfig.Store, connectionName string, options ...Option) (Connection, error) {
	if store == nil {
		return Connection{}, fmt.Errorf("local connector configuration store is required")
	}
	reference := sdkgo.ConnectionRef{Provider: "http", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("http local connection: %w", err)
	}
	var config Config
	if err := store.DecodeConfiguration(ConnectorID, connectionName, &config); err != nil {
		return Connection{}, err
	}
	credentials := localconfig.NewCredentialProvider(store, ConnectorID, connectionName, decodeLocalCredentials)
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeLocalCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		APIKey        string `json:"api_key"`
		WebhookSecret string `json:"webhook_secret"`
	}
	if err := localconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		APIKey:        sdkgo.NewSecretString(fields.APIKey),
		WebhookSecret: sdkgo.NewSecretString(fields.WebhookSecret),
	}
	return credentials, credentials.Validate()
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("http connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("http connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("http connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("http connector connections cannot be serialized")
}
func (Connection) String() string   { return "httpconnector.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "httpconnector.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		Timeout:           time.Duration(15000000000),
		MaxResponseBytes:  2097152,
		IdempotencyHeader: "Idempotency-Key",
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.Timeout == 0 {
		config.Timeout = defaults.Timeout
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	if config.IdempotencyHeader == "" {
		config.IdempotencyHeader = defaults.IdempotencyHeader
	}
	return config
}

func (config Config) Validate() error {
	if config.BaseURL == "" {
		return fmt.Errorf("configuration baseUrl is required")
	}
	if config.BaseURL != "" {
		parsed, err := url.Parse(config.BaseURL)
		if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
			return fmt.Errorf("configuration baseUrl must be an absolute URL")
		}
	}
	if config.Timeout < 0 {
		return fmt.Errorf("configuration timeout cannot be negative")
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	return nil
}

const QueryBranchSucceeded sdkgo.BranchID = "succeeded"
const QueryBranchFailed sdkgo.BranchID = "failed"
const QueryBranchDefect sdkgo.BranchID = "defect"

var QueryDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "query"},
	Branches: []sdkgo.BranchDefinition{
		{ID: QueryBranchSucceeded, Description: "The provider returned a successful response."},
		{ID: QueryBranchFailed, Description: "The provider rejected the query or returned a terminal response."},
		{ID: QueryBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch: QueryBranchDefect,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementOptional,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type QueryStepOutput[IN any] = sdkgo.QueryStepOutput[IN, Response]

type QueryStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                    `connector:"connectorId=http"`
	operationID                    struct{}                                    `connector:"operationId=query"`
	StepType                       string                                      `connector:"stepType"`
	Presentation                   sdkgo.StepPresentation                      `connector:"presentation"`
	Connection                     Connection                                  `connector:"connection"`
	ConnectionName                 string                                      `connector:"connectionName"`
	BuildInput                     func(IN) (Request, error)                   `connector:"buildInput"`
	Succeeded                      sdkgo.Target[QueryStepOutput[IN]]           `connector:"branch=succeeded"`
	Failed                         sdkgo.Target[QueryStepOutput[IN]]           `connector:"branch=failed"`
	Defect                         sdkgo.Target[QueryStepOutput[IN]]           `connector:"branch=defect"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[Response]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                            `connector:"stepOptionsOverride"`
}

func NewQueryStep[IN any](config QueryStepConfig[IN]) sdkgo.QueryStep[IN, Request, Response] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("http connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, Request, Response]{
		StepType: config.StepType, Presentation: config.Presentation,
		Operation: config.Connection.client.Query(), Connection: config.Connection.reference,
		BuildInput: config.BuildInput,
		Branches: []sdkgo.BranchTarget[QueryStepOutput[IN]]{
			config.Succeeded.BranchTarget(QueryBranchSucceeded),
			config.Failed.BranchTarget(QueryBranchFailed),
			config.Defect.BranchTarget(QueryBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const MutationBranchSucceeded sdkgo.BranchID = "succeeded"
const MutationBranchRejected sdkgo.BranchID = "rejected"
const MutationBranchUncertain sdkgo.BranchID = "uncertain"
const MutationBranchDefect sdkgo.BranchID = "defect"

var MutationDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "mutation"},
	Branches: []sdkgo.BranchDefinition{
		{ID: MutationBranchSucceeded, Description: "The provider confirmed the mutation."},
		{ID: MutationBranchRejected, Description: "The provider definitely rejected the mutation."},
		{ID: MutationBranchUncertain, Description: "The provider outcome cannot be confirmed."},
		{ID: MutationBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch:    MutationBranchDefect,
	UncertainBranch: MutationBranchUncertain,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementRequired,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type MutationStepOutput[IN any] = sdkgo.MutationStepOutput[IN, Response]

type MutationStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                       `connector:"connectorId=http"`
	operationID                       struct{}                                       `connector:"operationId=mutation"`
	StepType                          string                                         `connector:"stepType"`
	Presentation                      sdkgo.StepPresentation                         `connector:"presentation"`
	Connection                        Connection                                     `connector:"connection"`
	ConnectionName                    string                                         `connector:"connectionName"`
	BuildInput                        func(IN) (Request, error)                      `connector:"buildInput"`
	Succeeded                         sdkgo.Target[MutationStepOutput[IN]]           `connector:"branch=succeeded"`
	Rejected                          sdkgo.Target[MutationStepOutput[IN]]           `connector:"branch=rejected"`
	Uncertain                         sdkgo.Target[MutationStepOutput[IN]]           `connector:"branch=uncertain"`
	Defect                            sdkgo.Target[MutationStepOutput[IN]]           `connector:"branch=defect"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[Response]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                               `connector:"stepOptionsOverride"`
}

func NewMutationStep[IN any](config MutationStepConfig[IN]) sdkgo.MutationStep[IN, Request, Response] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("http connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, Request, Response]{
		StepType: config.StepType, Presentation: config.Presentation,
		Operation: config.Connection.client.Mutation(), Connection: config.Connection.reference,
		BuildInput: config.BuildInput,
		Branches: []sdkgo.BranchTarget[MutationStepOutput[IN]]{
			config.Succeeded.BranchTarget(MutationBranchSucceeded),
			config.Rejected.BranchTarget(MutationBranchRejected),
			config.Uncertain.BranchTarget(MutationBranchUncertain),
			config.Defect.BranchTarget(MutationBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const VerifyWebhookBranchVerified sdkgo.BranchID = "verified"
const VerifyWebhookBranchRejected sdkgo.BranchID = "rejected"
const VerifyWebhookBranchDefect sdkgo.BranchID = "defect"

var VerifyWebhookDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "verifyWebhook"},
	Branches: []sdkgo.BranchDefinition{
		{ID: VerifyWebhookBranchVerified, Description: "The webhook signature and replay checks passed."},
		{ID: VerifyWebhookBranchRejected, Description: "The webhook could not be verified."},
		{ID: VerifyWebhookBranchDefect, Description: "Local input or connector definition is invalid."},
	},
	DefectBranch: VerifyWebhookBranchDefect,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementNone,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type VerifyWebhookStepOutput[IN any] = sdkgo.QueryStepOutput[IN, WebhookResult]

type VerifyWebhookStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                  `connector:"connectorId=http"`
	operationID                    struct{}                                  `connector:"operationId=verifyWebhook"`
	StepType                       string                                    `connector:"stepType"`
	Presentation                   sdkgo.StepPresentation                    `connector:"presentation"`
	Connection                     Connection                                `connector:"connection"`
	ConnectionName                 string                                    `connector:"connectionName"`
	BuildInput                     func(IN) (WebhookRequest, error)          `connector:"buildInput"`
	Verified                       sdkgo.Target[VerifyWebhookStepOutput[IN]] `connector:"branch=verified"`
	Rejected                       sdkgo.Target[VerifyWebhookStepOutput[IN]] `connector:"branch=rejected"`
	Defect                         sdkgo.Target[VerifyWebhookStepOutput[IN]] `connector:"branch=defect"`
	StepOptionsOverride            *dex.StepOptions                          `connector:"stepOptionsOverride"`
}

func NewVerifyWebhookStep[IN any](config VerifyWebhookStepConfig[IN]) sdkgo.QueryStep[IN, WebhookRequest, WebhookResult] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("http connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, WebhookRequest, WebhookResult]{
		StepType: config.StepType, Presentation: config.Presentation,
		Operation: config.Connection.client.VerifyWebhook(), Connection: config.Connection.reference,
		BuildInput: config.BuildInput,
		Branches: []sdkgo.BranchTarget[VerifyWebhookStepOutput[IN]]{
			config.Verified.BranchTarget(VerifyWebhookBranchVerified),
			config.Rejected.BranchTarget(VerifyWebhookBranchRejected),
			config.Defect.BranchTarget(VerifyWebhookBranchDefect),
		},
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
