// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package hackernews

import (
	"encoding/json"
	"fmt"
	"net/url"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig/provider"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "hacker-news-daily"

type Config struct {
	BaseURL          string        `json:"baseUrl,omitempty" yaml:"baseUrl,omitempty"`
	Timeout          time.Duration `json:"timeout,omitempty" yaml:"timeout,omitempty"`
	MaxResponseBytes int64         `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
}

type Credentials struct {
}

// CredentialSource is the credential provider New requires: this connector never refreshes its credentials.
type CredentialSource = sdkgo.CredentialProvider[Credentials]

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

// NewConnection wraps a client built with New, such as a test client with a static credential provider.
// Applications open declared connections with NewProjectConnection instead.
func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("hacker-news-daily connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("hacker-news-daily connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewProjectConnection opens the connection that dex-app.yaml declares as connectionName from the
// loaded project configuration. It reads ordinary settings now and resolves credentials during each call.
func NewProjectConnection(project *projectconfig.LoadedProject, connectionName string, options ...Option) (Connection, error) {
	if project == nil {
		return Connection{}, fmt.Errorf("hacker-news-daily connection requires the loaded project configuration")
	}
	reference := sdkgo.ConnectionRef{Provider: "hacker-news", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("hacker-news-daily connection: %w", err)
	}
	key := projectconfig.ConnectionKey{ConnectorID: ConnectorID, ConnectionName: connectionName}
	var config Config
	if err := project.Configuration.DecodeConnectionConfiguration(key, &config); err != nil {
		return Connection{}, fmt.Errorf("hacker-news-daily connection %q settings: %w", connectionName, err)
	}
	credentials, err := provider.NewCredentialProvider(project.Connections, key, decodeCredentials)
	if err != nil {
		return Connection{}, err
	}
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
	}
	if err := projectconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{}
	return credentials, credentials.Validate()
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("hacker-news-daily connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("hacker-news-daily connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("hacker-news-daily connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("hacker-news-daily connector connections cannot be serialized")
}
func (Connection) String() string   { return "hackernews.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "hackernews.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		BaseURL:          "https://hacker-news.firebaseio.com/v0",
		Timeout:          time.Duration(15000000000),
		MaxResponseBytes: 1048576,
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.BaseURL == "" {
		config.BaseURL = defaults.BaseURL
	}
	if config.Timeout == 0 {
		config.Timeout = defaults.Timeout
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	return config
}

func (config Config) Validate() error {
	if config.BaseURL != "" {
		parsed, err := url.Parse(config.BaseURL)
		if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
			return fmt.Errorf("configuration baseUrl must be an absolute URL")
		}
	}
	if config.Timeout < 0 {
		return fmt.Errorf("configuration timeout cannot be negative")
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	return nil
}

const ListStoryIDsBranchListed sdkgo.BranchID = "listed"
const ListStoryIDsBranchProviderRejected sdkgo.BranchID = "providerRejected"
const ListStoryIDsBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const ListStoryIDsBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var ListStoryIDsDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "listStoryIDs"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ListStoryIDsBranchListed, Description: "The feed snapshot was read."},
		{ID: ListStoryIDsBranchProviderRejected, Description: "Hacker News rejected the request.", Optional: true},
		{ID: ListStoryIDsBranchInvalidResponse, Description: "Hacker News returned malformed or oversized data.", Optional: true},
		{ID: ListStoryIDsBranchDefect, Description: "Local input or connection configuration is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(3900000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type ListStoryIDsResult = sdkgo.QueryResult[StoryIDs]

type ListStoryIDsStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                    `connector:"connectorId=hacker-news-daily"`
	operationID                    struct{}                                    `connector:"operationId=listStoryIDs"`
	StepType                       string                                      `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                       `connector:"annotations"`
	Connection                     Connection                                  `connector:"connection"`
	ConnectionName                 string                                      `connector:"connectionName"`
	MapToOperationInput            func(IN) ListStoryIDsInput                  `connector:"mapToOperationInput"`
	Listed                         sdkgo.Target[ListStoryIDsResult]            `connector:"branch=listed"`
	ProviderRejected               sdkgo.Target[ListStoryIDsResult]            `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[ListStoryIDsResult]            `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[ListStoryIDsResult]            `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[StoryIDs]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                            `connector:"stepOptionsOverride"`
}

func NewListStoryIDsStep[IN any](config ListStoryIDsStepConfig[IN]) sdkgo.QueryStep[IN, ListStoryIDsInput, StoryIDs] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("hacker-news-daily connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, ListStoryIDsInput, StoryIDs]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.ListStoryIDs(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[ListStoryIDsResult] {
			branches := make([]sdkgo.BranchTarget[ListStoryIDsResult], 0, 4)
			if config.Listed.HasStep() {
				branches = append(branches, config.Listed.BranchTarget(ListStoryIDsBranchListed))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(ListStoryIDsBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(ListStoryIDsBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(ListStoryIDsBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const GetItemBranchFound sdkgo.BranchID = "found"
const GetItemBranchNotFound sdkgo.BranchID = "notFound"
const GetItemBranchProviderRejected sdkgo.BranchID = "providerRejected"
const GetItemBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const GetItemBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var GetItemDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getItem"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetItemBranchFound, Description: "The public item was read."},
		{ID: GetItemBranchNotFound, Description: "The item is missing, deleted, or dead.", Optional: true},
		{ID: GetItemBranchProviderRejected, Description: "Hacker News rejected the request.", Optional: true},
		{ID: GetItemBranchInvalidResponse, Description: "Hacker News returned malformed or oversized data.", Optional: true},
		{ID: GetItemBranchDefect, Description: "Local input or connection configuration is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(3900000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type GetItemResult = sdkgo.QueryResult[Item]

type GetItemStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                `connector:"connectorId=hacker-news-daily"`
	operationID                    struct{}                                `connector:"operationId=getItem"`
	StepType                       string                                  `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                   `connector:"annotations"`
	Connection                     Connection                              `connector:"connection"`
	ConnectionName                 string                                  `connector:"connectionName"`
	MapToOperationInput            func(IN) GetItemInput                   `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[GetItemResult]             `connector:"branch=found"`
	NotFound                       sdkgo.Target[GetItemResult]             `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[GetItemResult]             `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[GetItemResult]             `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[GetItemResult]             `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[Item]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                        `connector:"stepOptionsOverride"`
}

func NewGetItemStep[IN any](config GetItemStepConfig[IN]) sdkgo.QueryStep[IN, GetItemInput, Item] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("hacker-news-daily connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetItemInput, Item]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.GetItem(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[GetItemResult] {
			branches := make([]sdkgo.BranchTarget[GetItemResult], 0, 5)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(GetItemBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(GetItemBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(GetItemBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(GetItemBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(GetItemBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
