// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package linear

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig"
	"github.com/superdurable/dex-connectors-library/sdkgo/projectconfig/provider"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "linear"

const (
	UIUnitTeamPicker         = "teamPicker"
	UITeamPickerPortTeamID   = "teamId"
	UITeamPickerPortTeamKey  = "teamKey"
	UITeamPickerPortTeamName = "teamName"
)

type Config struct {
	MaxResponseBytes          int64         `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
	WebhookMaxBodyBytes       int64         `json:"webhookMaxBodyBytes,omitempty" yaml:"webhookMaxBodyBytes,omitempty"`
	WebhookSignatureTolerance time.Duration `json:"webhookSignatureTolerance,omitempty" yaml:"webhookSignatureTolerance,omitempty"`
}

type Credentials struct {
	AuthMethodID         string
	APIKey               sdkgo.SecretString
	WebhookSigningSecret sdkgo.SecretString
	OAuthClientID        string
	OAuthClientSecret    sdkgo.SecretString
	AccessToken          sdkgo.SecretString
	RefreshToken         sdkgo.SecretString
}

// CredentialSource is the credential provider New requires: this connector refreshes its credentials.
type CredentialSource = sdkgo.RefreshingCredentialProvider[Credentials]

type Connection struct {
	client     *Client
	operations Operations
	reference  sdkgo.ConnectionRef
}

// Operations returns the operations that this connector's Step factories invoke, one accessor per operation.
// NewConnection uses the client's operations; NewConnectionWithOperations accepts another implementation.
type Operations interface {
	SearchIssues() sdkgo.Query[SearchIssuesInput, SearchIssuesOutput]
	GetIssue() sdkgo.Query[GetIssueInput, Issue]
	CreateIssue() sdkgo.Mutation[CreateIssueInput, CreateIssueOutput]
	UpdateIssue() sdkgo.Mutation[UpdateIssueInput, UpdateIssueOutput]
	AddComment() sdkgo.Mutation[AddCommentInput, AddCommentOutput]
	FindUserByEmail() sdkgo.Query[FindUserByEmailInput, User]
	ListWorkflowStates() sdkgo.Query[ListWorkflowStatesInput, ListWorkflowStatesOutput]
}

type clientOperations struct{ client *Client }

func (operations clientOperations) SearchIssues() sdkgo.Query[SearchIssuesInput, SearchIssuesOutput] {
	return operations.client.SearchIssues()
}
func (operations clientOperations) GetIssue() sdkgo.Query[GetIssueInput, Issue] {
	return operations.client.GetIssue()
}
func (operations clientOperations) CreateIssue() sdkgo.Mutation[CreateIssueInput, CreateIssueOutput] {
	return operations.client.CreateIssue()
}
func (operations clientOperations) UpdateIssue() sdkgo.Mutation[UpdateIssueInput, UpdateIssueOutput] {
	return operations.client.UpdateIssue()
}
func (operations clientOperations) AddComment() sdkgo.Mutation[AddCommentInput, AddCommentOutput] {
	return operations.client.AddComment()
}
func (operations clientOperations) FindUserByEmail() sdkgo.Query[FindUserByEmailInput, User] {
	return operations.client.FindUserByEmail()
}
func (operations clientOperations) ListWorkflowStates() sdkgo.Query[ListWorkflowStatesInput, ListWorkflowStatesOutput] {
	return operations.client.ListWorkflowStates()
}

// NewConnection wraps a client built with New, such as a test client with a static credential provider.
// Applications open declared connections with NewProjectConnection instead.
func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("linear connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("linear connector connection: %w", err)
	}
	return Connection{client: client, operations: clientOperations{client: client}, reference: reference}, nil
}

// NewConnectionWithOperations binds other operations, such as a generated mock package's, to a connection.
// The connection serves operation Steps only: Trigger factories and runners require NewConnection.
func NewConnectionWithOperations(operations Operations, reference sdkgo.ConnectionRef) (Connection, error) {
	if operations == nil {
		return Connection{}, fmt.Errorf("linear connector operations are required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("linear connector connection: %w", err)
	}
	return Connection{operations: operations, reference: reference}, nil
}

// NewProjectConnection opens the connection that dex-app.yaml declares as connectionName from the
// loaded project configuration. It reads ordinary settings now and resolves credentials during each call.
func NewProjectConnection(project *projectconfig.LoadedProject, connectionName string, options ...Option) (Connection, error) {
	if project == nil {
		return Connection{}, fmt.Errorf("linear connection requires the loaded project configuration")
	}
	reference := sdkgo.ConnectionRef{Provider: "linear", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("linear connection: %w", err)
	}
	key := projectconfig.ConnectionKey{ConnectorID: ConnectorID, ConnectionName: connectionName}
	var config Config
	if err := project.Configuration.DecodeConnectionConfiguration(key, &config); err != nil {
		return Connection{}, fmt.Errorf("linear connection %q settings: %w", connectionName, err)
	}
	credentials, err := provider.NewRefreshingCredentialProvider(project.Connections, key, decodeCredentials, encodeCredentials)
	if err != nil {
		return Connection{}, err
	}
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		AuthMethodID         string `json:"auth_method"`
		APIKey               string `json:"api_key"`
		WebhookSigningSecret string `json:"webhook_signing_secret"`
		OAuthClientID        string `json:"oauth_client_id"`
		OAuthClientSecret    string `json:"oauth_client_secret"`
		AccessToken          string `json:"access_token"`
		RefreshToken         string `json:"refresh_token"`
	}
	if err := projectconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		AuthMethodID:         fields.AuthMethodID,
		APIKey:               sdkgo.NewSecretString(fields.APIKey),
		WebhookSigningSecret: sdkgo.NewSecretString(fields.WebhookSigningSecret),
		OAuthClientID:        fields.OAuthClientID,
		OAuthClientSecret:    sdkgo.NewSecretString(fields.OAuthClientSecret),
		AccessToken:          sdkgo.NewSecretString(fields.AccessToken),
		RefreshToken:         sdkgo.NewSecretString(fields.RefreshToken),
	}
	return credentials, credentials.Validate()
}

func encodeCredentials(credentials Credentials) (json.RawMessage, error) {
	fields := struct {
		AuthMethodID         string `json:"auth_method"`
		APIKey               string `json:"api_key,omitempty"`
		WebhookSigningSecret string `json:"webhook_signing_secret,omitempty"`
		OAuthClientID        string `json:"oauth_client_id,omitempty"`
		OAuthClientSecret    string `json:"oauth_client_secret,omitempty"`
		AccessToken          string `json:"access_token,omitempty"`
		RefreshToken         string `json:"refresh_token,omitempty"`
	}{
		AuthMethodID:         credentials.AuthMethodID,
		APIKey:               credentials.APIKey.Reveal(),
		WebhookSigningSecret: credentials.WebhookSigningSecret.Reveal(),
		OAuthClientID:        credentials.OAuthClientID,
		OAuthClientSecret:    credentials.OAuthClientSecret.Reveal(),
		AccessToken:          credentials.AccessToken.Reveal(),
		RefreshToken:         credentials.RefreshToken.Reveal(),
	}
	return json.Marshal(fields)
}

func (connection Connection) validate() error {
	if connection.client == nil && connection.operations != nil {
		return fmt.Errorf("linear connector connection from NewConnectionWithOperations serves only operation Steps")
	}
	if connection.client == nil {
		return fmt.Errorf("linear connector connection is required")
	}
	return connection.reference.Validate()
}

func (connection Connection) validateOperations() error {
	if connection.operations == nil {
		return fmt.Errorf("linear connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("linear connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("linear connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("linear connector connections cannot be serialized")
}
func (Connection) String() string   { return "linear.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "linear.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		MaxResponseBytes:          4194304,
		WebhookMaxBodyBytes:       1048576,
		WebhookSignatureTolerance: time.Duration(60000000000),
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	if config.WebhookMaxBodyBytes == 0 {
		config.WebhookMaxBodyBytes = defaults.WebhookMaxBodyBytes
	}
	if config.WebhookSignatureTolerance == 0 {
		config.WebhookSignatureTolerance = defaults.WebhookSignatureTolerance
	}
	return config
}

func (config Config) Validate() error {
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	if config.WebhookMaxBodyBytes < 0 {
		return fmt.Errorf("configuration webhookMaxBodyBytes cannot be negative")
	}
	if config.WebhookSignatureTolerance < 0 {
		return fmt.Errorf("configuration webhookSignatureTolerance cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	switch credentials.AuthMethodID {
	case "personal-api-key":
		if credentials.APIKey.Reveal() == "" {
			return fmt.Errorf("credential api_key is required")
		}
	case "linear-oauth":
		if credentials.OAuthClientID == "" {
			return fmt.Errorf("credential oauth_client_id is required")
		}
		if credentials.OAuthClientSecret.Reveal() == "" {
			return fmt.Errorf("credential oauth_client_secret is required")
		}
		if credentials.AccessToken.Reveal() == "" {
			return fmt.Errorf("credential access_token is required")
		}
		if credentials.RefreshToken.Reveal() == "" {
			return fmt.Errorf("credential refresh_token is required")
		}
	default:
		return fmt.Errorf("credential auth_method is invalid")
	}
	return nil
}

var IssueEventReceivedTriggerDefinition = sdkgo.TriggerDefinition{
	Trigger:     sdkgo.TriggerRef{ConnectorID: ConnectorID, TriggerName: "issueEventReceived"},
	Description: "Receive a signed Linear Issue webhook for a created, updated, or removed issue, verified with its Linear-Signature and fresh webhookTimestamp; the event ID is the action, the issue UUID, and the issue's updatedAt.",
}

type IssueEventReceivedTriggerBindingConfig struct {
	sdkgo.TriggerBindingFactoryConfigMarker `connector:"factory=triggerBinding"`
	connectorID                             struct{}                       `connector:"connectorId=linear"`
	triggerName                             struct{}                       `connector:"triggerName=issueEventReceived"`
	ConnectionName                          string                         `connector:"connectionName"`
	BindingName                             string                         `connector:"bindingName"`
	ConfigurationUI                         sdkgo.ConnectorConfigurationUI `connector:"configurationUI"`
}

func DefineIssueEventReceivedTriggerBinding(config IssueEventReceivedTriggerBindingConfig) sdkgo.TriggerBindingDefinition {
	return sdkgo.MustTriggerBindingDefinition(sdkgo.TriggerBindingDefinition{
		Definition: IssueEventReceivedTriggerDefinition, ConnectionName: config.ConnectionName, BindingName: config.BindingName,
		ConfigurationUI: &config.ConfigurationUI,
	})
}

type IssueEventReceivedTriggerConfig struct {
	sdkgo.TriggerFactoryConfigMarker `connector:"factory=trigger"`
	connectorID                      struct{}                               `connector:"connectorId=linear"`
	triggerName                      struct{}                               `connector:"triggerName=issueEventReceived"`
	Connection                       Connection                             `connector:"connection"`
	ConnectionName                   string                                 `connector:"connectionName"`
	BindingName                      string                                 `connector:"bindingName"`
	Configuration                    IssueEventReceivedTriggerConfiguration `connector:"triggerConfiguration"`
	Target                           sdkgo.TriggerTarget[IssueEvent]        `connector:"triggerTarget"`
}

func NewIssueEventReceivedTrigger(config IssueEventReceivedTriggerConfig) sdkgo.TriggerRunner {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linear connector trigger ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	binding := sdkgo.TriggerBindingRef{Connection: config.Connection.reference, Trigger: IssueEventReceivedTriggerDefinition.Trigger, Name: config.BindingName}
	return sdkgo.MustNewTrigger(sdkgo.TriggerConfig[IssueEvent]{
		Definition: IssueEventReceivedTriggerDefinition, Binding: binding,
		Source: config.Connection.client.issueEventReceivedTriggerSource(config.Connection.reference, config.Configuration), Target: config.Target,
	})
}

const SearchIssuesBranchSearched sdkgo.BranchID = "searched"
const SearchIssuesBranchProviderRejected sdkgo.BranchID = "providerRejected"
const SearchIssuesBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const SearchIssuesBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var SearchIssuesDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "searchIssues"},
	Branches: []sdkgo.BranchDefinition{
		{ID: SearchIssuesBranchSearched, Description: "One page of matching issue summaries was read; it can be empty."},
		{ID: SearchIssuesBranchProviderRejected, Description: "Linear conclusively rejected the search, such as an invalid cursor, missing team access, or a rejected credential.", Optional: true},
		{ID: SearchIssuesBranchInvalidResponse, Description: "Linear returned an invalid or oversized page of issues.", Optional: true},
		{ID: SearchIssuesBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type SearchIssuesResult = sdkgo.QueryResult[SearchIssuesOutput]

type SearchIssuesStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                              `connector:"connectorId=linear"`
	operationID                    struct{}                                              `connector:"operationId=searchIssues"`
	StepType                       string                                                `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                 `connector:"annotations"`
	ConfigurationUI                sdkgo.ConnectorConfigurationUI                        `connector:"configurationUI"`
	Connection                     Connection                                            `connector:"connection"`
	ConnectionName                 string                                                `connector:"connectionName"`
	MapToOperationInput            func(IN) SearchIssuesInput                            `connector:"mapToOperationInput"`
	Searched                       sdkgo.Target[SearchIssuesResult]                      `connector:"branch=searched"`
	ProviderRejected               sdkgo.Target[SearchIssuesResult]                      `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[SearchIssuesResult]                      `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[SearchIssuesResult]                      `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[SearchIssuesOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                      `connector:"stepOptionsOverride"`
}

func NewSearchIssuesStep[IN any](config SearchIssuesStepConfig[IN]) sdkgo.QueryStep[IN, SearchIssuesInput, SearchIssuesOutput] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linear connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, SearchIssuesInput, SearchIssuesOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.operations.SearchIssues(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[SearchIssuesResult] {
			branches := make([]sdkgo.BranchTarget[SearchIssuesResult], 0, 4)
			if config.Searched.HasStep() {
				branches = append(branches, config.Searched.BranchTarget(SearchIssuesBranchSearched))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(SearchIssuesBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(SearchIssuesBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(SearchIssuesBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const GetIssueBranchFound sdkgo.BranchID = "found"
const GetIssueBranchNotFound sdkgo.BranchID = "notFound"
const GetIssueBranchProviderRejected sdkgo.BranchID = "providerRejected"
const GetIssueBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const GetIssueBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var GetIssueDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getIssue"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetIssueBranchFound, Description: "The issue was read."},
		{ID: GetIssueBranchNotFound, Description: "The issue does not exist, was deleted, or the connection cannot see its team.", Optional: true},
		{ID: GetIssueBranchProviderRejected, Description: "Linear conclusively rejected the issue read.", Optional: true},
		{ID: GetIssueBranchInvalidResponse, Description: "Linear returned an invalid or oversized issue.", Optional: true},
		{ID: GetIssueBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type GetIssueResult = sdkgo.QueryResult[Issue]

type GetIssueStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                 `connector:"connectorId=linear"`
	operationID                    struct{}                                 `connector:"operationId=getIssue"`
	StepType                       string                                   `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                    `connector:"annotations"`
	ConfigurationUI                sdkgo.ConnectorConfigurationUI           `connector:"configurationUI"`
	Connection                     Connection                               `connector:"connection"`
	ConnectionName                 string                                   `connector:"connectionName"`
	MapToOperationInput            func(IN) GetIssueInput                   `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[GetIssueResult]             `connector:"branch=found"`
	NotFound                       sdkgo.Target[GetIssueResult]             `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[GetIssueResult]             `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[GetIssueResult]             `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[GetIssueResult]             `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[Issue]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                         `connector:"stepOptionsOverride"`
}

func NewGetIssueStep[IN any](config GetIssueStepConfig[IN]) sdkgo.QueryStep[IN, GetIssueInput, Issue] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linear connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetIssueInput, Issue]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.operations.GetIssue(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[GetIssueResult] {
			branches := make([]sdkgo.BranchTarget[GetIssueResult], 0, 5)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(GetIssueBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(GetIssueBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(GetIssueBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(GetIssueBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(GetIssueBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const CreateIssueBranchCreated sdkgo.BranchID = "created"
const CreateIssueBranchProviderRejected sdkgo.BranchID = "providerRejected"
const CreateIssueBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var CreateIssueDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "createIssue"},
	Branches: []sdkgo.BranchDefinition{
		{ID: CreateIssueBranchCreated, Description: "Linear created the issue, or an earlier attempt of this Step already had, and the issue was read."},
		{ID: CreateIssueBranchProviderRejected, Description: "Linear conclusively rejected the issue, such as an unknown team, a workflow state or label of another team, or missing permission; unless Linear rejected the credential or permission, a read-back by the Step's UUID found no issue.", Optional: true},
		{ID: CreateIssueBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type CreateIssueResult = sdkgo.MutationResult[CreateIssueOutput]

type CreateIssueStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                                `connector:"connectorId=linear"`
	operationID                       struct{}                                                `connector:"operationId=createIssue"`
	StepType                          string                                                  `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                   `connector:"annotations"`
	ConfigurationUI                   sdkgo.ConnectorConfigurationUI                          `connector:"configurationUI"`
	Connection                        Connection                                              `connector:"connection"`
	ConnectionName                    string                                                  `connector:"connectionName"`
	MapToOperationInput               func(IN) CreateIssueInput                               `connector:"mapToOperationInput"`
	Created                           sdkgo.Target[CreateIssueResult]                         `connector:"branch=created"`
	ProviderRejected                  sdkgo.Target[CreateIssueResult]                         `connector:"branch=providerRejected,optional"`
	Defect                            sdkgo.Target[CreateIssueResult]                         `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[CreateIssueOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewCreateIssueStep[IN any](config CreateIssueStepConfig[IN]) sdkgo.MutationStep[IN, CreateIssueInput, CreateIssueOutput] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linear connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, CreateIssueInput, CreateIssueOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.operations.CreateIssue(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[CreateIssueResult] {
			branches := make([]sdkgo.BranchTarget[CreateIssueResult], 0, 3)
			if config.Created.HasStep() {
				branches = append(branches, config.Created.BranchTarget(CreateIssueBranchCreated))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(CreateIssueBranchProviderRejected))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(CreateIssueBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const UpdateIssueBranchUpdated sdkgo.BranchID = "updated"
const UpdateIssueBranchNotFound sdkgo.BranchID = "notFound"
const UpdateIssueBranchProviderRejected sdkgo.BranchID = "providerRejected"
const UpdateIssueBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const UpdateIssueBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var UpdateIssueDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "updateIssue"},
	Branches: []sdkgo.BranchDefinition{
		{ID: UpdateIssueBranchUpdated, Description: "Linear applied the change and returned the issue."},
		{ID: UpdateIssueBranchNotFound, Description: "The issue does not exist, was deleted, or the connection cannot see its team; nothing was changed.", Optional: true},
		{ID: UpdateIssueBranchProviderRejected, Description: "Linear conclusively rejected the change, such as a workflow state or label of another team, an unknown assignee, or missing permission.", Optional: true},
		{ID: UpdateIssueBranchInvalidResponse, Description: "Linear returned an invalid or oversized issue, so the change may have been applied; repeating the Step is safe.", Optional: true},
		{ID: UpdateIssueBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type UpdateIssueResult = sdkgo.MutationResult[UpdateIssueOutput]

type UpdateIssueStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                                `connector:"connectorId=linear"`
	operationID                       struct{}                                                `connector:"operationId=updateIssue"`
	StepType                          string                                                  `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                   `connector:"annotations"`
	ConfigurationUI                   sdkgo.ConnectorConfigurationUI                          `connector:"configurationUI"`
	Connection                        Connection                                              `connector:"connection"`
	ConnectionName                    string                                                  `connector:"connectionName"`
	MapToOperationInput               func(IN) UpdateIssueInput                               `connector:"mapToOperationInput"`
	Updated                           sdkgo.Target[UpdateIssueResult]                         `connector:"branch=updated"`
	NotFound                          sdkgo.Target[UpdateIssueResult]                         `connector:"branch=notFound,optional"`
	ProviderRejected                  sdkgo.Target[UpdateIssueResult]                         `connector:"branch=providerRejected,optional"`
	InvalidResponse                   sdkgo.Target[UpdateIssueResult]                         `connector:"branch=invalidResponse,optional"`
	Defect                            sdkgo.Target[UpdateIssueResult]                         `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[UpdateIssueOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewUpdateIssueStep[IN any](config UpdateIssueStepConfig[IN]) sdkgo.MutationStep[IN, UpdateIssueInput, UpdateIssueOutput] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linear connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, UpdateIssueInput, UpdateIssueOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.operations.UpdateIssue(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[UpdateIssueResult] {
			branches := make([]sdkgo.BranchTarget[UpdateIssueResult], 0, 5)
			if config.Updated.HasStep() {
				branches = append(branches, config.Updated.BranchTarget(UpdateIssueBranchUpdated))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(UpdateIssueBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(UpdateIssueBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(UpdateIssueBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(UpdateIssueBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const AddCommentBranchAdded sdkgo.BranchID = "added"
const AddCommentBranchNotFound sdkgo.BranchID = "notFound"
const AddCommentBranchProviderRejected sdkgo.BranchID = "providerRejected"
const AddCommentBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var AddCommentDefinition = sdkgo.MutationDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "addComment"},
	Branches: []sdkgo.BranchDefinition{
		{ID: AddCommentBranchAdded, Description: "Linear added the comment, or an earlier attempt of this Step already had, and the comment was read."},
		{ID: AddCommentBranchNotFound, Description: "The issue does not exist, was deleted, or the connection cannot see its team; nothing was added.", Optional: true},
		{ID: AddCommentBranchProviderRejected, Description: "Linear conclusively rejected the comment, such as missing permission; unless Linear rejected the credential or permission, a read-back by the Step's UUID found no comment.", Optional: true},
		{ID: AddCommentBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type AddCommentResult = sdkgo.MutationResult[AddCommentOutput]

type AddCommentStepConfig[IN any] struct {
	sdkgo.MutationFactoryConfigMarker `connector:"factory=mutation"`
	connectorID                       struct{}                                               `connector:"connectorId=linear"`
	operationID                       struct{}                                               `connector:"operationId=addComment"`
	StepType                          string                                                 `connector:"stepType"`
	Annotations                       sdkgo.StepAnnotations                                  `connector:"annotations"`
	ConfigurationUI                   sdkgo.ConnectorConfigurationUI                         `connector:"configurationUI"`
	Connection                        Connection                                             `connector:"connection"`
	ConnectionName                    string                                                 `connector:"connectionName"`
	MapToOperationInput               func(IN) AddCommentInput                               `connector:"mapToOperationInput"`
	Added                             sdkgo.Target[AddCommentResult]                         `connector:"branch=added"`
	NotFound                          sdkgo.Target[AddCommentResult]                         `connector:"branch=notFound,optional"`
	ProviderRejected                  sdkgo.Target[AddCommentResult]                         `connector:"branch=providerRejected,optional"`
	Defect                            sdkgo.Target[AddCommentResult]                         `connector:"branch=defect,optional"`
	ResultAttribute                   *dex.Attribute[sdkgo.MutationResult[AddCommentOutput]] `connector:"resultAttribute"`
	StepOptionsOverride               *dex.StepOptions                                       `connector:"stepOptionsOverride"`
}

func NewAddCommentStep[IN any](config AddCommentStepConfig[IN]) sdkgo.MutationStep[IN, AddCommentInput, AddCommentOutput] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linear connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewMutationStep(sdkgo.MutationStepConfig[IN, AddCommentInput, AddCommentOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.operations.AddComment(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[AddCommentResult] {
			branches := make([]sdkgo.BranchTarget[AddCommentResult], 0, 4)
			if config.Added.HasStep() {
				branches = append(branches, config.Added.BranchTarget(AddCommentBranchAdded))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(AddCommentBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(AddCommentBranchProviderRejected))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(AddCommentBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const FindUserByEmailBranchFound sdkgo.BranchID = "found"
const FindUserByEmailBranchNotFound sdkgo.BranchID = "notFound"
const FindUserByEmailBranchProviderRejected sdkgo.BranchID = "providerRejected"
const FindUserByEmailBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const FindUserByEmailBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var FindUserByEmailDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "findUserByEmail"},
	Branches: []sdkgo.BranchDefinition{
		{ID: FindUserByEmailBranchFound, Description: "The user was found."},
		{ID: FindUserByEmailBranchNotFound, Description: "No user of the workspace has the email, or the user is disabled and disabled users were not requested.", Optional: true},
		{ID: FindUserByEmailBranchProviderRejected, Description: "Linear conclusively rejected the user lookup.", Optional: true},
		{ID: FindUserByEmailBranchInvalidResponse, Description: "Linear returned an invalid or oversized user list.", Optional: true},
		{ID: FindUserByEmailBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type FindUserByEmailResult = sdkgo.QueryResult[User]

type FindUserByEmailStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                `connector:"connectorId=linear"`
	operationID                    struct{}                                `connector:"operationId=findUserByEmail"`
	StepType                       string                                  `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                   `connector:"annotations"`
	ConfigurationUI                sdkgo.ConnectorConfigurationUI          `connector:"configurationUI"`
	Connection                     Connection                              `connector:"connection"`
	ConnectionName                 string                                  `connector:"connectionName"`
	MapToOperationInput            func(IN) FindUserByEmailInput           `connector:"mapToOperationInput"`
	Found                          sdkgo.Target[FindUserByEmailResult]     `connector:"branch=found"`
	NotFound                       sdkgo.Target[FindUserByEmailResult]     `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[FindUserByEmailResult]     `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[FindUserByEmailResult]     `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[FindUserByEmailResult]     `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[User]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                        `connector:"stepOptionsOverride"`
}

func NewFindUserByEmailStep[IN any](config FindUserByEmailStepConfig[IN]) sdkgo.QueryStep[IN, FindUserByEmailInput, User] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linear connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, FindUserByEmailInput, User]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.operations.FindUserByEmail(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[FindUserByEmailResult] {
			branches := make([]sdkgo.BranchTarget[FindUserByEmailResult], 0, 5)
			if config.Found.HasStep() {
				branches = append(branches, config.Found.BranchTarget(FindUserByEmailBranchFound))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(FindUserByEmailBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(FindUserByEmailBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(FindUserByEmailBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(FindUserByEmailBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const ListWorkflowStatesBranchListed sdkgo.BranchID = "listed"
const ListWorkflowStatesBranchNotFound sdkgo.BranchID = "notFound"
const ListWorkflowStatesBranchProviderRejected sdkgo.BranchID = "providerRejected"
const ListWorkflowStatesBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const ListWorkflowStatesBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var ListWorkflowStatesDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "listWorkflowStates"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ListWorkflowStatesBranchListed, Description: "The team's workflow states were read."},
		{ID: ListWorkflowStatesBranchNotFound, Description: "The team does not exist or the connection cannot see it.", Optional: true},
		{ID: ListWorkflowStatesBranchProviderRejected, Description: "Linear conclusively rejected the read.", Optional: true},
		{ID: ListWorkflowStatesBranchInvalidResponse, Description: "Linear returned an invalid or oversized list of workflow states.", Optional: true},
		{ID: ListWorkflowStatesBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid.", Optional: true},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(60000000000), MaximumAttempts: 6, TotalDuration: time.Duration(300000000000)},
		ExecuteDurability: dex.StepDurabilityAsync,
	},
}

type ListWorkflowStatesResult = sdkgo.QueryResult[ListWorkflowStatesOutput]

type ListWorkflowStatesStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                                    `connector:"connectorId=linear"`
	operationID                    struct{}                                                    `connector:"operationId=listWorkflowStates"`
	StepType                       string                                                      `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                       `connector:"annotations"`
	ConfigurationUI                sdkgo.ConnectorConfigurationUI                              `connector:"configurationUI"`
	Connection                     Connection                                                  `connector:"connection"`
	ConnectionName                 string                                                      `connector:"connectionName"`
	MapToOperationInput            func(IN) ListWorkflowStatesInput                            `connector:"mapToOperationInput"`
	Listed                         sdkgo.Target[ListWorkflowStatesResult]                      `connector:"branch=listed"`
	NotFound                       sdkgo.Target[ListWorkflowStatesResult]                      `connector:"branch=notFound,optional"`
	ProviderRejected               sdkgo.Target[ListWorkflowStatesResult]                      `connector:"branch=providerRejected,optional"`
	InvalidResponse                sdkgo.Target[ListWorkflowStatesResult]                      `connector:"branch=invalidResponse,optional"`
	Defect                         sdkgo.Target[ListWorkflowStatesResult]                      `connector:"branch=defect,optional"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[ListWorkflowStatesOutput]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                            `connector:"stepOptionsOverride"`
}

func NewListWorkflowStatesStep[IN any](config ListWorkflowStatesStepConfig[IN]) sdkgo.QueryStep[IN, ListWorkflowStatesInput, ListWorkflowStatesOutput] {
	if err := config.Connection.validateOperations(); err != nil {
		panic(err)
	}
	if config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linear connector Step ConnectionName %q must equal its connection's name %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, ListWorkflowStatesInput, ListWorkflowStatesOutput]{
		StepType: config.StepType, Annotations: config.Annotations,
		ConfigurationUI: config.ConfigurationUI,
		Operation:       config.Connection.operations.ListWorkflowStates(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: func() []sdkgo.BranchTarget[ListWorkflowStatesResult] {
			branches := make([]sdkgo.BranchTarget[ListWorkflowStatesResult], 0, 5)
			if config.Listed.HasStep() {
				branches = append(branches, config.Listed.BranchTarget(ListWorkflowStatesBranchListed))
			}
			if config.NotFound.HasStep() {
				branches = append(branches, config.NotFound.BranchTarget(ListWorkflowStatesBranchNotFound))
			}
			if config.ProviderRejected.HasStep() {
				branches = append(branches, config.ProviderRejected.BranchTarget(ListWorkflowStatesBranchProviderRejected))
			}
			if config.InvalidResponse.HasStep() {
				branches = append(branches, config.InvalidResponse.BranchTarget(ListWorkflowStatesBranchInvalidResponse))
			}
			if config.Defect.HasStep() {
				branches = append(branches, config.Defect.BranchTarget(ListWorkflowStatesBranchDefect))
			}
			return branches
		}(),
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
