// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package githubconnector

import (
	"encoding/json"
	"fmt"
	"net/url"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/localconfig"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "github"

type Config struct {
	BaseURL                string        `json:"baseUrl,omitempty" yaml:"baseUrl,omitempty"`
	APIVersion             string        `json:"apiVersion,omitempty" yaml:"apiVersion,omitempty"`
	Timeout                time.Duration `json:"timeout,omitempty" yaml:"timeout,omitempty"`
	MaxResponseBytes       int64         `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
	DefaultRepositoryLimit int64         `json:"defaultRepositoryLimit,omitempty" yaml:"defaultRepositoryLimit,omitempty"`
	MaxRepositories        int64         `json:"maxRepositories,omitempty" yaml:"maxRepositories,omitempty"`
}

type Credentials struct {
	AccessToken sdkgo.SecretString
}

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("github connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("github connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewLocalConnection loads startup configuration and reloads credentials before every provider call.
func NewLocalConnection(store *localconfig.Store, connectionName string, options ...Option) (Connection, error) {
	if store == nil {
		return Connection{}, fmt.Errorf("local connector configuration store is required")
	}
	reference := sdkgo.ConnectionRef{Provider: "github", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("github local connection: %w", err)
	}
	var config Config
	if err := store.DecodeConfiguration(ConnectorID, connectionName, &config); err != nil {
		return Connection{}, err
	}
	credentials := localconfig.NewCredentialProvider(store, ConnectorID, connectionName, decodeLocalCredentials)
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeLocalCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		AccessToken string `json:"access_token"`
	}
	if err := localconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		AccessToken: sdkgo.NewSecretString(fields.AccessToken),
	}
	return credentials, credentials.Validate()
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("github connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("github connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("github connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("github connector connections cannot be serialized")
}
func (Connection) String() string   { return "githubconnector.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "githubconnector.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		BaseURL:                "https://api.github.com",
		APIVersion:             "2026-03-10",
		Timeout:                time.Duration(15000000000),
		MaxResponseBytes:       2097152,
		DefaultRepositoryLimit: 100,
		MaxRepositories:        500,
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.BaseURL == "" {
		config.BaseURL = defaults.BaseURL
	}
	if config.APIVersion == "" {
		config.APIVersion = defaults.APIVersion
	}
	if config.Timeout == 0 {
		config.Timeout = defaults.Timeout
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	if config.DefaultRepositoryLimit == 0 {
		config.DefaultRepositoryLimit = defaults.DefaultRepositoryLimit
	}
	if config.MaxRepositories == 0 {
		config.MaxRepositories = defaults.MaxRepositories
	}
	return config
}

func (config Config) Validate() error {
	if config.BaseURL != "" {
		parsed, err := url.Parse(config.BaseURL)
		if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
			return fmt.Errorf("configuration baseUrl must be an absolute URL")
		}
	}
	if config.Timeout < 0 {
		return fmt.Errorf("configuration timeout cannot be negative")
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	if config.DefaultRepositoryLimit < 0 {
		return fmt.Errorf("configuration defaultRepositoryLimit cannot be negative")
	}
	if config.MaxRepositories < 0 {
		return fmt.Errorf("configuration maxRepositories cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	if credentials.AccessToken.Reveal() == "" {
		return fmt.Errorf("credential access_token is required")
	}
	return nil
}

const GetAuthenticatedProfileBranchProfileLoaded sdkgo.BranchID = "profileLoaded"
const GetAuthenticatedProfileBranchVerifiedEmailRequired sdkgo.BranchID = "verifiedEmailRequired"
const GetAuthenticatedProfileBranchInsufficientScope sdkgo.BranchID = "insufficientScope"
const GetAuthenticatedProfileBranchAuthorizationRevoked sdkgo.BranchID = "authorizationRevoked"
const GetAuthenticatedProfileBranchNotFound sdkgo.BranchID = "notFound"
const GetAuthenticatedProfileBranchFailed sdkgo.BranchID = "failed"
const GetAuthenticatedProfileBranchDefect sdkgo.BranchID = "defect"

var GetAuthenticatedProfileDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getAuthenticatedProfile"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetAuthenticatedProfileBranchProfileLoaded, Description: "The authenticated profile and primary verified email were loaded."},
		{ID: GetAuthenticatedProfileBranchVerifiedEmailRequired, Description: "A primary verified email was not available."},
		{ID: GetAuthenticatedProfileBranchInsufficientScope, Description: "The OAuth grant does not match the required scopes."},
		{ID: GetAuthenticatedProfileBranchAuthorizationRevoked, Description: "The OAuth grant is invalid or revoked."},
		{ID: GetAuthenticatedProfileBranchNotFound, Description: "The authenticated account was not found."},
		{ID: GetAuthenticatedProfileBranchFailed, Description: "GitHub returned a terminal provider or protocol failure."},
		{ID: GetAuthenticatedProfileBranchDefect, Description: "Local configuration or input is invalid."},
	},
	DefectBranch: GetAuthenticatedProfileBranchDefect,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementRequired,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type GetAuthenticatedProfileResult = sdkgo.QueryResult[AuthenticatedProfile]

type GetAuthenticatedProfileStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                                `connector:"connectorId=github"`
	operationID                    struct{}                                                `connector:"operationId=getAuthenticatedProfile"`
	StepType                       string                                                  `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                   `connector:"annotations"`
	Connection                     Connection                                              `connector:"connection"`
	ConnectionName                 string                                                  `connector:"connectionName"`
	BuildOperationInput            func(IN) (GetAuthenticatedProfileInput, error)          `connector:"buildOperationInput"`
	ProfileLoaded                  sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=profileLoaded"`
	VerifiedEmailRequired          sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=verifiedEmailRequired"`
	InsufficientScope              sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=insufficientScope"`
	AuthorizationRevoked           sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=authorizationRevoked"`
	NotFound                       sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=notFound"`
	Failed                         sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=failed"`
	Defect                         sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=defect"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[AuthenticatedProfile]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewGetAuthenticatedProfileStep[IN any](config GetAuthenticatedProfileStepConfig[IN]) sdkgo.QueryStep[IN, GetAuthenticatedProfileInput, AuthenticatedProfile] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("github connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetAuthenticatedProfileInput, AuthenticatedProfile]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.GetAuthenticatedProfile(), Connection: config.Connection.reference,
		BuildOperationInput: config.BuildOperationInput,
		Branches: []sdkgo.BranchTarget[GetAuthenticatedProfileResult]{
			config.ProfileLoaded.BranchTarget(GetAuthenticatedProfileBranchProfileLoaded),
			config.VerifiedEmailRequired.BranchTarget(GetAuthenticatedProfileBranchVerifiedEmailRequired),
			config.InsufficientScope.BranchTarget(GetAuthenticatedProfileBranchInsufficientScope),
			config.AuthorizationRevoked.BranchTarget(GetAuthenticatedProfileBranchAuthorizationRevoked),
			config.NotFound.BranchTarget(GetAuthenticatedProfileBranchNotFound),
			config.Failed.BranchTarget(GetAuthenticatedProfileBranchFailed),
			config.Defect.BranchTarget(GetAuthenticatedProfileBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}

const ListPublicRepositoriesBranchRepositoriesLoaded sdkgo.BranchID = "repositoriesLoaded"
const ListPublicRepositoriesBranchInsufficientScope sdkgo.BranchID = "insufficientScope"
const ListPublicRepositoriesBranchAuthorizationRevoked sdkgo.BranchID = "authorizationRevoked"
const ListPublicRepositoriesBranchNotFound sdkgo.BranchID = "notFound"
const ListPublicRepositoriesBranchFailed sdkgo.BranchID = "failed"
const ListPublicRepositoriesBranchDefect sdkgo.BranchID = "defect"

var ListPublicRepositoriesDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "listPublicRepositories"},
	Branches: []sdkgo.BranchDefinition{
		{ID: ListPublicRepositoriesBranchRepositoriesLoaded, Description: "Public repositories were loaded and bounded."},
		{ID: ListPublicRepositoriesBranchInsufficientScope, Description: "The OAuth grant does not match the required scopes."},
		{ID: ListPublicRepositoriesBranchAuthorizationRevoked, Description: "The OAuth grant is invalid or revoked."},
		{ID: ListPublicRepositoriesBranchNotFound, Description: "The requested GitHub account was not found."},
		{ID: ListPublicRepositoriesBranchFailed, Description: "GitHub returned a terminal provider or protocol failure."},
		{ID: ListPublicRepositoriesBranchDefect, Description: "Local configuration or input is invalid."},
	},
	DefectBranch: ListPublicRepositoriesBranchDefect,
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
	ResultAttribute: sdkgo.RequirementRequired,
	Progress:        sdkgo.ProgressCapabilities{Structured: false, Text: false},
}

type ListPublicRepositoriesResult = sdkgo.QueryResult[PublicRepositories]

type ListPublicRepositoriesStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                              `connector:"connectorId=github"`
	operationID                    struct{}                                              `connector:"operationId=listPublicRepositories"`
	StepType                       string                                                `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                 `connector:"annotations"`
	Connection                     Connection                                            `connector:"connection"`
	ConnectionName                 string                                                `connector:"connectionName"`
	BuildOperationInput            func(IN) (ListPublicRepositoriesInput, error)         `connector:"buildOperationInput"`
	RepositoriesLoaded             sdkgo.Target[ListPublicRepositoriesResult]            `connector:"branch=repositoriesLoaded"`
	InsufficientScope              sdkgo.Target[ListPublicRepositoriesResult]            `connector:"branch=insufficientScope"`
	AuthorizationRevoked           sdkgo.Target[ListPublicRepositoriesResult]            `connector:"branch=authorizationRevoked"`
	NotFound                       sdkgo.Target[ListPublicRepositoriesResult]            `connector:"branch=notFound"`
	Failed                         sdkgo.Target[ListPublicRepositoriesResult]            `connector:"branch=failed"`
	Defect                         sdkgo.Target[ListPublicRepositoriesResult]            `connector:"branch=defect"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[PublicRepositories]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                      `connector:"stepOptionsOverride"`
}

func NewListPublicRepositoriesStep[IN any](config ListPublicRepositoriesStepConfig[IN]) sdkgo.QueryStep[IN, ListPublicRepositoriesInput, PublicRepositories] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("github connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, ListPublicRepositoriesInput, PublicRepositories]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.ListPublicRepositories(), Connection: config.Connection.reference,
		BuildOperationInput: config.BuildOperationInput,
		Branches: []sdkgo.BranchTarget[ListPublicRepositoriesResult]{
			config.RepositoriesLoaded.BranchTarget(ListPublicRepositoriesBranchRepositoriesLoaded),
			config.InsufficientScope.BranchTarget(ListPublicRepositoriesBranchInsufficientScope),
			config.AuthorizationRevoked.BranchTarget(ListPublicRepositoriesBranchAuthorizationRevoked),
			config.NotFound.BranchTarget(ListPublicRepositoriesBranchNotFound),
			config.Failed.BranchTarget(ListPublicRepositoriesBranchFailed),
			config.Defect.BranchTarget(ListPublicRepositoriesBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
