// Code generated by connectorctl generate; DO NOT EDIT.
// Copyright (c) 2026 Super Durable
// SPDX-License-Identifier: MIT

package linkedinconnector

import (
	"encoding/json"
	"fmt"
	"net/url"
	"time"

	"github.com/superdurable/dex-connectors-library/sdkgo"
	"github.com/superdurable/dex-connectors-library/sdkgo/localconfig"
	"github.com/superdurable/dex/sdk-go/dex"
)

const ConnectorID = "linkedin"

type Config struct {
	UserInfoURL      string        `json:"userInfoUrl,omitempty" yaml:"userInfoUrl,omitempty"`
	Timeout          time.Duration `json:"timeout,omitempty" yaml:"timeout,omitempty"`
	MaxResponseBytes int64         `json:"maxResponseBytes,omitempty" yaml:"maxResponseBytes,omitempty"`
}

type Credentials struct {
	AccessToken sdkgo.SecretString
}

type Connection struct {
	client    *Client
	reference sdkgo.ConnectionRef
}

func NewConnection(client *Client, reference sdkgo.ConnectionRef) (Connection, error) {
	if client == nil {
		return Connection{}, fmt.Errorf("linkedin connector client is required")
	}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("linkedin connector connection: %w", err)
	}
	return Connection{client: client, reference: reference}, nil
}

// NewLocalConnection loads startup configuration and reloads credentials before every provider call.
func NewLocalConnection(store *localconfig.Store, connectionName string, options ...Option) (Connection, error) {
	if store == nil {
		return Connection{}, fmt.Errorf("local connector configuration store is required")
	}
	reference := sdkgo.ConnectionRef{Provider: "linkedin", Name: connectionName}
	if err := reference.Validate(); err != nil {
		return Connection{}, fmt.Errorf("linkedin local connection: %w", err)
	}
	var config Config
	if err := store.DecodeConfiguration(ConnectorID, connectionName, &config); err != nil {
		return Connection{}, err
	}
	credentials := localconfig.NewCredentialProvider(store, ConnectorID, connectionName, decodeLocalCredentials)
	client, err := New(config, credentials, options...)
	if err != nil {
		return Connection{}, err
	}
	return NewConnection(client, reference)
}

func decodeLocalCredentials(contents json.RawMessage) (Credentials, error) {
	var fields struct {
		AccessToken string `json:"access_token"`
	}
	if err := localconfig.DecodeCredentials(contents, &fields); err != nil {
		return Credentials{}, err
	}
	credentials := Credentials{
		AccessToken: sdkgo.NewSecretString(fields.AccessToken),
	}
	return credentials, credentials.Validate()
}

func (connection Connection) validate() error {
	if connection.client == nil {
		return fmt.Errorf("linkedin connector connection is required")
	}
	return connection.reference.Validate()
}

func (Connection) MarshalJSON() ([]byte, error) {
	return nil, fmt.Errorf("linkedin connector connections cannot be serialized")
}
func (Connection) MarshalText() ([]byte, error) {
	return nil, fmt.Errorf("linkedin connector connections cannot be serialized")
}
func (Connection) MarshalYAML() (any, error) {
	return nil, fmt.Errorf("linkedin connector connections cannot be serialized")
}
func (Connection) String() string   { return "linkedinconnector.Connection{[REDACTED]}" }
func (Connection) GoString() string { return "linkedinconnector.Connection{[REDACTED]}" }

func DefaultConfig() Config {
	return Config{
		UserInfoURL:      "https://api.linkedin.com/v2/userinfo",
		Timeout:          time.Duration(15000000000),
		MaxResponseBytes: 1048576,
	}
}

func withConfigDefaults(config Config) Config {
	defaults := DefaultConfig()
	if config.UserInfoURL == "" {
		config.UserInfoURL = defaults.UserInfoURL
	}
	if config.Timeout == 0 {
		config.Timeout = defaults.Timeout
	}
	if config.MaxResponseBytes == 0 {
		config.MaxResponseBytes = defaults.MaxResponseBytes
	}
	return config
}

func (config Config) Validate() error {
	if config.UserInfoURL != "" {
		parsed, err := url.Parse(config.UserInfoURL)
		if err != nil || parsed.Scheme == "" || parsed.Hostname() == "" {
			return fmt.Errorf("configuration userInfoUrl must be an absolute URL")
		}
	}
	if config.Timeout < 0 {
		return fmt.Errorf("configuration timeout cannot be negative")
	}
	if config.MaxResponseBytes < 0 {
		return fmt.Errorf("configuration maxResponseBytes cannot be negative")
	}
	return nil
}

func (credentials Credentials) Validate() error {
	if credentials.AccessToken.Reveal() == "" {
		return fmt.Errorf("credential access_token is required")
	}
	return nil
}

const GetAuthenticatedProfileBranchProfileLoaded sdkgo.BranchID = "profileLoaded"
const GetAuthenticatedProfileBranchVerifiedEmailRequired sdkgo.BranchID = "verifiedEmailRequired"
const GetAuthenticatedProfileBranchInsufficientScope sdkgo.BranchID = "insufficientScope"
const GetAuthenticatedProfileBranchAuthorizationRevoked sdkgo.BranchID = "authorizationRevoked"
const GetAuthenticatedProfileBranchNotFound sdkgo.BranchID = "notFound"
const GetAuthenticatedProfileBranchProviderRejected sdkgo.BranchID = "providerRejected"
const GetAuthenticatedProfileBranchInvalidResponse sdkgo.BranchID = "invalidResponse"
const GetAuthenticatedProfileBranchDefect sdkgo.BranchID = sdkgo.DefectBranchID

var GetAuthenticatedProfileDefinition = sdkgo.QueryDefinition{
	Operation: sdkgo.OperationRef{ConnectorID: ConnectorID, OperationID: "getAuthenticatedProfile"},
	Branches: []sdkgo.BranchDefinition{
		{ID: GetAuthenticatedProfileBranchProfileLoaded, Description: "The authenticated profile and verified email were loaded."},
		{ID: GetAuthenticatedProfileBranchVerifiedEmailRequired, Description: "A verified email was not available."},
		{ID: GetAuthenticatedProfileBranchInsufficientScope, Description: "The OpenID Connect grant lacks required authorization."},
		{ID: GetAuthenticatedProfileBranchAuthorizationRevoked, Description: "The OpenID Connect grant is invalid or revoked."},
		{ID: GetAuthenticatedProfileBranchNotFound, Description: "The authenticated member was not found."},
		{ID: GetAuthenticatedProfileBranchProviderRejected, Description: "LinkedIn conclusively rejected the profile query."},
		{ID: GetAuthenticatedProfileBranchInvalidResponse, Description: "LinkedIn returned an invalid or oversized profile response."},
		{ID: GetAuthenticatedProfileBranchDefect, Description: "Local input, connection configuration, or connector definition is invalid."},
	},
	StepDefaults: sdkgo.StepDefaults{
		ExecuteMethodTimeout: time.Duration(30000000000), HeartbeatTimeout: time.Duration(0),
		ExecuteRetry:      &dex.RetryPolicy{InitialInterval: time.Duration(1000000000), BackoffCoefficient: 2, MaximumInterval: time.Duration(30000000000), MaximumAttempts: 5, TotalDuration: time.Duration(120000000000)},
		ExecuteDurability: dex.StepDurabilitySync,
	},
}

type GetAuthenticatedProfileResult = sdkgo.QueryResult[AuthenticatedProfile]

type GetAuthenticatedProfileStepConfig[IN any] struct {
	sdkgo.QueryFactoryConfigMarker `connector:"factory=query"`
	connectorID                    struct{}                                                `connector:"connectorId=linkedin"`
	operationID                    struct{}                                                `connector:"operationId=getAuthenticatedProfile"`
	StepType                       string                                                  `connector:"stepType"`
	Annotations                    sdkgo.StepAnnotations                                   `connector:"annotations"`
	Connection                     Connection                                              `connector:"connection"`
	ConnectionName                 string                                                  `connector:"connectionName"`
	MapToOperationInput            func(IN) GetAuthenticatedProfileInput                   `connector:"mapToOperationInput"`
	ProfileLoaded                  sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=profileLoaded"`
	VerifiedEmailRequired          sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=verifiedEmailRequired"`
	InsufficientScope              sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=insufficientScope"`
	AuthorizationRevoked           sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=authorizationRevoked"`
	NotFound                       sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=notFound"`
	ProviderRejected               sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=providerRejected"`
	InvalidResponse                sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=invalidResponse"`
	Defect                         sdkgo.Target[GetAuthenticatedProfileResult]             `connector:"branch=defect"`
	ResultAttribute                *dex.Attribute[sdkgo.QueryResult[AuthenticatedProfile]] `connector:"resultAttribute"`
	StepOptionsOverride            *dex.StepOptions                                        `connector:"stepOptionsOverride"`
}

func NewGetAuthenticatedProfileStep[IN any](config GetAuthenticatedProfileStepConfig[IN]) sdkgo.QueryStep[IN, GetAuthenticatedProfileInput, AuthenticatedProfile] {
	if err := config.Connection.validate(); err != nil {
		panic(err)
	}
	if config.ConnectionName != "" && config.ConnectionName != config.Connection.reference.Name {
		panic(fmt.Errorf("linkedin connector configuration connection name %q does not match runtime connection %q", config.ConnectionName, config.Connection.reference.Name))
	}
	return sdkgo.MustNewQueryStep(sdkgo.QueryStepConfig[IN, GetAuthenticatedProfileInput, AuthenticatedProfile]{
		StepType: config.StepType, Annotations: config.Annotations,
		Operation: config.Connection.client.GetAuthenticatedProfile(), Connection: config.Connection.reference,
		MapToOperationInput: config.MapToOperationInput,
		Branches: []sdkgo.BranchTarget[GetAuthenticatedProfileResult]{
			config.ProfileLoaded.BranchTarget(GetAuthenticatedProfileBranchProfileLoaded),
			config.VerifiedEmailRequired.BranchTarget(GetAuthenticatedProfileBranchVerifiedEmailRequired),
			config.InsufficientScope.BranchTarget(GetAuthenticatedProfileBranchInsufficientScope),
			config.AuthorizationRevoked.BranchTarget(GetAuthenticatedProfileBranchAuthorizationRevoked),
			config.NotFound.BranchTarget(GetAuthenticatedProfileBranchNotFound),
			config.ProviderRejected.BranchTarget(GetAuthenticatedProfileBranchProviderRejected),
			config.InvalidResponse.BranchTarget(GetAuthenticatedProfileBranchInvalidResponse),
			config.Defect.BranchTarget(GetAuthenticatedProfileBranchDefect),
		},
		ResultAttribute:     config.ResultAttribute,
		StepOptionsOverride: config.StepOptionsOverride,
	})
}
